### ISSUE TITLE
own assembler mov syntax

### ISSUE THREAD

**Issue by GoogleCodeExporter** [eteran/edb-debugger#109]
It would be nice if the assembler would show `mov` instructions not at `mov eax, ebx`, but as `mov: eax <- ebx`

Some advantages:
1. It is much clearer and easier to understand 
2. When switching between AT&T and Intel syntax, you get otherwise horrible confused
3. Since edb is often used for reverse engineering, it doesn't need to display the real `mov`s and should abstract as much as possible. (it could even collapse different moves together, or show variable names for `[ebp+...]` addresses)
4. It can export the traditional syntax, e.g. when copying it in the clipboard, so there is no disadvantage .

**Comment by AaronOpfer** [comment]
This sounds like a lot of work for what ultimately is a nice-to-have. I feel that most people cracking open edb are "gurus" who won't really need this.

**Comment by eteran** [comment]
I definitely agree. I think that at best, we can look at this issue as "maybe we can modularize the disassembler so it can be replaced by user plugins". Then they can create any syntax they like. I think that's about as far as is reasonable to go on this one.

**Comment by eteran** [comment]
Closing, this was an interesting idea inspired by radare, but I don't think it'll ever happen.

Eventually, we may come up with a good "Disassembly Engine" API which would allow 3rd party developers to implement something like this themselves if they **really** want it.
