### ISSUE TITLE
could not load symbol file

### ISSUE THREAD

**Issue by GoogleCodeExporter** [eteran/edb-debugger#115]
```
I don't know if it is possible, but , anyway, I haven't found way to do this.
I have compiled my program with fasm that way:
'fasm anyname.asm -s anyname.map', which give me two files:
'anyname' - executable file, which is compilied program
'anyname.map' - is symbols-file, provided by fasm for debugging.

so, i haven't found a way to use last one with EDB.
'Symbol Directory' option points to directory, where both files are.
```

Original issue reported on code.google.com by `evan.teran` on 3 Oct 2012 at 3:22

**Comment by eteran** [comment]
I think is going to be a "won't fix" for now. This was a one off request, and I'm not sure that the OP is still looking for this functionality. If anyone else is interested in fasm map file support, please reopen the issue and I will revisit this idea.
