### ISSUE TITLE
failed to open and attach to process please check privileges and try again

### ISSUE THREAD

**Issue by GoogleCodeExporter** [eteran/edb-debugger#133]
What steps will reproduce the problem?
1. While running edb it give privilege error?
2. When i try to debug any exe it says failed to open and attach to process 
please check privileges and try again?

I tried different exe, but it is not disassemble any exe.

What version of the product are you using? On what operating system?
version: 0.9.20
Ubuntu 12.04 LTS

Attachments:
- [edb issue.png](https://storage.googleapis.com/google-code-attachments/edb-debugger/issue-133/comment-0/edb issue.png)

**Comment by eteran** [comment]
Not sure if this is still an issue.

**Comment by T3KT4K** [comment]
still an issue for me

**Comment by eteran** [comment]
@T3KT4K Can you provide any details? I was never able to reproduce this issue for the original reporter.

Does it happen for all binaries or just some? If so, which ones?
Are you using the latest git master, or a versioned build?
What distribution are you using?

The only thing I can say, is that so far, I've only seen similar behavior when using broken nvidia drivers. if there is any details that you can help narrow down the issue, I'd love to help!

**Comment by 10110111** [comment]
Likely related to [this](http://askubuntu.com/questions/41629/after-upgrade-gdb-wont-attach-to-process).

**Comment by eteran** [comment]
No real follow up on this, and it seems to be possibly an issue introduced by a specific version of Ubuntu. We can always re-open if this proves to be an issue for users.
