### ISSUE TITLE
It will be helpful to show callled program name when step into another program call by main at the top of the menu

### ISSUE THREAD

**Issue by GoogleCodeExporter** [eteran/edb-debugger#135]
```
The top of the menu always show the name of main program.

It will be very helpful to show callled program name when step into another 
program call by main at the top of the menu.


```

Original issue reported on code.google.com by `bridg...@gmail.com` on 8 Aug 2014 at 12:32

**Comment by eteran** [comment]
Not 100% sure what this is asking for since edb doesn't step into other programs? Perhaps he's asking for the function name to be displayed? 

Since that can be found in the register view, I'm closing this issue.
