### ISSUE TITLE
MOVD instruction is disassembled wrongly (as MOVQ) in x86-64 mode

### ISSUE THREAD

**Issue by 10110111** [eteran/edb-debugger#148]
Several MOVD instruction variants, e.g. the following ones, on x86-64 system, are disassembled as MOVQ instead:

`0f 7e f0` `movq rax, mm6` // correct would be `movd eax,mm6`
`0f 6e f8` `movq mm7, rax` // correct would be `movd mm7,eax`
`66 44 0f 6e d1` `movq xmm10, rcx` // correct is `movd xmm10,ecx`

I've checked this with Intel's instruction set reference, GDB and their effect on registers. All these checks support my assertion that these instructions are actually MOVD, not MOVQ.

The list of instruction variants is not exhaustive, there might be some other variants handled wrongly too.

**Comment by eteran** [comment]
I'll look into it. Fortunately, the there is a lot of shared code, so fixing it in one spot will likely fix it in several variants.

**Comment by eteran** [comment]
I think this should fix it. Interestingly, I had specific comments in the code saying "This is different on x86-64 vs x86" and had deliberate alternate table entries for those instructions on x86-64. I must have simply misread the documentation though. All sources I looked at agree with you :-)
