### ISSUE TITLE
No keyboard shortcut for Toggle Breakpoint

### ISSUE THREAD

**Issue by 10110111** [eteran/edb-debugger#149]
Currently I can toggle a breakpoint by clicking on the address in CPU view (found this by reading the sources). But apparently there's no keyboard shortcut for this.
In fact, I've found that there is some action for this defined in Debugger.ui with shortcut of F2, but apparently it isn't actually used.
Could we have this keyboard shortcut working?

**Comment by eteran** [comment]
Sure thing, adding more keyboard shortcuts (and ensuring that they are working) is something I've been meaning to do. Now is as good a time as any :-)

**Comment by 10110111** [comment]
This has been fixed by #177.
