### ISSUE TITLE
MOVSD instruction is disassembled to take XMMWORD memory operand instead of QWORD

### ISSUE THREAD

**Issue by 10110111** [eteran/edb-debugger#152]
Consider the following instruction:

    f2 0f 10 05 c0 87 04 08

It's disassembled by EDB as

    movsd xmm0, xmmword ptr [0x08487c0]

But it's "move single double" (c.f. `movapd`, which is "move aligned _packed_ doubles"), i.e. it takes a `qword` operand, so should rather be

    movsd xmm0, qword ptr [0x08487c0]

The same is about the reverse: `movsd [esp+152],xmm0`:

    f2 0f 11 84 24 98 00 00 00

**Comment by eteran** [comment]
Should be fixed in the latest. Thank you so much for you contributions.
