### ISSUE TITLE
Addition of negative offsets should be showed as subtraction of positive ones

### ISSUE THREAD

**Issue by 10110111** [eteran/edb-debugger#155]
After seeing how IDA handles `89 93 9c 01 ff ff`, I though it'd be nice if EDB also did this: instead of

    mov dword ptr [ebx+0xffff019c], edx

I'd like to see

    mov dword ptr [ebx-0xfe64], edx

Apart from this being more natural due to wraparound after such addition, this would be useful when e.g. addressing local variables as `[ebp-VAR]`.

**Comment by eteran** [comment]
Closing as this is a Capstone issue now
