### ISSUE TITLE
FPU registers with exponent values exceeding those of float64 are shown as 0 or inf

### ISSUE THREAD

**Issue by 10110111** [eteran/edb-debugger#159]
Here's an [example FASM code](https://pastebin.mozilla.org/8839973) and [checking code in C++](https://pastebin.mozilla.org/8839974). If running the fasm example, the first `fld` loads approximately `3.25435e-763`, which EDB shows as `0`. The second load is of approximately `-3.46264e+383`, which EDB shows as `-inf`.

Apparently, somewhere in the middle of processing the numbers are converted to double, thus losing representation range.

Running the C++ snippet you can check that the values are actually in the range of `float80`.

What's funny, GDB (at least 7.7.1) has exactly the same issue :)

**Comment by 10110111** [comment]
I'm taking this (dunno how to assign myself here).

**Comment by eteran** [comment]
Awesome, just send a pull request mentioning this bug and I'll close when you're done :+1:

**Comment by eteran** [comment]
I beleive that this was fixed by pull #163
