### ISSUE TITLE
`finit` instruction should be disassembled as `fwait\nfinit`

### ISSUE THREAD

**Issue by 10110111** [eteran/edb-debugger#167]
Due to the way single stepping works, `finit`, being actually a pair of `fwait` and `fninit`, gets split when you single-step the debuggee. I.e. `fwait` is always trapped on single step. Thus it would make more sense to always disassemble `fwait` as a separate instruction, and then what remains as another one.

To compare with other debuggers:

* GDB: disassembles `finit` as a single instruction, thus on si it transforms to `fninit`. But here it doesn't make much of a problem (although it might confuse for a moment, like "there was no `fninit` after a `finit`!"), because its text-based GUI is rarely used, and it doesn't have a notion of "current line in assembly view".

* OllyDbg: this one is half-way there: it does split the instruction into `WAIT` and `FINIT` (sic!). Apparently this is either a typo, or its devs don't consider `FNINIT` a good name, but the name they use, `FINIT`, is misleading.

* EDB: as GDB, it disassembles `finit` as a single instruction. And, as we single step through `finit`, the `fninit` going in the next step scrolls to the top of disassembly view, interfering with the user's work flow.

**Comment by eteran** [comment]
Interesting, such an odd little instruction :-). So it sounds like `9b` should be considered to be the `fwait` instruction by itself and the `db e3` should be `fninit`.

I would like to just double check if `9b` followed by anything else would should decode as something other than `fwait`.

Also, it looks like from the docs that `fsave` needs the same treatment and will result in an `fwait` + `fnsave`.

I'll work on a fix ASAP.

**Comment by 10110111** [comment]
In the Intel's Instruction Set Reference manual only the following instructions start with `9B`: `fclex`, `finit`, `fsave`, `fstcw`, `fstenv`, `fstsw` and `fwait` itself. All these are FPU instructions, and all they are a composition of `fwait` and corresponding `fn*` instruction.

**Comment by 10110111** [comment]
Interestingly, this works as it should in 64 bit version, but doesn't in 32 bit.

**Comment by eteran** [comment]
Well... that's weird. That's actually a "bug" in the disassembly look up tables. But at least it obviates the fix :-)

**Comment by eteran** [comment]
Should be fixed in latest
