### ISSUE TITLE
`68 ff ff ff ff` is `push qword -1`, not `push dword -1`

### ISSUE THREAD

**Issue by 10110111** [eteran/edb-debugger#169]
Compiling an instruction like `push qword -1` in fasm to ELF64, I get its code as `68 ff ff ff ff`. This is correct, and executes as expected, pushing `0xffffffffffffffff` to stack and decreasing `rsp` by 8. But EDB disassembles it as `push 0xffffffff`, which is wrong.

**Comment by eteran** [comment]
Interesting. I'll look into it.

**Comment by eteran** [comment]
**should** be fixed in latest push

**Comment by 10110111** [comment]
It seems to have not been fixed (unless I pulled wrongly. I did `git fetch upstream --recurse-modules` followed by `git submodule update --recursive`, then rebuilt.)

**Comment by eteran** [comment]
please try again, i had to do a minor follow up fix :-)

**Comment by 10110111** [comment]
OK, now seems to work correctly. Thanks.

**Comment by eteran** [comment]
nice, was getting bit by:

    func(op.sdword());

not being the same as

    int32_t n = op.sdword();
    func(n); 

I think perhaps on 64-bit things were getting widened implicitly without the temp. Regardless, all better now :-)

**Comment by 10110111** [comment]
Regarding you commit messages, yes, I've also found it surprising that `static_cast<uint32_t>(static_cast<int8_t>(0x80))` gives me `0xffffff80`. This is explicitly explained e.g. [here](http://en.cppreference.com/w/cpp/language/implicit_cast#Integral_conversions):

> If the destination type is unsigned, the resulting value is the smallest unsigned value equal to the source value modulo 2^n where n is the number of bits used to represent the destination type.
> That is, depending on whether the destination type is wider or narrower, signed integers are sign-extended or truncated and unsigned integers are zero-extended or truncated respectively.
