### ISSUE TITLE
barely readable text with breeze-dark theme

### ISSUE THREAD

**Issue by pcordes** [eteran/edb-debugger#178]
There's lots of dark-blue on dark gray backgrounds, and other dark on dark situations, when using the KDE Breeze-Dark theme.

I assume fixing this would require getting around to the TODO comments in SyntaxHighlighter.cpp:

    void SyntaxHighlighter::create_rules() {

	// TODO: make these rules be implemented in a portable way
	// right now things are very much hard coded

screenshot attached.  (I would normally have edb's window much bigger; shrunk for a smaller image.)

![edb-dark](https://cloud.githubusercontent.com/assets/165377/9028762/a2ac429a-3959-11e5-8957-ec4d48a5acc2.png)

**Comment by eteran** [comment]
I've just added a section to the wiki for [theming] (https://github.com/eteran/edb-debugger/wiki/Theming). See if you are able to make sufficient tweaks to the colors to get what you need. If not, I can certainly add more things which can be changed.

In the future, I plan to make everything universally themable using Qt's CSS like style-sheets. But for now, this is the tool we have :-).

Let me know.

**Comment by eteran** [comment]
BTW, is this on KDE 5 or 4? Colors aside, I really like thw widget theme you've got there. Which one is it?

**Comment by pcordes** [comment]
Thanks for the theming update on the wiki, I'll take a look.

It's the Breeze widget theme, with Breeze-dark colors.  There's a "Breeze" color theme which uses the more traditional dark-on-light scheme.

I'm using KDE5 on Kubuntu 15.04.  (But upstream has bugfixes that aren't in Kubuntu's version, so I can't really recommend just using Kubuntu.   :/  I'm thinking about switching to Arch or Gentoo for my desktop, for rolling-release setup that keeps up with upstream.)

Breeze-dark has huge usability problems with some apps, edb is far from an isolated case.  e.g. in Firefox text boxes on some sites (e.g. facebook), you're entering near-white text on white  background.  Or dark text on a dark bg.  I think this only happened after I tweaked FF to use that theme, instead of clashing horribly.

 Eclipse is also horrible.

Some GTK3 apps look fine with breeze-dark styling, though.

I use my computer in a dim room suitable for watching movies, so I hate having bright-white stuff all over my screen (even though most web pages and PDFs still look that way.)

**Comment by eteran** [comment]
@pcordes , Since it's been a while, I'm going to mark this bug as closed. But please re-open this issue if there are aspects of the UI that don't have enough control to make things usable
