### ISSUE TITLE
Small positive integers are showed with excessive number of insignificant digits

### ISSUE THREAD

**Issue by 10110111** [eteran/edb-debugger#179]
The instruction like `48 83 ec 38` is disassembled as

    sub rsp,0x0000000000000038

. There's is way too many zeros here to be readable. Although it's not wrong per se, it still is unreadable. I'm not sure, but this may have been introduced while fixing #169.

Interestingly, this instruction appears to be unaffected: `48 81 ec 40 03 00 00`, being disassembled as

    sub rsp,0x0340

**Comment by eteran** [comment]
It was certainly introduced by that set of changes. This class of issues is unfortunately proving to be complex.

**Comment by 10110111** [comment]
This seems to have been fixed together with #169.
