### ISSUE TITLE
Unaligned access exception gives a misleading detail

### ISSUE THREAD

**Issue by 10110111** [eteran/edb-debugger#182]
Consider the following code

    sub rsp,512
    and rsp,-16
    fxsave [rsp+1]

It leads to alignment failure. And EDB reports "The address 0x0000000000000000 could not be accessed." This is actually misleading since there was no NULL-pointer dereference. EDB should check operand, and if the memory reference is not zero, then either omit this sentence, or (better) analyze the real reasons per-instruction (in this case address being not aligned at 16-byte boundary).

**Comment by eteran** [comment]
This is similar to bug #26, The main problem is that linux use SEGFAULT for quite a few errors and offers little to no way to differentiate between them. We could add code to iterate through all parameters, also check [ER]IP and if none of those are NULL, then offer a better error message. I'll check it out.

**Comment by 10110111** [comment]
Linux doesn't give actually leave us with no information for SIGSEGV. It does give [something](https://www.mkssoftware.com/docs/man5/siginfo_t.5.asp), although that isn't much. Namely, if the illegal memory access was at unmapped address, we get `si_code==1==SEGV_MAPERR`, while on trying to write to write-protected region it should give (haven't checked yet) `si_code==SEGV_ACCERR`. And on misaligned access as well as privileged instruction (and maybe any others which aren't segmentation faults per se) it appears to give `si_code==128` (at least with my Kubuntu 14.04 64 bit kernel).

**Comment by eteran** [comment]
That is some very useful info! I'll work on integrating that into the code :-)

**Comment by 10110111** [comment]
Just checked, indeed, writing to unwritable area gives me `si_code==2`. So, we have at least three different messages to give at SIGSEGV for different faults (and possibly elaborate on the case with `si_code==128`).

**Comment by 10110111** [comment]
You might find useful my little [test program](https://pastebin.mozilla.org/8841932) which generates several types of exceptions, getting `SIGSEGV`, `SIGILL` and `SIGFPE` and handles these signals, shows their parameters like `si_signo` and `si_code`.

**Comment by eteran** [comment]
I've added code toi differentiate between the different classes of segfaults and made the message (ever so slightly) more accurate. probably still some room for improvement, but at least the message is no longer misleading.
