### ISSUE TITLE
Allow running a new debuggee without special options like `--run`

### ISSUE THREAD

**Issue by 10110111** [eteran/edb-debugger#185]
Could EDB have a possibility to run a new debuggee like `edb path/to/program` instead of current `edb --run path/to/program`? It is quite annoying to make stupid mistakes like `gdb --run progname` or vice-versa, `edb progname` when frequently launching and comparing the two debuggers. Some consistency would be nice.

In other words, could the default action when no `--something` was specified be "run the first argument"?

**Comment by eteran** [comment]
I understand the motivation here. Consistency is good. But I'm not sure I think that gdb's approach is a model that I care for more than edb's. For example, edb's run is more like gdb's `--args` option:

    ./edb --run /bin/ls /etc # run ls passing /etc as the first argument for it
    gdb --args /bin/ls /etc # almost the same, you still need to run
    gdb -ex run --args  /bin/ls /etc # same as edb's --run, you still need to run

Personally, I find gdb's approach a bit more complicated. I don't like that it has a different set of arguments to run the target with args or not.

That being said, gdb currently has the ability to send data to stdin and edb doesn't (yet)
