### ISSUE TITLE
ADCX with LOCK prefix is disassembled as invalid with wrong instruction length

### ISSUE THREAD

**Issue by 10110111** [eteran/edb-debugger#186]
The instruction `F0 66 0F 38 F6 C1`, i.e. `lock\nadcx eax,ecx`, is a decodable instruction, although it generates #UD. But EDB thinks that this instruction is invalid (which is somewhat correct given its behavior), but says it doesn't "own" the last byte.

For comparison, Capstone (testable in a [web-based disassembler based on it](http://www.cenigma.org/)), decodes the instruction fully as `lock adcx eax, ecx`.
The same is for GDB.

So, EDB should at least correctly tell its length, and it'd be best if it decoded it completely as GDB and Capstone do.

**Comment by eteran** [comment]
I've added support for this instruction. But I'm also since I don't know which instruction set added it, i'm sure that there are others in the same family not covered :-/

**Comment by 10110111** [comment]
See [this Intel whitepaper](http://www.intel.com/content/www/us/en/intelligent-systems/intel-technology/ia-large-integer-arithmetic-paper.html). In short, there're three instructions in this set: `MULX`, and in newer CPUs also `ADCX`, `ADOX`.

**Comment by eteran** [comment]
thanks!
