### ISSUE TITLE
Contents of inaccessible memory are showed as 0xffffffff

### ISSUE THREAD

**Issue by 10110111** [eteran/edb-debugger#189]
Consider code like this:

    xor eax,eax
    lea ecx,[eax]
    lea edx,[eax+5]

EDB tries to show what's there at `[eax]` and `[eax+5]`, but the memory is not mapped at those addresses. Instead of correctly handling this situation, it prints bogus data such as

    [eax+5] = [00000005] = 0xffffffff

. It should instead either say something like

    [eax+5] = [00000005] = (invalid memory reference)

or just refrain from showing the corresponding line in analysis view.

**Comment by eteran** [comment]
I could have sworn that it would print something like:

    [eax+5] = [00000005] = ?

But I'll look into it

**Comment by 10110111** [comment]
Some of my recent commits might have broken this then.

**Comment by 10110111** [comment]
OK, checked, at least as of commit 3190eda407237727e81c8c0fe225d8f6b4480f0d the bug is present (tested on 64 bit system), so not from my commits.

**Comment by eteran** [comment]
Fair enough. Looking at the code, in x86_64/ArchProcessor line 520, it attempts to do what I said. But for some reason, process->read_bytes is returning true. I'll have to look into it.

Thanks

**Comment by eteran** [comment]
Actually, that particular line is for a call analysis. I need to find the spot for general dereferencing (which should probably be shared if they are that similar)

**Comment by eteran** [comment]
Yea, line 615 looks more like it, same symptom though

**Comment by eteran** [comment]
should be fixed in latest push

**Comment by eteran** [comment]
However, it does have a side effect of making the widget go blank of refresh while the debuggee is running. Can't say I love that :-/
