### ISSUE TITLE
When debuggee is running, widgets show nothing

### ISSUE THREAD

**Issue by eteran** [eteran/edb-debugger#191]
Previously the behavior was to show the data as all 0xff` bytes. I recently fixed a bug by making the back end properly report when it couldn't read bytes. But as a side effect, now the front end will refresh to showing **nothing** while the traced app is not in a stopped state. I'd like to come up with a better solution.

Perhaps a "micro pause" that is implicit in the API, where if the process is running, it will attempt to pause it, do the read, then unpause it?

Another option is to "lock" the widgets when we are running. Basically force them to not change in display (perhaps we dim them to show no updates are happening) until the traced app is paused again. I think that could be a nice way to handle it

**Comment by 10110111** [comment]
I think micro-pause is a better thing to do, because as the debuggee runs, the user may want to scroll the code and maybe even intervene like setting a breakpoint etc..

**Comment by eteran** [comment]
Yea, I'll look into it. I hope it doesn't get too messy in light of threads (which are already messy to deal with). But I think you're right. I also think that this is what the Windows APIs do implicitly, so some consistency will be nice as well.

**Comment by eteran** [comment]
I believe that this was fixed by one of Ruslan's commits. Closing.

**Comment by 10110111** [comment]
For the record, it's the result of reading `/proc/$PID/mem` instead of doing `PTRACE_PEEKDATA`
