### ISSUE TITLE
Some system calls are shown without arguments

### ISSUE THREAD

**Issue by 10110111** [eteran/edb-debugger#194]
Some system calls, e.g. `sys_exit` in 64 bit code, are showed without arguments, i.e. while in 32 bit code analysis view says `exit(0)`, in 64 bits we can only see `exit()`.

As I've seen in `src/xml/syscalls.xml`, majority of the entries there lack any specification of arguments. Is there any particular reason why not just use `<linux source>/include/linux/syscalls.h` to get the argument lists?

**Comment by eteran** [comment]
Well the XML file is intended to allow it to work, even in cases where for some reason that the syscalls.h file is not present. As for why is it incomplete, just a matter of man-power ...I'd like for it to be complete eventually, it just hasn't been high on the list.

**Comment by 10110111** [comment]
I didn't mean to use `syscalls.h` on each rebuild or like that. I was just wondering whether this incompleteness was intentional or not (e.g. you might have wanted to test each of syscalls before actually putting the corresponding lines in the XML).

**Comment by eteran** [comment]
Yea, probably would be nice to make something that could parse `syscalls.h` and auto-generate the XML.

**Comment by 10110111** [comment]
I think it'd be better to have a general tool to generate things like functions.xml in some generic format for syscalls and procedure calls (although syscall numbers will still have to be placed somewhere there), also supporting things like different calling conventions (e.g. asmlinkage vs x86-64 ABI vs i386 ABI etc.). I'll try to see what I can do for this.
