### ISSUE TITLE
`j[re]?cxz` is always analyzed as "jump taken"

### ISSUE THREAD

**Issue by 10110111** [eteran/edb-debugger#199]
In the following code both `j[re]?cxz` instructions are analyzed as "jump taken", although for both it's not:

        mov ecx,1
        jrcxz doJump1
        jecxz doJump2
        nop
    doJump1:
        nop
    doJump2:

**Comment by eteran** [comment]
Hmm, the code in ArchProcessor::is_jcc_taken looks correct. The only think that I think could be a factor is if the state passed to it somehow doesn't have the correct eflags in it. I'll do some testing

**Comment by 10110111** [comment]
Also note that one of these instructions has a `67` prefix, which seems to not be taken into account in the code.

**Comment by eteran** [comment]
Ah, I see that. I am guessing that the prefix is used as "invert condition". Which would explain why they both get the same result.

**Comment by 10110111** [comment]
No, it's not inversion. It's change of `rcx`->`ecx` in 64 bits and `ecx`->`cx` in 32 bits.

**Comment by eteran** [comment]
Yup, you're right. I misread the code. I'll check it out.

**Comment by eteran** [comment]
I think that it should be fixed in the latest push
