### ISSUE TITLE
ld-2.19.so function names aren't recognized in indirect jumps

### ISSUE THREAD

**Issue by 10110111** [eteran/edb-debugger#201]
Followup to #200: on indirect jump to `_dl_runtime_resolve` EDB just tells the address the jump would go to, but doesn't mention the symbol, although it's known.
OTOH, if the jump is direct, then EDB shows the function as it should, e.g.

    call 0x00007f1fb3823c40 <libc-2.19.so::__fortify_fail>

**Comment by eteran** [comment]
Just to understand correctly, you are saying:

    ; doesn't display correctly
    mov rax, 0x00007f1fb3823c40
    call rax 
----

    ; does display correctly
    call 0x00007f1fb3823c40

Is that correct? If so, should be relatively easy to fix :-)

**Comment by 10110111** [comment]
Hmm, seems not so simple. On another system (32 bit LFS), where I'm now, it shows correctly in both cases. Have to find out why it doesn't work on 64 bit Kubuntu.

**Comment by 10110111** [comment]
OK, I guess I know what happens here. I was wrong that it's due to indirection of the jump. It happens for this `_dl_runtime_resolve` in any case with direct and indirect jumps. On my 64 bit Kubuntu EDB doesn't see this function because `ld-2.19.so` has been stripped. And GDB works because it supports debug info, which it loads from `/usr/lib/debug/`. So EDB should also be able to load separate debuginfo (maybe having its directory set by the user).

**Comment by eteran** [comment]
Ah, support for debug info has been on my personal TODO list for a while. Good call

**Comment by 10110111** [comment]
Now as this is basically duplicate of #249, I'm closing it.
