### ISSUE TITLE
Assemble command doesn't work for anything but yasm and nasm

### ISSUE THREAD

**Issue by 10110111** [eteran/edb-debugger#202]
When I specify some non-yasm and non-nasm (whose names I only could find in EDB sources and nowhere else) in _Assembler Helper Application_ setting of Assembley Plugin, they don't work. Sometimes silently do nothing (when specifying GNU `as`), other times showing an empty exclamation message box (when specifying `fasm`).

EDB should at least warn the user that it doesn't support the assembler chosen, and tell what assemblers are supported.

But best of all would be to give the user a way to specify header to put before the user-supplied instruction to assemble. It could look something like this for `fasm`:

    use%BITNESS
    org %ADDRESS
    %INSTRUCTION

and EDB would replace `%BITNESS` with bitness of current target, `%ADDRESS` with current instruction pointer and `%INSTRUCTION` with the text entered in `DialogAssembler`.

In such case there'd be no need to do any hard-coded translation to the syntax of assembler at hand, as the user is supposed to know syntax of the assembler he choses.

**Comment by eteran** [comment]
So, the assemble command is *attempting* to replicate similar functionality in ollydbg. However, you are right. I also like your suggestions. Ideally, edb would be able to assemble natively and circumvent this issue. But alas, writing an assembler is hard :-P.

I'll work on trying to improve this

**Comment by eteran** [comment]
Also, at the moment, edb trying to normalize the syntax to match what is displayed in the disassembly views. Which is why nasm/yasm are the currently only supported assemblers (They have a very good match for the syntax that edb prefers).

Perhaps this normalization should be re-considered. If we allow an arbitrary assembler, we can just tell the user which one is selected and they should know the syntax of that assembler.

**Comment by 10110111** [comment]
Yeah, telling which is selected is a good idea. And also hinting that the choice can be changed in preferences.

**Comment by eteran** [comment]
Additionally to this. At the moment, the code manually constructs an assembly file to send to assembler. I think there is a superior solution involving file templates. We could have the plugin reference something like an XML file, which would describe the assembler itself and any supporting syntax this is needed in the file (like `ORG` and `BITS` directives). This way it would be trivial for users to add support for any assembler they like with no recompile.

Additionally, I'm thinking that I'll have the current choices "built in" as  resources for smoothness of switching :-).

**Comment by eteran** [comment]
So I've done a commit with puts the file template into an XML file (currently a resource). Which is step 1.

Regarding the manual ASM fixup. The only problem here, which I've torn on, is that the ASM we put in the box won't "just work" if the assembler doesn't have a compatible syntax with the disassembler :-(.

Unless we simply have a built in disassembler, I'm not sure this is avoidable though.

**Comment by eteran** [comment]
The assembler plugin is fairly flexible now. As demonstrated by a recent patch adding fasm support. I think we can consider this closed.
