### ISSUE TITLE
Jump to unmapped address results in EIP being not updated

### ISSUE THREAD

**Issue by 10110111** [eteran/edb-debugger#203]
Consider an instruction: `66 E9 fc ff`. All it does is `EIP&=0xffff` (near jump with `OperandSize==16`). But EDB somehow gets confused by the fact that the new location `EIP` points at is inaccessible, and register view shows old `EIP`.

**Comment by eteran** [comment]
Confirmed. This is an interesting one.

**Comment by eteran** [comment]
So, there is an interesting set of things going on here:

in `Debugger::update_gui()`, the else condition was not being handled, so `update_register_view()` wasn't being called. I fixed that. But now it gets strange.

The state that edb actually gets is not correct!

So I've gotten it to update, but it's not the expected value :-/

**Comment by eteran** [comment]
Additionally, even setting `RIP` manually to something in the `0x0000` - `0xffff` range results in the no change, which is certainly something at a kernel level enforcing it. So I'm not sure how to call this bug... The instruction results in a state different that what's expected regardless.

**Comment by eteran** [comment]
OK, I can confirm that the register correctly update ... when the kernel allows `RIP` to be set the invalid value. Which I think is all we can do. If the kernel rejects a value there's not much we can do about it.

**Comment by 10110111** [comment]
That's strange that the kernel doesn't allow to set such a `RIP` value. In GDB I successfully do `set $pc=0x1234`, and the next `si` leads to `SIGSEGV` with this address.

**Comment by eteran** [comment]
Hnmm, I am making some assumptions here. I'll have to look into this further then if GDB seems to act more intuitively.

**Comment by eteran** [comment]
Seems you are correct:

	# gdb /bin/ls
	(gdb) break main
	Breakpoint 1 at 0x4027f0: file src/ls.c, line 1243.
	(gdb) run
	Starting program: /bin/ls 

	Breakpoint 1, main (argc=1, argv=0x7fffffffdb18) at src/ls.c:1243
	1243    src/ls.c: No such file or directory.
	(gdb) set $pc=0x1234
	(gdb) si

	Program received signal SIGSEGV, Segmentation fault.
	0x0000000000001234 in ?? ()
	(gdb) 

I'll have to look into why EDB behaves differently.

**Comment by 10110111** [comment]
It seems the problem is in PlatformState::set_register(). It doesn't set `rip` to the value specified.

**Comment by eteran** [comment]
Looks like manual setting of RIP is broken :-/

**Comment by 10110111** [comment]
Yeah, I think it's my bug :)

**Comment by 10110111** [comment]
If you don't mind, I'll try to fix this myself, since I introduced it.

**Comment by eteran** [comment]
no problem
