### ISSUE TITLE
Report interrupted syscalls in analysis view

### ISSUE THREAD

**Issue by 10110111** [eteran/edb-debugger#208]
When the debuggee is interrupted in the middle of a syscall (e.g. pressing F11 in EDB while debuggee is in nanosleep (such as `sleep 3600` debuggee interrupted)), it'd be useful to use `ORIG_rAX` value as to show the number of syscall which has been interrupted (and also its arguments, since the kernel preserves the corresponding registers).

**Comment by eteran** [comment]
This would be a great feature, I am very interested in implementing this

**Comment by 10110111** [comment]
Note: interrupted syscall shouldn't be confused with a returned syscall. Both set `orig_eax` to a value different from `-1`, but interrupted syscall has `-(EINTR|ERESTARTSYS)` in `eax`, while successfully returned one doesn't.

**Comment by eteran** [comment]
Right. To be honest, this is in line with some other additions I'd like to make to the "analysis". At the moment it's fairly naiive and only considers the current instruction. Real powerful analysis will come when it is capable of looking forward and backwards a few instructions. Combine that with a simulation of the stack and we can get ollydbg like parameter prediction :-).

**Comment by eteran** [comment]
I believe that this is now implemented thanks to Ruslan!
