### ISSUE TITLE
SYSENTER-powered system calls are not analyzed

### ISSUE THREAD

**Issue by 10110111** [eteran/edb-debugger#209]
While `int 0x80` syscalls are analyzed normally, i586 Linux 2.6.? systems also support `sysenter`-powered ones, which are not analyzed by EDB at all. Here's a test app (use fasm to compile):

````
format ELF executable
segment readable executable
    mov edx, msgLen
    mov ecx, msg
    mov ebx, 1 ; stdout
    mov eax, 4 ; sys_write

    ; sysenter support
    push sysenterRet ; return EIP
    push ecx         ; these three are popped by the point where sysexit lands
    push edx
    push ebp
    mov ebp,esp      ; apparently, esp is written to from ebp before/by sysexit
    sysenter
    int3
sysenterRet:
    nop
    mov eax, 1 ; sys_exit
    mov ebx,183 ; exit code

    ; Why is ebp==esp needed for exit?!
    ; Anyway, this seems to be the only thing needed to satisfy the kernel
    mov ebp,esp
    sysenter
    int3
msg:
    db "Hello with sysenter!",10
msgLen = $-msg
````

**Comment by eteran** [comment]
I've added trivial analysis for `sysenter` (it is currently treated the same as `syscall`). We can do better, but it's a start :-)

**Comment by 10110111** [comment]
OK, this works. Now the first what could be better is that there's a difference from `int 0x80` in that the sixth argument is on the top of stack instead of `ebp`, since `ebp` holds a copy of `esp` (which is used by the kernel to fetch the sixth argument from usermode stack even for syscalls like `sys_exit`, only after that jumping to real syscall handler).
