### ISSUE TITLE
 Installation problem: "fatal error: QHexView: No such file or directory"

### ISSUE THREAD

**Issue by JohnnyAMD** [eteran/edb-debugger#212]
Hi, 

1. System: Ubuntu 14.04, i686
2. Uname -a:
Linux ubuntu 3.16.0-48-generic #64~14.04.1-Ubuntu SMP Thu Aug 20 23:03:49 UTC 2015 i686 i686 i686 GNU/Linux

3. Installed all the prerequisites. 

QHexView was cloned from here: https://github.com/eteran/qhexview 

Did qmake and make. Got the following error: 

"make
cd src/ && make -f Makefile 
make[1]: Entering directory `/home/dragos/Desktop/edb-debugger/src'
g++ -c -pipe -std=c++0x -O2 -Wall -W -D_REENTRANT -DQT_NO_DEBUG -DQT_XMLPATTERNS_LIB -DQT_XML_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtXml -I/usr/include/qt4/QtXmlPatterns -I/usr/include/qt4 -Iwidgets -I../include -I../src/capstone-edb/include -Iqhexview -I../include/os/unix -Icapstone-edb -Iarch/x86-generic -I../include/arch/x86-generic -I.release-shared/moc -I.release-shared/uic -o .release-shared/obj/CommentServer.o CommentServer.cpp
In file included from CommentServer.cpp:19:0:
CommentServer.h:22:20: fatal error: QHexView: No such file or directory
 #include "QHexView"
                    ^
compilation terminated.
"
Got read the README file for couple of times. How do I have to to do make it successfully compiled? 
Do I missed something?

Also, be advised that your official installation steps is not telling where that wicked QHexView has to be placed, compiled or integrated with the main edb-debugger in order to get it properly work. 

Please advise. 

Thank you, 

-J

**Comment by eteran** [comment]
The reason why there aren't any instructions regarding where to put QHexview is because It is not necessary to separately clone that project. As per the README, please clone edb-debugger with the `--recursive` flag and all should be well.

Please let me know if after that you run into any issues.

Thanks,
Evan
