### ISSUE TITLE
compilation error

### ISSUE THREAD

**Issue by hephaestus9** [eteran/edb-debugger#214]
While following the compilation instructions in the readme I first ran into this problem...

>In file included from CommentServer.cpp:19:0:
>CommentServer.h:22:20: fatal error: QHexView: No such file or directory
> #include "QHexView"
>                    ^
>compilation terminated.

So I downloaded the qhexview project and put it in the /src/widgets folder.  The program continued to build, but now I am getting this error ...

>make[1]: *** No rule to make target `qhexview.cpp', needed by `.release-shared/obj/qhexview.o'.  Stop.

**Comment by eteran** [comment]
As mentioned in the README, please clone the repo with the `--recursive` flag
