### ISSUE TITLE
Automatically let the user to assemble next instruction

### ISSUE THREAD

**Issue by 10110111** [eteran/edb-debugger#219]
OllyDbg and x64dbg have a useful feature: when you press "OK" in Assemble dialog, they automatically start this dialog for the next instruction, i.e. with the address right after the one just assembled. I.e. you can simply right assembly code instruction by instruction, as if you entered it into a text editor.

It'd be nice if EDB also had this feature.

**Comment by eteran** [comment]
I like it, shouldn't be too hard to do this.

**Comment by eteran** [comment]
Like the commit message says, it's not quite perfect. The dialog box properly updates to the new address and you will able to use it as expected. However, the highlight line of the CPU doesn't update immediately... Perhaps because the dialog box is modal? I'll have to look into it.

**Comment by eteran** [comment]
I think I am going to consider the CPU highlighting issue a separate bug. Having it visible to the user is a relatively new thing, so I'm sure it has quirks which need to be ironed out.
