### ISSUE TITLE
EDB can't properly detach from debuggee which loops forever without any syscalls

### ISSUE THREAD

**Issue by 10110111** [eteran/edb-debugger#222]
To reproduce:
1. Open a debuggee (`F3`)
2. Change first two bytes to `EB FE` (i.e. `jmp $`)
3. Select Debug->Detach
4. See EDB hang

**Comment by eteran** [comment]
Interesting,perhaps internally it waits for an interruption point to make this happen. I'll look into it.

**Comment by eteran** [comment]
Honestly, this may be a kernel bug. We are sending `SIGSTOP`s, we are doing a `PTRACE_DETACH` and finally we are doing a `waitpid` where we hang in the syscall. I'm not sure that there is anything we could do to not hang. Let me see if I can reduce this down to the simplest example possible and continue to investigate.

**Comment by 10110111** [comment]
Why do we have to `waitpid` after `PTRACE_DETACH`?

**Comment by eteran** [comment]
good question, I'm not 100% sure, but I **think** it's considered "proper" to wait on processes that we've spawned. But perhaps not?

**Comment by eteran** [comment]
So, if we don't wait, edb doesn't hang, but the child process continue to run and spins hard.

**Comment by 10110111** [comment]
I don't think so. In case of `PTRACE_DETACH` we have nothing to wait for, and doing this even leads to  this hang.

**Comment by eteran** [comment]
I think you're right, and now that I think of it.... The process continuing to run and spinning is exactly what should happen! we asked to detach. Patch incoming :-)
