### ISSUE TITLE
Debuggee runs away if EDB crashes

### ISSUE THREAD

**Issue by 10110111** [eteran/edb-debugger#224]
When you debug a malware, you'd expect that it can't escape debugger's control. And if the debugger crashes, debuggee should be killed if it was started by debugger. EDB doesn't do this, even if Close Behavior is Terminate Debuggee. The fix is to use `PTRACE_O_EXITKILL` for such cases.

**Comment by eteran** [comment]
fixed, if edb crashes, then it will kill the debugee

**Comment by 10110111** [comment]
Hmm, it seems to do this unconditionally. Are you sure it's a good idea when Close Behavior isn't Terminate? Or is it hard to query settings at that stage?

**Comment by eteran** [comment]
well, this should only take effect if edb crashes.

If edb exits normally, it manually executes a detach or kill depending on settings. So when it actually closes, it won't be attached to anything anymore :-)
