### ISSUE TITLE
Step over doesn't work after entering signal handler

### ISSUE THREAD

**Issue by 10110111** [eteran/edb-debugger#226]
Steps to reproduce:

1. Setup a signal handler in a program, so that the handler calls some function
2. Cause a segfault/raise a signal to self
3. Launch the program in EDB
4. Run until you get message box about signal
5. Press Shift+F7
6. Try to step over function calls
7. Even if you step through `rt_sigreturn`, getting back to the place of the signal generation, you still can't step over

This seems to be caused by TF somehow getting stuck on entering signal handler.

**Comment by eteran** [comment]
I believe that this is an issue that I reported to the kernel devs in 2010. Or at least related to it since it also involved TF getting stuck.

https://bugzilla.kernel.org/show_bug.cgi?id=16061.

**Comment by 10110111** [comment]
Indeed looks like that's it. Can we work around this in EDB?

**Comment by eteran** [comment]
I don't think there is a practical user space solution. I think for this one, we may just have to say "if this is a problem, consider upgrading to a newer kernel".

Of course, feel free to re-open the bug if you think there is a workable solution. :-)

**Comment by 10110111** [comment]
I think that when EDB sees that the trap trigger was `TF` (there's a bit in `DR6` for this), but EDB didn't request single stepping, it would again call `PTRACE_CONT`. Doing this check on each stop would work around this kernel bug (which apparently hasn't been fixed in any newer kernel).

P.S. Can't seem to reopen this.

**Comment by 10110111** [comment]
OK, I was wrong: when in signal handler, debug registers seem to appear frozen for some reason. So we can't use them to decide what happens.

**Comment by 10110111** [comment]
Well, not completely frozen. Maybe it's just that Hardware Breakpoint plugin doesn't update them when I expected. When I use Run To Line, the debug regs are updated, but for some reason the BS flag is never reset once I do single step (when the bug doesn't trigger).

**Comment by 10110111** [comment]
OK, sorry for the noise above. Now I see in that bug report that the problem has been actually fixed in relatively recent kernels. No need to do anything in EDB then.
