### ISSUE TITLE
RETF isn't highlighted

### ISSUE THREAD

**Issue by 10110111** [eteran/edb-debugger#229]
I've noticed that some instructions like calls, jumps and rets are highlighted with yellow. It seems wrong then that `retf` is not highlighted.
Also, now that we use capstone, a new rule has to be added to highlight `ljmp`, which formerly was a mere `jmp` (or `jmp far`, not sure how edisassm showed it).
Also, capstone seems to differ from edisassm in naming of some conditions like `jne` vs `jnz`. These have to be added to highlighting rules too. In fact, I think all possible combinations should be supported — it'd be useful for the cases if in the future we do context-dependent choices of condition mnemonics, like here:

````
cmp eax,ecx
jne label
````
vs
````
test eax,eax
jnz label
````

**Comment by eteran** [comment]
should be fixed.
