### ISSUE TITLE
No easy way to go to previous/next location

### ISSUE THREAD

**Issue by 10110111** [eteran/edb-debugger#237]
I do understand there're bookmarks, but they are quite unhelpful when you just want to jump to previous/next location. If EDB maintained a stack of recent locations or something like that, it'd be much more useful.
Something like this is implemented in OllyDbg, it has shortcut keys `Num+`/`Num-` for next/previous location.

**Comment by eteran** [comment]
Is there a particular definition for "location"? do we mean previously selected CPU addresses? previously stopped on addresses? Is the list of previous addresses cleared when the debugee is resumed?

**Comment by 10110111** [comment]
If mimicking OllyDbg functionality, here's what it says in its help on Command history:

> OllyDbg keeps track of up to 1000 last commands displayed in Disassembler window. Each time the debugged program stops on breakpoint or exception, or you step next command, or follow address of jump or call, or simply press Return, OllyDbg adds current address together with thread identifier to the command history. If run trace is inactive, you can navigate through the history by pressing buttons '+' and '-'.

**Comment by eteran** [comment]
A recent merge adds navigation of previous locations via plus/minus hotkeys and also updates the selection to the current location on each stop.
