### ISSUE TITLE
AVX & AVX-512 disassembly is not fully highlighted

### ISSUE THREAD

**Issue by 10110111** [eteran/edb-debugger#242]
Syntax highlighter lacks `ymmword ptr` highlighting rule. The same is for `zmmword ptr` and `zmm([0-9]|[12][0-9]|3[01])`.

Test instructions, which Capstone does appear to support:
````
C5 FD 10 35 08 13 00 00
62 81 7C 48 28 FE
62 E1 7C 48 28 91 EA 00 C5 7D
````

**Comment by eteran** [comment]
So I think the regex list is properly updated to support this. Unfortunately, capstone doesn't yet support the examples so I have not tested it as much as I'd like.

Please re-open if they prove to need some tweaking

**Comment by 10110111** [comment]
Hmm, it does. These are exactly the examples I got it to understand. Do you use the latest version?

**Comment by eteran** [comment]
lemme double check :-) gimme a few minutes
