### ISSUE TITLE
Edit bytes in the disassembly view should offer the ability to write more bytes than the current instruction size

### ISSUE THREAD

**Issue by eteran** [eteran/edb-debugger#244]
If we are trying to alter the instruction stream by editing bytes. It is often annoying to deal with adding instructions which are longer than the ones being overwritten. This is because edb assumes you want to set exactly N bytes if the original instruction is size N.

It would be useful to have a check box (similar to the assembler plugin) to allow writing more bytes.

**Comment by eteran** [comment]
Fixed by merge #375 ?

**Comment by 10110111** [comment]
Yes, this can be closed.
