### ISSUE TITLE
Analyzer crashes on assertion failure when a far jump is present in code

### ISSUE THREAD

**Issue by 10110111** [eteran/edb-debugger#245]
`plugins/Analyzer/Analyzer.cpp` has the following code:

````
} else if(is_unconditional_jump(inst)) {

Q_ASSERT(inst.operand_count() == 1);
````

It crashes when reaching a far jump, which Capstone represents as having two arguments: selector and offset.

**Comment by eteran** [comment]
Fair enough, I'll have to fix that up :-)
