### ISSUE TITLE
Add support for separate debuginfos

### ISSUE THREAD

**Issue by 10110111** [eteran/edb-debugger#249]
On some distros, e.g. Ubuntu, most debug symbol files are separate from actual executable library binaries. E.g. for `/lib/i386-linux-gnu/ld-2.15.so` the debug info file is `/usr/lib/debug/lib/i386-linux-gnu/ld-2.15.so`. I.e. the special prefix for such files is `/usr/lib/debug`. It'd be useful if EDB could merge the symbols it extracted from the executable with the symbols it can take from separate debug info file, having debuginfo prefix as a setting.

I've currently tried using `edb --symbols` on that separate debuginfo file and then appending it (skipping first two lines) to the original file EDB auto-generated while debugging. Then, after restarting EDB, it resolved much more symbols, i.e. this idea works, just has to be automated.

**Comment by eteran** [comment]
should be fixed in latest push :-)

**Comment by 10110111** [comment]
Strangely, it doesn't seem to generate any symbol files now — and even doesn't create any directories for symbols specified in the config.

**Comment by 10110111** [comment]
Ah, no, my bad, was looking into wrong directory.
