### ISSUE TITLE
Assemble dialog switches to next existing instruction instead of to after the current one

### ISSUE THREAD

**Issue by 10110111** [eteran/edb-debugger#251]
Suppose we have the code:
````
B8 12 45 9a 73
EB 27
````
When using Assemble dialog and entering e.g. `xchg eax,ecx`, I get the `B8` byte replaced by `91` as expected, the remaining 4 bytes filled with `90`, and the dialog switches to the address of the next instruction, i.e. to `EB 27`. Thus if I enter e.g. `ud2`, this `0F 0B` sequence appears _after_ NOPs. The code then looks awkward and is harder to single-step:
````
xchg eax,ecx
nop
nop
nop
nop
ud2
````

Instead, the dialog should switch to the first byte after the instruction just assembled — in this example, to the first NOP.

**Comment by eteran** [comment]
I believe that this should be fixed now
