### ISSUE TITLE
Process Properties prints bytes/1000 and says it's in KiB

### ISSUE THREAD

**Issue by 10110111** [eteran/edb-debugger#254]
On the Process Properties _Memory_ tab size is printed in decimal kilobytes, but misleads the user by telling it's in `KiB`.
I'd rather prefer it to talk in real binary prefixes (otherwise we end up rounding since memory sizes have page granularity), but even if decimal, they should be correctly displayed.

**Comment by eteran** [comment]
heh, must have been a little confused that day :-P. Fixed.
