### ISSUE TITLE
rFLAGS should give more complete information to the user

### ISSUE THREAD

**Issue by 10110111** [eteran/edb-debugger#257]
Currently `rFLAGS` view doesn't tell the state of at least TF and RF. One has to open Intel documentation and look what some bit stands for when he sees it set. Sometimes it's even worse: some flags are filtered in numeric value field, and the user sees incomplete (in fact, wrong) picture. I seem to remember that when I saw "sticky TF" problem in signal handlers and was trying to understand it, I **had** to use _Dump State_ plugin to see the complete picture in EDB, because _Register View_ didn't show me TF _even in the numeric entry_. I actually discovered that plugin only after seeing TF set in GDB, which finally made sense.

So this request is to avoid filtering information before presenting to the user.

**Comment by eteran** [comment]
All non-system flags should be shown in the broken down view now.
