### ISSUE TITLE
Capstone disassembly quirks with negative values?

### ISSUE THREAD

**Issue by eteran** [eteran/edb-debugger#265]
I just noticed that the byte sequence: `48 b8 00 00 00 00 00 00 00 80` results in the disassembly

    movabs rax, -0x8000000000000000

The negative sign seems incorrect here. And in fact, after this instruction is executed `rax` simply has a value of `0x8000000000000000`

**Comment by aquynh** [comment]
do you want to have the immediate value of MOVABS to be always positive?

**Comment by eteran** [comment]
Well, it's not a matter of always positive or not. It just strikes me as odd to have both the `-` and a hex value that has the sign bit set. Typically it's one or the other:

For example, we'd write either `-2` or `0xFFFFFFFFFFFFFFFE`, but `-0xFFFFFFFFFFFFFFFE` would be confusing. `-` typically means apply 2's compliment, so would `-0xFFFFFFFFFFFFFFFE` actually mean we're loading `2`? Fortunately, Capstone does the right thing with this value and produces `-2`.

However, `-0x8000000000000000` is a bit of a corner case, because it's 2's compliment is itself (i think). So while it looks strange, it also is the correct value. This may not be a "real" issue, just looked weird to me.

Thoughts?

**Comment by 10110111** [comment]
It'd be not `-0xFFFFFFFFFFFFFFFE`, but rather `-0x2`.

**Comment by eteran** [comment]
@10110111, that's kinda my point. `-0xFFFFFFFFFFFFFFFE` doesn't make sense (i mean, it basically mean **positive** `2`, because negating that value results in `0x0000000000000002`).

For similar reasons, `-0x8000000000000000 ` just looks weird

**Comment by aquynh** [comment]
fixed in the "next" branch of Capstone, please confirm. thanks.

**Comment by eteran** [comment]
looks good as far as I can tell
