### ISSUE TITLE
Application arguments are not listed in Application Arguments dialog

### ISSUE THREAD

**Issue by 10110111** [eteran/edb-debugger#266]
If you run edb like this
````
edb --run `which true` --parm
````
, then the debuggee does get its `--parm` argument, but clicking _Options_→_Application Arguments_ gives a dialog with empty list.

**Comment by eteran** [comment]
So this is trivial to implement (already have it in my local code). But here's the question:

so we run:

    edb --run `which true` --parm

This puts `--parm` into the dialog. OK, good. When `true` finishes, should it **still** be in there? There are a few possibilities, with varying levels of complexity:

1. we just leave it in there, it's up to the user to sort out the args if they re-run the app, or run a different one
2. we clear it out, the arguments only applied to that particular run
3. we leave it in there, but warn if they run a different executable than the original one
4. we make the arguments system much more complex and robust. we make it so arguments aren't a flat list, but a set of lists where we remember the set of arguments each unique executable was run with. 

#4 sounds the most useful, but it gets complex, especially in the context of a user running an app, then setting the arguments for the next app, then opens the next app. Should the arguments only be associated with the second? both?

What doOllydbg and/or x64dbg do?

**Comment by 10110111** [comment]
In OllyDbg he arguments seem to be associated with the particular run of the application, and also saved in the list of recently debugged applications. If the user opens a New App window (e.g. pressing F3), the arguments list is empty (this feature is not present in EDB, it can't set parameters at this stage), but if `Ctrl+F2` is pressed even when no app is being debugged, the ones from the recently debugged apps list are used.

**Comment by eteran** [comment]
Right, I plan to improve how arguments are handled and saved, especially related to the recent file list. Gonna try to think about the best way to handle it.
