### ISSUE TITLE
unable to compile

### ISSUE THREAD

**Issue by FaizSayyid** [eteran/edb-debugger#270]
../include/Types.h:115: error: ‘nullptr’ was not declared in this scope

Hi,

Compiling on centos 6 with gcc gcc (GCC) 4.4.7 20120313 (Red Hat 4.4.7-11).

I get this and whole load of other errors. 

I compile with

1)qmake: no errors
2) make - this produces errors

What am i doing wrong?

Thanks

**Comment by 10110111** [comment]
GCC at least version 4.8 is required. Earlier versions don't support C++11 well enough.

**Comment by FaizSayyid** [comment]
thanks
