### ISSUE TITLE
Look into whether cmake would be a better build system

### ISSUE THREAD

**Issue by eteran** [eteran/edb-debugger#274]
Over the years, I've had to jump through many hoops to get `qmake` to work well for this project. While it works just fine at the moment, it may be a good idea to look into switching to `cmake` and see if it results in a more robust and more easily controllable build system.

One thing that I've been running into lately is `qmake` not always detecting when something needs to be rebuilt when dealing with changes in plugins vs. main code :-/

**Comment by 10110111** [comment]
True, was also thinking of this. Great that you've come up with this too :)

**Comment by eteran** [comment]
So I've done some experiments, and there are some difficulties that `cmake` doesn't handle well yet. Specifically, the `AUTOMOC` feature doesn't seem to handle when a header is not in the same sub-tree as the source file that includes it (which edb does for API purposes). So given the basic example of a project with the following layout:

    Example/CMakeLists.txt
    Example/include/Dialog.h
    Example/src/Dialog.cpp
    Example/src/Dialog.ui
    Example/src/main.cpp

The build results in lots of v-table erorrs because it doesn't properly `AUTOMOC` `src/Dialog.cpp`. :-(

**Comment by 10110111** [comment]
You can try to explicitly include e.g. `main.moc` in `main.cpp` etc.. I've followed this approach for the cases with older cmake 3 and Qt5's `Q_GADGET`, which isn't detected until cmake 3.3 IIRC.

**Comment by eteran** [comment]
Hmm, I'll continue to experiment with it, I am certain that there are manual solutions. I was just hoping that it would "just work".

**Comment by eteran** [comment]
We now have an implementation of a cmake based build system. The "make install" target still needs to be added, and I'd also like to figure out the best way to avoid unnecessary rebuilds due to the "detect-proc-mem-writes" test. But it builds and works!
