### ISSUE TITLE
Native binary check is broken

### ISSUE THREAD

**Issue by 10110111** [eteran/edb-debugger#277]
After commit 21591a443ff63f09cde5aa1c09a540f245fbd740, if I run a 64-bit debuggee on 32-bit EDB right after starting EDB or after having just debugged a 32-bit debuggee, I don't get any warnings. But instead, when switching from 64-bit debuggee to 32-bit one I get the warning.
Seems now BinaryInfo is updated too late so that the old one is queried about nativeness of the binary. And at the cold start of EDB, binary_info_ is even null at this point, so that `native()` call isn't even done.

**Comment by eteran** [comment]
Interesting, I'll check it out
