### ISSUE TITLE
"Follow" menu items don't make sense for flags and the like registers

### ISSUE THREAD

**Issue by 10110111** [eteran/edb-debugger#280]
If you right-click rFLAGS or MXCSR, you'll get menu with three "Follow ..." items. It doesn't make sense for these registers, since they are never used to store addresses.

**Comment by eteran** [comment]
agreed, we should be more intelligent about what options we place in what context menus.

**Comment by 10110111** [comment]
It seems just removing `Register::TYPE_COND` from `on_registerList_customContextMenuRequested`'s `if` will solve this particular issue.

**Comment by eteran** [comment]
well that's easy. I will push a fix in just a minute then.
