### ISSUE TITLE
Run until return renders EDB unusable if the app doesn't return

### ISSUE THREAD

**Issue by 10110111** [eteran/edb-debugger#281]
Consider this code:

```
format ELF executable
segment readable executable
entry $
e:  nop
    jmp e
    retn
```

Running it via `F9` and stopping via `F11` works at first. But If you run it via `Ctrl+F9`, and then try to interrupt the app via `F11`, you'll see that it fails to get interrupted, and in fact you have to kill it to have any chance to debug after this.

**Comment by eteran** [comment]
This may be a kind of race condition, because the debugee is constantly being started and stopped while we test to see if it reached the ret yet. Currently, if we hit stop, there is a good chance that it isn't actually in the run state or similar.

I will look into the best way to fix this.
