### ISSUE TITLE
Incompatible with Qt5 while compiling after newly commit 

### ISSUE THREAD

**Issue by lxj616** [eteran/edb-debugger#282]
Recently Got ERROR like this (xubuntu new installation according to wiki ubuntu compile wiki)

arch/x86-generic/DialogEditFPU.cpp: In member function ‘void DialogEditFPU::onHexEdited(const QString&)’:
arch/x86-generic/DialogEditFPU.cpp:81:52: error: ‘class QString’ has no member named ‘toAscii’
  const auto byteArray=QByteArray::fromHex(readable.toAscii());

-------------------------------------------------------

git checkout eb102f31ddbd6cff2c9a90163afa3cf1ebef7615

Everything works like a charm 

-------------------------------------------------------

 So I guess some commits used .toAscii() which is deprecated in QT5 ,Please check

**Comment by 10110111** [comment]
Hmm, I guess this can be changed to use `toLatin1()` then...

**Comment by eteran** [comment]
Right, that is the correct fix.
