### ISSUE TITLE
EDB doesn't stop debuggee if it constantly creates & destroys threads

### ISSUE THREAD

**Issue by 10110111** [eteran/edb-debugger#288]
Consider this test C++ program:

```
#include <thread>

void func(unsigned i)
{
    static volatile unsigned x;
    x=i;
}

int main()
{
    for(unsigned i=1;;++i)
    {
        std::thread thr(func,i);
        thr.join();
    }
}
```

If you launch it in EDB, then press F9, F9 so that it runs, then after pressing F11 it'll get stuck in `t` mode, while EDB will think it's running. Pressing F11 at this stage doesn't enable EDB to continue usefully debugging it (although you can change registers and view/edit memory, you can't continue execution), and the only way to proceed is to kill the debuggee.
Detaching at this stage also doesn't fully detach, because I can't attach to the process with GDB after this, I get this from GDB (many times, as if for each thread or whatever):

> warning: Cannot attach to lwp 31555: Operation not permitted (1), process 31555 is already traced by process 31523

**Comment by eteran** [comment]
This one is tough. Debugging threads with `ptrace` is particularly hard to do correctly, but I will look into it.

Thanks
