### ISSUE TITLE
Order of symbol loading, attaching and searching for `main` is messed up

### ISSUE THREAD

**Issue by 10110111** [eteran/edb-debugger#293]
Relevant stderr output:
````
No symbol path specified. Please set it in the preferences to enable symbols. 
No main symbol found, calculated it to be  "0x080483d0"  using heuristic 
loading symbols: "/tmp/edb//test.map"
````
I.e. first it tries to load symbol file from unset location, then searches for `main` (and fails of course), and only then (after attaching is complete) sets the symbol path and loads the symbol file.

**Comment by eteran** [comment]
Hmm, should be an easy fix. I'll look into it
