### ISSUE TITLE
Let the user use arrow keys to move selection in disassembly view

### ISSUE THREAD

**Issue by 10110111** [eteran/edb-debugger#303]
Debuggers such as OllyDbg and Borland Turbo Debugger allow to use arrow keys to move selection in disassembly view. EDB instead just scrolls the view when you press Up/Down. It'd be more intuitive if EDB behaved more like the above mentioned debuggers.
This will allow to more easily navigate disassembly, and as a bonus, we'll still have (well, at least should have) scrolling when the selection reaches the border of the disassembly view. This would (should!) feel as natural as does navigation of usual QTreeView.

**Comment by eteran** [comment]
Agreed, just need to add a little code to make it auto-scroll when the selection goes beyond the edge of the view.

**Comment by AaronOpfer** [comment]
I think this works now.

**Comment by 10110111** [comment]
Works indeed.
