### ISSUE TITLE
PTRACE_KILL is deprecated

### ISSUE THREAD

**Issue by 10110111** [eteran/edb-debugger#307]
`ptrace(2)` says:

> This  operation  is  deprecated; do not use it!  Instead, send a `SIGKILL` directly using kill(2) or tgkill(2).  The problem with `PTRACE_KILL` is that it requires the tracee to be in signal-delivery-stop, otherwise it may not work (i.e., may complete successfully but won't kill the tracee).  By contrast, sending a `SIGKILL` directly has no such limitation.

But I see the following in `DebuggerCore.cpp`:
````
		ptrace(PTRACE_KILL, pid(), 0, 0);

		// TODO: do i need to actually do this wait?
		native::waitpid(pid(), 0, __WALL);
````

I'm not sure whether this is on purpose, but it seems EDB should just do `kill(pid(),SIGKILL)` instead.

**Comment by eteran** [comment]
fair enough.

**Comment by eteran** [comment]
Fixed (my first commit was wrong, but my subsequent one should be correct)
