### ISSUE TITLE
Changed registers stop being highlighted after any register is double-clicked

### ISSUE THREAD

**Issue by 10110111** [eteran/edb-debugger#308]
Apparently, previous state is somehow reset to equal current whenever a register is double-clicked. This way, if you edit a register, only it will be highlighted, while all the others will become black.

**Comment by eteran** [comment]
OK, definitely worth fixing. Ideally we should do like OllyDbg and have a notion of the complete unaltered state and compare to that.

This way, if you alter a reg, then change it back, it switches back to the starting color.

**Comment by 10110111** [comment]
This has been fixed.
