### ISSUE TITLE
IPlugin::save_state is never called

### ISSUE THREAD

**Issue by 10110111** [eteran/edb-debugger#326]
I've just to put my state saving code there to discover that it's never called. Grepping the code gave zero mentions it.

**Comment by eteran** [comment]
probably about time that I implement session files :-)

**Comment by eteran** [comment]
@10110111, just a heads up that I am considering changing the plugin state API. At the moment, it is based on a `QByteArray`, but I think it may be better to use `QVariantMap`. This will make it simpler to store the results in human readable formats if desired.

Any objections?

**Comment by 10110111** [comment]
This is a good thing I think. And I'm currently not using state API since it doesn't work, so it shouldn't conflict if you change it.
