### ISSUE TITLE
Could not open

### ISSUE THREAD

**Issue by martin-gametest** [eteran/edb-debugger#329]
"Failed to open and attach to process, please check privileges and try again."
edb version: 0.9.20
Linux kali 4.0.0-kali1-amd64 #1 SMP Debian 4.0.4-1+kali2 (2015-06-03) x86_64 GNU/Linux

"readelf -all" for both of them attached in txt.

I have two binaries i would like to debug, they are client and server. I am not able to open nether of them. If it helps, Iam willing to upload them for examination, but i would prefer not to upload them for everybody if possible.

Thanks.
[client.txt](https://github.com/eteran/edb-debugger/files/87570/client.txt)
[server.txt](https://github.com/eteran/edb-debugger/files/87571/server.txt)

**Comment by 10110111** [comment]
How do you run it? Something like `edb --run /path/to/binary`?

**Comment by martin-gametest** [comment]
File - Open  /root/Desktop/*

**Comment by 10110111** [comment]
Are you running EDB as root? Do the binaries have execute flags on?

**Comment by martin-gametest** [comment]
Yes i do, command: sudo edb --run server
Produces same error, but graphic of GUI is slightly different: Failed to open and attach to process, please check priviliges and try again.
No, X flag is not on.

**Comment by 10110111** [comment]
Please try specifying full path to EDB. And to run, a binary must have Execute bit on, otherwise you'll not be able to start it even without debugger.

**Comment by martin-gametest** [comment]
sudo /usr/bin/edb --run /root/Desktop/server  was succesfull

**Comment by eteran** [comment]
great, so it seems that it was just a permissions issue. Remember, in order to debug something, it must always be marked as executable.

**Comment by martin-gametest** [comment]
No its not. I have 2 elf files, both now with permission 777, one of them can be opened without a problem, the second one still cant be opened any way. (from gui / commad line / command line with full paths to edb and oppening file)

**Comment by 10110111** [comment]
It looks different because your normal user and root have different themes chosen in Qt config.

**Comment by martin-gametest** [comment]
Iam login as a root the whole time, it doesnt matter?
What can i do about that file I cant open?

**Comment by 10110111** [comment]
Can it run without debugger? Can GDB start it — like `gdb /path/to/file -ex r`?

**Comment by martin-gametest** [comment]
# /usr/bin/gdb /root/client -ex r
GNU gdb (Debian 7.7.1+dfsg-5) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /root/client...(no debugging symbols found)...done.
Starting program: /root/client
/bin/bash: /root/client: No such file or directory
During startup program exited with code 127.
(gdb)

**Comment by 10110111** [comment]
OK, I think I know what happens. You don't have some libraries found. What does `ldd /root/client` say?

**Comment by martin-gametest** [comment]
# ldd /root/client
        not a dynamic executable

**Comment by martin-gametest** [comment]
Esteran: "So to answer why Qt looks different under sudo. It is because it is running as root, which being a different user, is not respecting your user's Qt theme setting."
I dont understand what is the difference beeing login as root and use sudo (while still logged as root.) Is still the same, right? root == root, there is no root1 or root2.. ? If I am wrong, can you point me where should i study it? Thanks.

**Comment by 10110111** [comment]
> not a dynamic executable

That's quite strange. Could you attach a file resulting from the following command (assuming it's safe to actually let the debuggee run):

````
strace -f gdb -q -n -e /root/client -ex r -ex q &> /tmp/gdb.log
````

**Comment by martin-gametest** [comment]
strace -f gdb -q -n -e /root/client -ex r -ex q &> /tmp/gdb.log
[gdb.txt](https://github.com/eteran/edb-debugger/files/91642/gdb.txt)

**Comment by 10110111** [comment]
````
[pid  2245] execve("/root/client", ["/root/client"], [/* 19 vars */]) = -1 ENOENT (No such file or directory)
[pid  2245] stat("/root/client", {st_mode=S_IFREG|0777, st_size=2617100, ...}) = 0
[pid  2245] stat("/root/client", {st_mode=S_IFREG|0777, st_size=2617100, ...}) = 0
[pid  2245] stat("/root/client", {st_mode=S_IFREG|0777, st_size=2617100, ...}) = 0
[pid  2245] geteuid()                   = 0
[pid  2245] getegid()                   = 0
[pid  2245] getuid()                    = 0
[pid  2245] getgid()                    = 0
[pid  2245] access("/root/client", X_OK) = 0
[pid  2245] stat("/root/client", {st_mode=S_IFREG|0777, st_size=2617100, ...}) = 0
[pid  2245] geteuid()                   = 0
[pid  2245] getegid()                   = 0
[pid  2245] getuid()                    = 0
[pid  2245] getgid()                    = 0
[pid  2245] access("/root/client", R_OK) = 0
[pid  2245] open("/root/client", O_RDONLY) = 3
[pid  2245] read(3, "\177ELF\1\1\1\0\0\0\0\0\0\0\0\0\2\0\3\0\1\0\0\0\300\375\4\0104\0\0\0"..., 80) = 80
[pid  2245] close(3)                    = 0
[pid  2245] open("/usr/share/locale/en_US.UTF-8/LC_MESSAGES/libc.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
[pid  2245] open("/usr/share/locale/en_US.utf8/LC_MESSAGES/libc.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
[pid  2245] open("/usr/share/locale/en_US/LC_MESSAGES/libc.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
[pid  2245] open("/usr/share/locale/en.UTF-8/LC_MESSAGES/libc.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
[pid  2245] open("/usr/share/locale/en.utf8/LC_MESSAGES/libc.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
[pid  2245] open("/usr/share/locale/en/LC_MESSAGES/libc.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
[pid  2245] write(2, "/bin/bash: /root/client: No such"..., 51/bin/bash: /root/client: No such file or directory
) = 51
````

The above should mean that the app is unable to run even if launched just as `/root/client`, without debugger? Is it true? If not, it'be interesting to look at the file itself...

**Comment by martin-gametest** [comment]
/root/client
bash: /root/client: No such file or directory

Can I send you the file privately, so it would not be exposed to everyone?

**Comment by 10110111** [comment]
Yes, `b7.10110111` at gmail.com

**Comment by 10110111** [comment]
OK, first: the file can't be opened not only by EDB. It can't be _run_ by any other debugger, and even by the kernel itself. The reason is just that you don't have the program interpreter `/lib/ld-linux.so.2`. Don't know what package provides it on your distro, in (K)Ubuntu it's `libc6:i386`. Another way to run this client is on a 32-bit OS.

**Comment by martin-gametest** [comment]
Thanks, i will try it under 32bit Kali.
Client was originaly running under Gentoo.
If i get the interpreter, will it be possible to load elf into EDB??

**Comment by 10110111** [comment]
Yes, I think it should be.

**Comment by eteran** [comment]
@martin-gametest, when you get a chance, let us know how it goes so we know if we can close this issue. Thanks.

**Comment by martin-gametest** [comment]
It seems to be working. Iam able to open client in EDB on Kali-Linux-2.0.0-vm-i686  and server in EDB on Kali-Linux-2.0.0-vm-amd64.
So thanks for help.
(I will also try the new version of EDB from Git, but have to learn using Git first.)
