### ISSUE TITLE
Disassembly is unreadable when color scheme is dark

### ISSUE THREAD

**Issue by 10110111** [eteran/edb-debugger#331]
See the screenshot. Color scheme is default KDE's _Obsidian Coast_. I'd say in fact that the blue text in `QHexView`s is also unreadable. It should be taken either from the system (Qt/KDE) (preferred), or set in EDB settings.
![6](https://cloud.githubusercontent.com/assets/6376882/12296351/26cb7c8c-ba18-11e5-96ee-6a63375d7b76.png)

**Comment by eteran** [comment]
Can you try the dark theme at the bottom of the theming guide and let me know if it works well?

https://github.com/eteran/edb-debugger/wiki/Theming

**Comment by 10110111** [comment]
Well, it works better than default with dark themes. I still find the blue unreadable though, see:

![screenshot - 01142016 - 08 35 53 am](https://cloud.githubusercontent.com/assets/6376882/12316636/056ca070-ba9a-11e5-8a38-1c41836019c0.png)

**Comment by 10110111** [comment]
Closing this in favor of the duplicate: #436.
