### ISSUE TITLE
edb-debugger for debian

### ISSUE THREAD

**Issue by shengdade** [eteran/edb-debugger#334]
Hi,

you mentioned that <i>"thanks to the work of Fernando Mercês from http://mentebinaria.com.br/, edb now has .deb files for users of Debian based distributions."<i>

So where can I download the <b>.deb</b> files in order to install edb-debugger to my debian system?

**Comment by eteran** [comment]
It has been a while since the .deb files were updated. At the moment, my recommendation is to build from source and do a `make install`

**Comment by shengdade** [comment]
Thanks for your reply. I am quite a novice on this. Could you tell me how to build it from source? and then <b>make install<b>? Thanks.

**Comment by eteran** [comment]
Sure thing. To install in `/usr/local`, do the following:

    # first clone the repo
    git clone --recursive git@github.com:eteran/edb-debugger.git

    # enter the repo's directory
    $ cd edb-debugger

    # build edb
    $ mkdir build
    $ cd build
    $ cmake -DCMAKE_INSTALL_PREFIX=/usr/local/ ..
    $ make
    $ sudo make install
    
    # then you can run it
    $ edb

For more information, you can check the wiki. Here's some useful links:

general compiling information
https://github.com/eteran/edb-debugger/wiki/Compiling

some ubuntu specific instructions for getting the dependencies installed:
https://github.com/eteran/edb-debugger/wiki/Compiling-(Ubuntu)
