### ISSUE TITLE
Data dump shows addresses in wrong format when new tab is opened

### ISSUE THREAD

**Issue by 10110111** [eteran/edb-debugger#336]
To reproduce, start a 64-bit debuggee (I tested with 32-bit EDB), press Ctrl+M, double-click on `[vdso]` and see address show as something like `311f:f000` instead of `00007fff311ff000` (I have colons disabled in options, and note the length which is also wrong).
In fact, it reproduces also with 32-bit debuggee on 32-bit EDB, showing colons when there shouldn't be any.

**Comment by eteran** [comment]
right, when we create a new tab, we need to apply the users display settings to it. should be an easy fix.

**Comment by eteran** [comment]
hmm, it seems that in `create_data_tab`, we are trying to apply the settings.. There may be more to this.
