### ISSUE TITLE
Attach dialog doesn't allow to filter by PID

### ISSUE THREAD

**Issue by 10110111** [eteran/edb-debugger#338]
E.g. I know the PID, I'd just type it in, but it appears this filter only works for names, which is useless in this case.

**Comment by eteran** [comment]
So, the mechanism that we are using `QSortFilterProxyModel` allows filtering on a single column. So we'll need a more custom solution to get what you're looking for.

There is however a workaround. If you click on the PID column of any of the entries in the attach dialog. You can then start typing the PID you want, and it should jump to the first match. It's not perfect, but it's what I've been doing by reflex for quite a while now without even thinking.

**Comment by 10110111** [comment]
The workaround doesn't seem to work. I've even clicked the target row's PID column, but typing the PID doesn't leave that row in the list.

**Comment by eteran** [comment]
interesting, it skips around for me. Either way, I'll look into a better solution.

**Comment by eteran** [comment]
Latest commit changes the behavior. If the filter is purely numeric, it will filter on PID, if it is not, then it will filter on name instead.
