### ISSUE TITLE
Show long operations like loading many symbol files in status bar

### ISSUE THREAD

**Issue by 10110111** [eteran/edb-debugger#342]
I'd like to have EDB use its status bar more extensively. Namely, it'd be useful to see that it actually loads some symbol files or auto-generates them or does similar things, not just hangs without reason. This is especially needed when EDB is started from GUI, so that its debug prints to console are not easily available.

Do you think it'd be a good idea to e.g. provide a global function like `edb::v1::set_status_text()` (and `clear_status_text()` for finished operations) or something like that? This would also be useful to show status like `SIGFPE: division by zero` or `SIGSEGV: address 0xdeadbeef is not mapped`.

**Comment by 10110111** [comment]
Ah, OK, I've found there already exists `edb::v1::set_status()`. The only thing looks not quite nice is that if the operation takes longer than 2 seconds, it'll clear...

**Comment by eteran** [comment]
We can make the timeout a parameter :-)

**Comment by eteran** [comment]
Also, this API isn't really used by anything yet, so we can feel free to alter it without fear of breaking anything.

**Comment by 10110111** [comment]
OK, I think I'll try and make a pull request. I've already done a commit for symbols: 425112c3a23b2b5e862c023c431b05bfac5586e9, it seems to look nice enough.
