### ISSUE TITLE
Threads dialog doesn't update on such events as stepping

### ISSUE THREAD

**Issue by 10110111** [eteran/edb-debugger#346]
To reproduce: launch a threaded program, open Threads dialog, then try stepping in one of the threads. See the dialog remain with the same information in "Instruction Pointer" column. Now move the mouse cursor over that list view, and the information updates.

**Comment by eteran** [comment]
Agreed, there should be some sort of event that just about any dialog/widget can hook to notify it of potential state changes and update appropriately.
