### ISSUE TITLE
Session directory isn't set, but EDB leaves *.edb files in my home

### ISSUE THREAD

**Issue by 10110111** [eteran/edb-debugger#349]
My "Session Directory" field in options is empty, but once in a while after using EDB I notice that my home directory is littered with `*.edb` files. EDB shouldn't save sessions if the directory isn't set.

**Comment by 10110111** [comment]
Ah, it's not even home, it's in every directory from which I started EDB!

**Comment by eteran** [comment]
ok, you feel that if there is no session directory, the preferred behavior is to not save/restore session? that's easy enough.

**Comment by 10110111** [comment]
Yes, I think it'd be better than leaving lots of unexpected files in all sorts of places.

**Comment by eteran** [comment]
Fixed

**Comment by 10110111** [comment]
`to enable symbols`?.. What does it mean? Will EDB refuse to load symbols if session directory not set?

**Comment by eteran** [comment]
oops, C&P bug :-P

**Comment by eteran** [comment]
should be better now :-)
