### ISSUE TITLE
Investigate using signalfd

### ISSUE THREAD

**Issue by eteran** [eteran/edb-debugger#355]
The DebuggerCore uses a bit of trickery to get the sub-process signals. If we can use `signalfd`, then things might be a lot simpler. I am not 100% sure what kernel version it was introduced at though.

**Comment by eteran** [comment]
Looks like it was introduced in 2.6.22. That may be long ago enough that we can use it unconditionally. But I'll have to see what out current minimum requirements are

**Comment by 10110111** [comment]
This is much long ago. I've started my Linux experience in 2008 with 2.6.22.5.

**Comment by eteran** [comment]
Yea, the other option after some investigation  is `sigwaitinfo`/`sigtimedwait` as well. I think all of these are cira 2007.
