### ISSUE TITLE
Assertion failure in some cases when holding F8 to step over multiple instructions

### ISSUE THREAD

**Issue by 10110111** [eteran/edb-debugger#359]
Often when debugging a particular app I get EDB abort with the following error:

    ASSERT: "waited_threads_.contains(tid)" in file /home/ruslan/src/edb-debugger/plugins/DebuggerCore/unix/linux/DebuggerCore.cpp, line 229

This happens when the `tid` has been removed from the container in `ptrace_step()`, but hasn't been re-added there in `ptrace_continue` for some reason. My guess is that this may be related to the fact that I hold F8 and EDB's frequency of response is less than my keyboard autorepeat rate, so the action might have been added to the Qt message queue when EDB no longer expects it to be issuable.

**Comment by eteran** [comment]
Yea, i have encountered this before (though not reliably). I am *guessing* that since the GUI thread and thread that handles debug events are different that there is some kind of race condition involving updating the container. Perhaps simply adding a lock to the `waited_threads_` object would fix this.

**Comment by 10110111** [comment]
Now the behavior appears to have changed: repeated _Step Over_ action now sometimes appears to step _in_ for some reason. I guess this happens in the cases when previously we'd get assertion failure.

**Comment by 10110111** [comment]
In fact, I've made up some code which allows to reproduce the problem (fasm):
````
format ELF executable
segment readable executable
entry $
lp1:
repeat 10
    call loc1
end repeat
    jmp lp1
loc1:
    mov ecx,1411235
lp2:
    loop lp2
    ret
````

Run it in EDB and just press F8. Eventually you'll end up stuck at the `loop` instruction (where you shouldn't end up normally), and no stepping will be possible at this point.

**Comment by 10110111** [comment]
This appears to not reproduce after 656c3d2360eb69e84cb458a20d47063da87dfc2d. But I'm not sure whether the problem is now hidden or `processEvents` really mustn't be called at those times.

**Comment by eteran** [comment]
Hmm, perhaps `processEvents` can cause an implicit second thread? If that is the source of the issue, then using a mutex around the thread tracking structure should resolve it in a more complete sense.

**Comment by 10110111** [comment]
I think it's not like an implicit thread — maybe more like a reentrance of non-reentrant EDB functions.

**Comment by eteran** [comment]
Since that patch seems to have made this bug no longer relevant, let's close this, but keep this in mind if a similar issue crops up in the future.
