### ISSUE TITLE
Update screenshot

### ISSUE THREAD

**Issue by 10110111** [eteran/edb-debugger#364]
Current screenshot on the front page is outdated. I suggest something like this (showing some of newly-added features: register view, demangling, syntax tweaking):

![screenshot - 120416 - 09 07 01](https://cloud.githubusercontent.com/assets/6376882/14451222/f5c4fb7e-008d-11e6-9ad1-67ede13c7477.png)

**Comment by eteran** [comment]
Good call, will do soon :-)

**Comment by eteran** [comment]
Done, thanks!
