### ISSUE TITLE
Double clicking in Data Dump sometimes chooses unexpected byte

### ISSUE THREAD

**Issue by 10110111** [eteran/edb-debugger#370]
Currently selection by double click seems to choose the byte to the right of the cursor position if we click on the space between the bytes. It'd be more user-friendly to choose nearest byte instead.
To reproduce, just click e.g. one pixel to the right of a byte — the next byte will be chosen instead.

**Comment by eteran** [comment]
I agree, it should round up or down based on how far into the white space they are to be ideal.
