### ISSUE TITLE
Allow selection of bytes by single click in hex views

### ISSUE THREAD

**Issue by 10110111** [eteran/edb-debugger#371]
Currently the only thing single click does is unselecting. It seems it'd be more useful if single click chose the byte under cursor, and if there's none (e.g. a space), only then unselected.
Otherwise it's quite annoying when one clicks Ctrl+E and gets a useless empty dialog, which doesn't even allow to enter anything.

**Comment by 10110111** [comment]
I suggest something like the following:
````
diff --git a/qhexview.cpp b/qhexview.cpp
index dd14f57..b9f9f97 100644
--- a/qhexview.cpp
+++ b/qhexview.cpp
@@ -713,7 +713,8 @@ void QHexView::mousePressEvent(QMouseEvent *event) {
         }
 
         if(offset < dataSize()) {
-            selection_start_ = selection_end_ = byte_offset;
+            selection_start_ = byte_offset;
+            selection_end_ = selection_start_+word_width_;
         } else {
             selection_start_ = selection_end_ = -1;
         }
````

**Comment by eteran** [comment]
Hmm, not that I'm against such a patch. But do we know how things like OllyDbg/x64Dbg behave regarding this? Just curious if we'd be changing expected behavior in any significant ways.

**Comment by 10110111** [comment]
At least OllyDbg allows you click-to-select in its data dump.

**Comment by 10110111** [comment]
And in stack view OllyDbg allows selection of the whole line by single-clicking it (effectively the same as selection of a word in EDB).

**Comment by eteran** [comment]
Will be fixed once I update the version of QHexview that edb uses.
