### ISSUE TITLE
No values for XMM registers in "register view". (?? ?? ?? ?? ?? ??)

### ISSUE THREAD

**Issue by JackArchie** [eteran/edb-debugger#372]
No values for XMM registers in "register view". (?? ?? ?? ?? ?? ??) (see jpeg attachment)

My system : Debian 8.4 as VirtualBox 5 guest.

My installation plan for edb-debugger:
sudo apt-get install cmake
sudo apt-get install libboost-dev
sudo apt-get install libqt5xmlpatterns5-dev
sudo apt-get install qtbase5-dev
sudo apt-get install qt5-default
sudo apt-get install libcapstone-dev 
sudo apt-get install git
sudo apt-get install pkg-config
sudo apt-get install graphviz
sudo apt-get install graphviz-dev libgvc6 
cd ~/INSTALL
git clone --recursive https://github.com/aquynh/capstone.git
cd capstone
./make.sh
sudo ./make.sh install
cd ~/INSTALL
git clone --recursive https://github.com/eteran/edb-debugger.git
cd edb-debugger
mkdir build
cd build
cmake -DCMAKE_INSTALL_PREFIX=/usr/local/ ..
make
sudo make install   

But on "real computer" with Arch Linux always is ok.

I also tried Ubuntu, Ubuntu Mate, Arch Linux as guest systems on VirtualBox and VMWare. Same issue.

![vmsseregbug](https://cloud.githubusercontent.com/assets/18646116/14769053/9aa2e95c-0a58-11e6-8fee-8c1c651fe6d9.jpg)

**Comment by 10110111** [comment]
Oh, that's interesting. In fact, FPU/MMX registers also look messed up. What settings differ from defaults in your VirtualBox?
Also, the title bar looks very convincingly like a Windows' one. Is there something unusual in your setup?

**Comment by JackArchie** [comment]
"title bar" is "WinMe" window border in Mate Customize theme.

VMWare has default settings.

VirtualBox settings:
------------------------

System page:
-- Motherboard ----
Chipset ICH9
Checked:
Enable i/o APIC
Hardware clock in UTC Time
-- CPU ---------------
Processors=2
Checked:
Enable PAE/NX
-- Acceleration -----
Paravirtualization Interface: Default
Checked:
Enable VT-x/AMD-V
Enable Nested Paging

Display page:
Checked:
Enable 3D Acceleration

**Comment by 10110111** [comment]
What's your host CPU?

**Comment by JackArchie** [comment]
Host CPU for last test is "Intel Celeron CPU G1620 2.7GHz".
But previously I saw same issues when my host CPU was Intel Core i5-4440 3.1 GHz

**Comment by 10110111** [comment]
With VirtualBox 5 and Debian 8.4 and your instructions to install capstone+edb I've failed to reproduce the issue.
What does EDB print in the terminal you launch it from?

**Comment by JackArchie** [comment]
EDB print in the terminal:
![edboutput](https://cloud.githubusercontent.com/assets/18646116/14769954/37976800-0a6d-11e6-916b-38c2e0abe249.jpg)

**Comment by JackArchie** [comment]
My Host system is Windows 7. May be this is the problem.

**Comment by 10110111** [comment]
Oh. Could you apply this patch to EDB and show the output again?
````
diff --git a/plugins/DebuggerCore/unix/linux/PlatformState.cpp b/plugins/DebuggerCore/unix/linux/PlatformState.cpp
index b5cbd8a..d71fed8 100644
--- a/plugins/DebuggerCore/unix/linux/PlatformState.cpp
+++ b/plugins/DebuggerCore/unix/linux/PlatformState.cpp
@@ -365,7 +365,7 @@ void PlatformState::fillFrom(const PrStatus_X86_64& regs)
 void PlatformState::fillFrom(const X86XState& regs, std::size_t sizeFromKernel) {
 	if(sizeFromKernel<X86XState::AVX_SIZE) {
 		// Shouldn't ever happen. If AVX isn't supported, the ptrace call will fail.
-		qDebug() << "Size of X86_XSTATE returned from the kernel appears less than expected";
+		qDebug() << "Size of X86_XSTATE returned from the kernel appears less than expected: " << sizeFromKernel;
 		return;
 	}
 ````
I don't think Windows 7 could be the reason.

**Comment by JackArchie** [comment]
Sorry, I am newbie.
I put patch text in file patch01.patch. I put this file in "edb-debugger" folder that git had made.
Then
git apply patch01.patch
and git say
fatal: corrupt patch at line 12
What I do wrong?

**Comment by JackArchie** [comment]
I'm tired of fighting with git.
So I just replace line
qDebug() << "Size of X86_XSTATE returned from the kernel appears less than expected";
with line
qDebug() << "Size of X86_XSTATE returned from the kernel appears less than expected: " << sizeFromKernel;
in file edb-debugger/plugins/DebuggerCore/unix/linux/PlatformState.cpp
Then
cd build
cmake -DCMAKE_INSTALL_PREFIX=/usr/local/ ..
make
./edb

edb-debugger say
...
Size of X86_XSTATE returned from the kernel appears less than expected:  576

![edboutpu2](https://cloud.githubusercontent.com/assets/18646116/14770476/2382cfd6-0a7b-11e6-980a-1d264cbccfa2.jpg)

**Comment by 10110111** [comment]
Thanks. So it seems my assumption that the ptrace call for XState will fail whenever AVX is not supported was wrong. I'll see how to fix this.

**Comment by 10110111** [comment]
Reproduces in QEMU with `-cpu qemu32,+xsave,level=13` on a host with AVX (Core i7-4765T).

**Comment by JackArchie** [comment]
edb is working perfecto in Arch Linux VM guest.
edb is working perfecto in Debian 8 VM guest.
Thanks!
I think we can close this issue.
