### ISSUE TITLE
Launching a new debuggee releases the old one instead of killing it despite the configuration setting to kill

### ISSUE THREAD

**Issue by 10110111** [eteran/edb-debugger#377]
I have "Terminate Debugged Application" option checked in Preferences/General, but when I run e.g. EDB in EDB, then select File->Recent Files->/bin/true, the EDB instance under debug gets released and opens its window etc. instead of being killed.

**Comment by 10110111** [comment]
I guess this is due to unconditional `detach()` at the beginning of `DebuggerCore::open()`.

**Comment by eteran** [comment]
agreed, should be easy enough to fix though.

**Comment by 10110111** [comment]
There're in fact lots of such calls to `detach()` in DebuggerCore, namely in `open()`.
