### ISSUE TITLE
EDB hangs in waitpid() when pid is leader thread and there're other threads in the group

### ISSUE THREAD

**Issue by 10110111** [eteran/edb-debugger#382]
This seems to be similar to [this GDB bug](https://sourceware.org/bugzilla/show_bug.cgi?id=12702). In short, I suspect that in my case (didn't try to reproduce again yet) main thread has exited before its clones, and EDB was doing `waitpid` on it. But `ptrace`/`waitpid` doesn't allow to reap the leader thread until all other threads in the group have been reaped. The GDB bug linked above is resolved as fixed, so maybe we can look into [its resolving patch](https://sourceware.org/git/gitweb.cgi?p=binutils-gdb.git;h=fa96cb382c12b099675c5cc238aaa7352a3fd3d7) to learn how to fix it in EDB.

**Comment by 10110111** [comment]
This can be easily reproduced as follows:

1. Launch two instances of EDB
2. From one instance, attach to another
3. Debug->Kill

The inferior instance will be killed, and superior one will hang in `waitpid`.

**Comment by eteran** [comment]
Yea, that is a weird one. I'll definitely take a look at the GDB patch to see if it can give us any ideas on how to best work around it on our end.

**Comment by 10110111** [comment]
The following patch seems to make it work, without leaving any zombies. I'm not sure what we want to do with the `pid`s which `waitpid()` returned, if `waitpid()!=pid()`. Also, EDB has some more `waitpid()` calls with non-`-1` `pid` argument, so might hang there in some circumstances too. We may want to make our own wrapper around `waitpid` to wait without hanging.
This is a bit ugly because it busily waits for the `pid` to exit instead of some type of sleep.
````
diff --git a/plugins/DebuggerCore/unix/linux/DebuggerCore.cpp b/plugins/DebuggerCore/unix/linux/DebuggerCore.cpp
index 3bb3f36..ed057ff 100644
--- a/plugins/DebuggerCore/unix/linux/DebuggerCore.cpp
+++ b/plugins/DebuggerCore/unix/linux/DebuggerCore.cpp
@@ -525,7 +525,7 @@ void DebuggerCore::kill() {
        ::kill(pid(), SIGKILL);
 
        // TODO: do i need to actually do this wait?
-       native::waitpid(pid(), 0, __WALL);
+       while(native::waitpid(-1, 0, __WALL)!=pid());
 
        delete process_;
        process_ = 0;
````

**Comment by eteran** [comment]
So there is another downside to this patch. Any wait events we see before reaching the target pid are outright dropped. This may be OK for the kill event since we want the process to go away regardless, but we should keep it in mind if we need similar fixups in other places.
