### ISSUE TITLE
Make new register view the default register view

### ISSUE THREAD

**Issue by eteran** [eteran/edb-debugger#383]
@10110111 

At this point the new "OllyDbg inspired" register view seems very functional. As far as I can tell, it offers everything the original view could show and more.

I would like to work towards both phasing out the old register view and towards making the UI have the new register view as part of the default UI arrangement.

This may mean upgrading the new register view from a plugin to being built directly into the main source tree (but maybe not, we'll see).

**Comment by 10110111** [comment]
The decision to make it a plugin was first of all dictated by it being very much tied to x86 architecture. I remember you wanted to make EDB more or less open to becoming cross-platform. If we completely remove the old tree-like register view, we may be unable to later view the registers if EDB is ever ported to e.g. ARM.

**Comment by eteran** [comment]
Right, I agree that keeping the modularity is still desirable. The goal of having it outright replace the current default is still something I'd like to work towards :-)

**Comment by eteran** [comment]
Just a thought (maybe a bad one since it's getting late here). Maybe the register plugin can/should be merged with the `DebuggerCore` plugin... Here's my thought process:

1. `DebuggerCore` is already **heavily** platform dependent.
2. The ability to view/edit register is a fairly core feature of the debugger.
3. If we support ARM one day, one way to do it would be to simply have a separate `DebuggerCore` plugin which explicitly is made for ARM.

The 3rd one is the weakest since it is possible to do it all in one plugin and avoid code duplication. That being said, perhaps support for multiple `DebuggerCore` plugins would be good (where you have the option to build 1 or more via cmake and can enable/disable them in the preferences).

Anyway, just some thoughts, if you feel like some of them don't make sense, just let me know.. like i said, it's getting late.

**Comment by 10110111** [comment]
This seems a bit wrong: DebuggerCore is mostly the plugin to support the platform-specific _operations_, it has nothing to do with GUI (at least currently). And register view is all about GUI, and in fact was specifically designed to work in modelview paradigm to not know anything about how the data are gotten. Do you really think these two things should be united in one plugin?

**Comment by eteran** [comment]
You're right. Just seeing it read back to me makes it clear how it's really not a good idea.

**Comment by eteran** [comment]
A default configuration places the new register view front and center by default. So I'm going to close this bug as it is "default" enough. I'd like to discuss the idea of outright removing the classic tree based view and just saying "like the debugger core, viewing registers is provided via a plugin"

**Comment by 10110111** [comment]
I think it's OK to remove the classic tree view. If/when a new arch is added, it's always possible to re-add it back as an initial version of the register view.
