### ISSUE TITLE
Give better reasons for failure to start process

### ISSUE THREAD

**Issue by 10110111** [eteran/edb-debugger#384]
Currently EDB just says "please check privileges and try again", which is at best not useful. I've made a patch to give better error messages, but I'm not sure whether this is a good change to `DebuggerCore` interface. See [my commit](https://github.com/10110111/edb-debugger/commit/8bf4b4c425c826d1059d6a8fff3a16c854d92eb1). Here I remove the overload of `DebuggerCoreBase::open` which doesn't take a `tty` string, and add another parameter to the second overload — `QString& errorString`, which would have error message if an error occurred.

This approach looks not too elegant to me. I'm thinking of two other approaches:

1. Have error string as return value, and consider function call successful if the string is empty
2. Return `bool` as now, but provide the error string similarly to `GetLastError()` (well, `getLastErrorString()` in fact) instead of requiring the `QString&` to be passed as argument.

What do you think would be best?

**Comment by eteran** [comment]
There are some more options:

1.  return a `std::tuple<bool, QString>` if the bool is `false`, then the string is an error message, otherwise it should be ignored.
2. The Qt-ish way is to return a string, but also have an `ok` out parameter which is a `bool` passed by pointer so that the "goodness" of the call is testable in a more obvious way.

Better error reporting is a good idea overall though.

**Comment by 10110111** [comment]
The variant with tuple seems explicitly redundant to me, although I did consider it at first. As for Qt-ish way, isn't it used when the return value is the _result_ of a function, and the boolean flag only used to check whether the result is valid? In the case of error message it seems a bit strange to have error string as "result" and a boolean flag as "whether result is valid".

**Comment by eteran** [comment]
Yea, you've convinced me. Having it return `QString()` on success is good enough.
