### ISSUE TITLE
Goto Address doesn't accept symbols as targets

### ISSUE THREAD

**Issue by 10110111** [eteran/edb-debugger#393]
For example, when I say "goto `.plt`", I get _Unknown Variable_. I'd instead expect not only being able to go to a symbol, but also to involve it in calculations, e.g. "goto .plt+6".

**Comment by eteran** [comment]
OK, I beleive that at the moment only registers are considered variables, we be easily expand this to include symbols. 

On the off chance that a symbol somehow conflicts with a register, I'll make the register take precedence (I don't think this is a big deal anyway since symbols have a module prefix like `hello.so!sym`)

**Comment by 10110111** [comment]
Do you mean to require the user to enter prefixed symbol? It seems to be an unnatural requirement, unless the symbols in different modules conflict.

**Comment by eteran** [comment]
No, just as a means of conflict resolution

if they type `ebx` it will choose the register `ebx`
if they type `module!ebx` it will choose the symbol `ebx` in `module`
if they type `module!main` of course it will choose the symbol `main` in `module`
if they type `main` it will choose the first symbol named `main` it finds in the loaded modules.

sound good?

**Comment by 10110111** [comment]
Yes, I like this.

**Comment by eteran** [comment]
So this is a little tricky, but for non-obvious reasons. The expression parser considers `!` a token delimiter since it's an operator.

So when you type: `ls!main` the parser sees: 

name: `ls`
operator: '!`
name: `main`

so I need to add some context sensitive smarts to the parser for this.

**Comment by eteran** [comment]
So I have a solution pushed for this, but there is an issue still (which I will make a separate bug). Basically, it is very much non-trivial to support module names with dashes in them, because they are also completely valid syntax for an expression subtracting values.
