### ISSUE TITLE
Forking debuggee makes EDB release both parent and child

### ISSUE THREAD

**Issue by 10110111** [eteran/edb-debugger#411]
Below is a sample C program which demonstrates the problem. To reproduce, run until the next line after `call fork@plt`, then just step. You'll get _Program exited with code 1_ in your face, and in the console you'll see debuggee's output `The child was unexpectedly killed by signal 5`, where signal 5 is `SIGTRAP`.

```
#define _POSIX_SOURCE
#include <stdio.h>
#include <errno.h>
#include <stdlib.h>
#include <stddef.h>
#include <sys/ptrace.h>
#include <sys/types.h>
#include <sys/wait.h>
#include <sys/user.h>
#include <unistd.h>
#include <signal.h>

int main(int argc, char** argv)
{
    const char* progPath="/bin/sleep";
    if(argc>1) progPath=argv[1];

    const pid_t pid = fork();
    switch(pid)
    {
    case -1: perror("fork"); return 1;
    case 0:
        if(ptrace(PTRACE_TRACEME)==-1)
        {
            perror("PTRACE_TRACEME failed");
            abort();
        }
        execl(progPath,progPath,"9463963",NULL);
        perror("execl");
        abort();
    default:    
      {
        int status;
        if(waitpid(pid,&status,__WALL)==-1)
        {
            perror("waitpid failed");
            goto error;
        }

        if(WIFSTOPPED(status) && WSTOPSIG(status) == SIGABRT) return 1;
        if(WIFEXITED(status))
        {
            fprintf(stderr,"The child unexpectedly exited with code %d\n",WEXITSTATUS(status));
            return 1;
        }
        if(WIFSIGNALED(status))
        {
            fprintf(stderr,"The child was unexpectedly killed by signal %d\n",WTERMSIG(status));
            return 1;
        }

        if(!WIFSTOPPED(status)||WSTOPSIG(status)!=SIGTRAP)
        {
            fprintf(stderr,"Unexpected status returned by waitpid: %#x\n",status);
            goto error;
        }

        if(kill(pid,SIGKILL)==-1)
            perror("Warning: failed to kill child");
        return 0;
      }
    }
error:
    if(kill(pid,SIGKILL)==-1)
        perror("Warning: failed to kill child");
    return 1;
}
```

**Comment by 10110111** [comment]
Here's what happens here: the debuggee gets `SIGCHLD`, and EDB simply passes this signal to it, letting it execute further:
```
ptrace(PTRACE_SINGLESTEP, 24529, NULL, SIG_0) = 0
waitpid(24529, [{WIFSTOPPED(s) && WSTOPSIG(s) == SIGCHLD}], WNOHANG|__WALL) = 24529
ptrace(PTRACE_GETSIGINFO, 24529, NULL, {si_signo=SIGCHLD, si_code=CLD_DUMPED, si_pid=25710, si_uid=1000, si_status=SIGTRAP, si_utime=0, si_stime=0}) = 0
ptrace(PTRACE_CONT, 24529, NULL, SIGCHLD) = 0
waitpid(24529, [{WIFEXITED(s) && WEXITSTATUS(s) == 1}], WNOHANG|__WALL) = 24529
```

**Comment by 10110111** [comment]
OK, so commenting this out I get this to work correctly:
```
	switch(event->code()) {
#ifdef Q_OS_UNIX
	case SIGCHLD:
	case SIGPROF:
		return edb::DEBUG_EXCEPTION_NOT_HANDLED;
#endif
```
What was the above code supposed to actually do? Looks like a hack to me.

**Comment by eteran** [comment]
Hmm, I don't recall what that code was working around...

**Comment by 10110111** [comment]
So, should it be removed? I think we'll not find out what it was for until it's gone. It has been in the code base since the first git commit.

**Comment by eteran** [comment]
Yea, it's probably no longer serving a purpose. My guess is that it was a work around for tests ng debugging some of the more complicated programs before edb had robust signal handling.

**Comment by eteran** [comment]
So an update on this. If we remove that code, then by default something like: `./edb --run ./edb` will fail. The subprocess will fail to start.

It seems we **need** to send the `SIGCHLD` to the debugee in order for it to work, which makes sense since edb uses that extensively. I imagine, that this was the reason for my little hack there.

However, we have had for a while now, an interface for telling edb to ignore signals (passing them to the debugee), which is the proper solution in my mind. So I am going to chop this code out. If a user needs to pass a signal to a child process to make it able to be debugged, we have an interface for that. And now we have an issue which people can refer to.
