### ISSUE TITLE
Syntax-highlighted disassembly is vertically misplaced relative to address and instruction bytes

### ISSUE THREAD

**Issue by 10110111** [eteran/edb-debugger#414]
See the screenshot. The syntax highlighted `vmulps` and `vsqrtss` instructions are rendered a pixel too high, while `nop`s are all correctly placed. The difference is that the former are syntax highlighed, while the latter are drawn as filling.
![edb-7px-font-syntax-highlighted-position-bug](https://cloud.githubusercontent.com/assets/6376882/15255431/9d908c14-1944-11e6-99da-f2843a70874d.png)
The above screenshot was made with disassembly view font _Droid Sans Mono 7_.
This bug will affect #337 once we want to apply its solution to other columns than just instruction bytes.

**Comment by eteran** [comment]
So I'm having a hard time pinning this down :-/.

As an experiment, I made it render both using `draw_rich_text` and `painter.drawText` overlapping and as long as I ignore things which are bolded/italic it does look like it lines up perfectly on my machine (with that font).

**Comment by eteran** [comment]
Looking at this screen shot more carefully , it *looks* to me like it depends on which line you are looking at! Look at the `nop` @ `001008a`, it has a small gap before the baseline. But the subsequent instruction doesn't look like it has this gap :-/. So this looks to me, like an issue with a non-integer character height or similar (I have a similar bug WAY back with a float based font width).

**Comment by eteran** [comment]
Can you give the following patch a try and see if it helps at all? I've made it use `qreal` instead of `int` in some places int he hopes of catching these fractional font heights correctly:

https://gist.github.com/eteran/a1c46350c7e9cb4721e97b6850532bd2

**Comment by 10110111** [comment]
Doesn't seem to change anything. BTW, the text sometimes is more than one pixel displaced, see this screenshot taken on another machine, with _DejaVu Sans Mono 6_:
![screenshot - 180516 - 08 12 58](https://cloud.githubusercontent.com/assets/6376882/15348150/c6e25d06-1cd0-11e6-97d9-0b089e932e8c.png)
Here the colored text is two pixels above its correct place.

**Comment by eteran** [comment]
hmm, unfortunately i am having a little difficulty reproducing the same effect so it's hard to know if i'm on the right track, but I'll keep plugging at it.

**Comment by eteran** [comment]
PS. does it happen with larger fonts in any noticeable way? My previous difficulties with non-integer font dimensions were mostly visible when dealing with small fonts.

**Comment by 10110111** [comment]
Yes, larger fonts have the opposite problem, see this, right above the selected line:
![screenshot - 180516 - 08 44 50](https://cloud.githubusercontent.com/assets/6376882/15348628/fc3e88ea-1cd4-11e6-8bea-9be8f9ff67f8.png)

**Comment by eteran** [comment]
Do we know if this is still a problem in light of the large changes done to the rendering algorithm?

**Comment by 10110111** [comment]
Rendering is inconsistent between selected and non-selected lines:
![scrn](https://cloud.githubusercontent.com/assets/6376882/21340987/0d227b2e-c69b-11e6-84db-3027b338ec0f.png)

Also, for some reason mnemonics of many instructions like `rdtsc` and SIMD ones (`vsqrtss`, `vmulps`, `rpcss` etc.) are not syntax-highlighted now, while such instructions as jumps are.

**Comment by AaronOpfer** [comment]
Do you mind copying your appearance config settings into this thread? Also
info about what DE you're using and what DPI your monitor is.

**Comment by eteran** [comment]
Well, `rdtsc` not being highlighted is pretty simple, it doesn't currently have a highlight rule ( I don't see any for the SIMD ones either).

Looking at the merge where I changed the syntax highlighting code, it doens't look like these were ever covered:

https://github.com/eteran/edb-debugger/commit/77b31c53dccf511688e765db93ad080b8242081e

**Comment by 10110111** [comment]
My default config is as follows:
```
[Appearance]
appearance.address_colon.enabled=false
appearance.address_semicolon.enabled=false
appearance.data.font="DejaVu Sans Mono,8,-1,5,50,0,0,0,0,0"
appearance.data.row_width=16
appearance.data.show_address.enabled=false
appearance.data.show_ascii.enabled=true
appearance.data.show_comments.enabled=true
appearance.data.show_hex.enabled=true
appearance.data.word_width=1
appearance.disassembly.font="DejaVu Sans Mono,8,-1,5,50,0,0,0,0,0"
appearance.registers.font="DejaVu Sans Mono,8,-1,5,50,0,0,0,0,0"
appearance.stack.font="DejaVu Sans Mono,8,-1,5,50,0,0,0,0,0"
```

For testing I changed disassembly font to size of 36 (in the GUI). Resolution:

```
$ xdpyinfo|grep dots
  resolution:    86x87 dots per inch
```

DE is a mixture of KDesktop (from KDE3), KWin (from KDE4), xfce4-panel (4.4), no session/desktop manager whatsoever.

**Comment by eteran** [comment]
I think I see what happened. I think we previously used to just default to blue if there was no rule, but now we default to black.

**Comment by 10110111** [comment]
Ah, that does make sense.

**Comment by eteran** [comment]
So I can replicate things going below the base line. It is particularly obvious for things which have a background color (like `call`/`ret`) where the yellow box obviously goes below the line.

I have no idea why it happens though :-/

**Comment by eteran** [comment]
Woah, though new bug :-P We need to invalidate the `QPixmap` cache if the user changes the font size :-P

**Comment by AaronOpfer** [comment]
Yeah, we do. Looks like we need to connect the QDisassemblyView to the configuration change event.

**Comment by eteran** [comment]
yup, i can do that real quick

**Comment by eteran** [comment]
interesting... calling `syntax_cache_.clear()` and forcing an update doesn't seem to be enough to completely force a fresh render. Strange.

**Comment by AaronOpfer** [comment]
Do you think that's because the paint event doesn't trigger or because the cache doesn't empty?

**Comment by eteran** [comment]
i think it must be that somehow we are mid-update or something. Because **some** lines do get fresh renderings. But some others don't

**Comment by AaronOpfer** [comment]
That's strange. We don't do any partial rendering in QDisassemblyView. How many threads does edb usually use?

**Comment by eteran** [comment]
1 mainly, but Qt likely has some implicit ones. I have a plan though. We can always optimize it later if needed.

**Comment by eteran** [comment]
OK, this is downright bizarre. I tried making it so the update event flipped a flag that during the next update, it would first clear the cache. And that too results in a mix of old/new renderings. I don't understand how that's possible. Looking into it...

**Comment by eteran** [comment]
pushed a naive effort to fix. It doesn't work. @AaronOpfer  see if you can replicate?

All I do is set the font size large, then set it small, and it only half updates the UI correctly :-/

**Comment by eteran** [comment]
@10110111 is it possible that you were running into something with the cache? Cause looking at your latest screen shot. It looks like the highlighted line is actually a different font from the rest. ("C" is smaller and has slightly different styling).

**Comment by 10110111** [comment]
May have been related to cache. After latest pushes it doesn't look that much inconsistent, and the selected line is aligned correctly, but other lines are still not aligned: error ±1px at least at sizes 36 and 26:
![scrn](https://cloud.githubusercontent.com/assets/6376882/21344882/0f98f978-c6af-11e6-808e-d95b7e2db695.png)

**Comment by eteran** [comment]
@10110111 I think I may have stumbled upon the right answer. Need to do some experimentation (and if possible have you take a look since you've noticed this issue the most).

So I think the issue here is that fixed size doesn't necessarily mean integer size. Which means that we are unacceptable to rounding issues and similar. But due to work on another project, I stumbled on the fact that `QFont` has the ability to set the "styleStrategy" to `ForceIntegerMetrics`. It isn't guaranteed to be accepted, but it works most of the time.

And when it does, all font metrics are nice round integers, making things line up (at least in my other project) perfectly and reliably.

I'll follow up when I have something worth testing in place :-)

**Comment by 10110111** [comment]
Seems to look correctly now.

**Comment by eteran** [comment]
Nice! another bug down :-).

Thanks for checking.

**Comment by 10110111** [comment]
It seems there _is_ a problem, although not about relative positioning, but about clipping:

![scrn](https://cloud.githubusercontent.com/assets/6376882/25428697/3da324fe-2a7f-11e7-9cd3-267232c458af.png)

See the lines with arrows: the underscores in the function names are invisible (clipped?).

**Comment by eteran** [comment]
ah, so close. I'll look into it.

Which font and size are you using?

**Comment by 10110111** [comment]
DejaVu Sans Mono 8.

**Comment by eteran** [comment]
I couldn't reproduce this exactly. On my system, the underline was 1px above the bottom of the rect.

However, now that we force integer metrics, I switched away from using floats in line height calculations. Additionally, I've added a 1px of padding to the line height in the hopes that it will solve this for you. Let me know if latest master looks good for you.

**Comment by 10110111** [comment]
Yeah, on another machine (LFS) it also looks 1px above — with the same font name and size. It's only on Kubuntu 14.04 that it did look clipped. Now I've checked, and it looks good on both.
