### ISSUE TITLE
format_argument in ArchProcessor hard-codes EDB types instead of debuggee ones

### ISSUE THREAD

**Issue by 10110111** [eteran/edb-debugger#422]
`format_argument` and `format_integer` functions in ArchProcessor hard-code native types of EDB regardless of personality of current debuggee. This may break in particular for 32-bit EDB with 64-bit debuggee, but also might show wrong results with `long` vs `int` vs `long long` with 64-bit EDB and 32-bit debuggee.

**Comment by eteran** [comment]
@10110111 do you know if this is still an issue?

**Comment by 10110111** [comment]
At least, `format_integer` now appears to have some checks for debuggee bitness, so I think it should have been fixed.

**Comment by eteran** [comment]
Sweet! Another bug we can close :-).
