### ISSUE TITLE
RFC: switch all `bool* ok` with `Q_ASSERT(ok)` to `bool& ok`

### ISSUE THREAD

**Issue by 10110111** [eteran/edb-debugger#427]
Currently EDB has lots of _mandatory_ pointers like `bool* ok`, which are in actual places of setting asserted with `Q_ASSERT(ok)`. This doesn't make sense in C++: generally, if a function wants a valid reference to an object, it should take it by reference. If it takes a pointer when a reference would work, it should expect that the pointer can be null.

So I propose that instead of these lots of assertions these functions take `bool&`. A reference can't refer to a null object if it was not obtained through UB.

Any arguments against?

**Comment by eteran** [comment]
So, I'm not dead set on this stylistic choice, but I'll explain and we can go from there. The idea is to make obvious at the call site that a variable is an "out" variable. Meaning that the value it has when passed to the function is meaningless, and the function it is passed to is expected to fill it in.

Ideally we would be 100% consistent with ordering of types of variables as well in the order of "in", "in/out", "out".

PS. this reminds me. I would like to put together a style guide to help makes things consistent since the project has been in progress for a long time at the point and stylistic choices have evolved over time. I'd like to get your input on this since you've been such a large contributor, I wouldn't want to make new rules that only make things difficult for you :-).

**Comment by 10110111** [comment]
In fact, I'd like to propose a completely different approach to these `ok`-type variables. Namely, EDB would have a set of classes like the following two for results with an error message (like `DebuggerCore::open()`)
```
class AnnotatedStatus
{
    QString errorMessage;
public:
    bool success() const { return errorMessage().isEmpty(); }
    bool failure() const { return !success(); }
    QString toString() const { return errorMessage; }
};
template<typename ValueType>
class AnnotatedResult
{
    AnnotatedStatus status;
    ValueType value;
public:
    ValueType operator*() const { return value; }
    bool succeeded() const { return status.success(); }
    bool failed() const { return !succeeded(); }
    explicit operator bool() const { return succeeded() };
    QString errorMessage() const { return status.toString(); }
};
```
And for results without message (e.g. reading a byte from userspace) we might even just use `boost::optional`.

Then we have four cases:

1. Return of just status, without message (for speed). This may be plain `bool success` as return value, as is in `DebuggerCore::write_data()`.
2. Return of value, accompanied by status, without description. This may be `boost::optional` or some custom class if it's not good enough
3. Return of status with message, but no data, e.g. `DebuggerCore::open()`. This would be `AnnotatedStatus` described above.
4. Return of status with message + data. This would be `AnnotatedResult` described above.

Then we can completely get rid of strange pointers to `bool` passed into functions (and can then use more `const` variables in the code ;))

**Comment by eteran** [comment]
I was out of town for a bit, but looking at your suggested classes, I like this idea a lot. Maybe `AnnotatedStatus` should have an explicit `operator bool` as well?

Either way, I am in favor of starting a migration to this style.

**Comment by 10110111** [comment]
Yes, `operator bool` would be good there indeed.

**Comment by eteran** [comment]
A version of these classes is now present in `include/Status.h`

In there are `Status` and `Result` respectively, which are analogous to your `AnnotatedStatus`, and `AnnotatedResult` classes. (I like the more terse names so long as they don't conflict with anything).

Next will be starting to use these in various parts of edb :-)

**Comment by eteran** [comment]
Started conversion of some code, it's looking good. Though I am running into one quirk that I don't understand :-(.

Code like this compiles for unknown reasons, despite the `explicit operator bool() const`

    if(Result<int> v = func() {
        func2(v); // NOTE: missing * in front of v !!! why is it implicitly converting here?
    }

But besides that, it works perfectly (just have to remember the `*` usage.

**Comment by eteran** [comment]
The conversion isn't 100%, but it's mostly done so I'll consider this bug closed.
