### ISSUE TITLE
Building EDB for Window

### ISSUE THREAD

**Issue by Djamana** [eteran/edb-debugger#429]
Background is that there is no OllyDbg for 64 bit.

Well I tried that: 
Installing CMake
Getting QT 
boost_1_61_0
capstone-3.0.4-win64
VS 2015
...finally got out some VS Project files for Visual Studio.

But starting build there I just get errors over errors.

Hmm so I wonder if this the first time some tried?

**Comment by 10110111** [comment]
I'd say it's long been broken. Actually it won't compile for anything but Linux currently. There might have been a version which built in Windows though.

**Comment by 10110111** [comment]
In fact, for Windows you can currently resort to x64dbg: it does work and is also very similar to OllyDbg.

**Comment by eteran** [comment]
@10110111 is correct. The Windows port is not in a funtional state. But getting it back up to speed is planned: See issue #261
