### ISSUE TITLE
No indication that breakpoint failed to be set

### ISSUE THREAD

**Issue by 10110111** [eteran/edb-debugger#433]
`Breakpoint::Breakpoint()` should throw on failure to be created, and the creator should catch this exception and report this to the user. If it was part of a complex action, like _Next_ or _Run to line_, then the whole action should be aborted.

**Comment by eteran** [comment]
Generally complete. Now the constructor will throw a `breakpoint_creation_error`, which is caught by the current implementation of `add_breakpoint`.

This function will report the error to the console and return `IBreakpoint::pointer()`. So the higher layers can detect that this function returned a null smart pointer and take appropriate actions.

As for the atomic handling of this error, that is something that will need a bit more effort on a case by case basis.
