### ISSUE TITLE
Add configuration option to center window on start

### ISSUE THREAD

**Issue by eteran** [eteran/edb-debugger#435]
zebus3D on twitter has requested this feature.

https://twitter.com/zebus3d/status/752233922830925824?cn=bWVudGlvbg%3D%3D

**Comment by 10110111** [comment]
In general it seems this is a job for a window manager. So this should be optional if implemented in EDB itself.

**Comment by eteran** [comment]
Absolutely optional, I'm thinking it'll be a simple checkbox in the settings defaulting to off so that users will get what the WM prefers by default.

**Comment by 10110111** [comment]
Doesn't it seem too localized to offer centering but not any other layout? Maybe better to restore geometry the window had at last shutdown?

**Comment by eteran** [comment]
Well we do restore things such as width, height, and dock widget locations. We could offer 3 options I suppose:

1. center main window on load
2. restore main window location on load
3. use default placement

It seems that the pain point that this user is looking to work around is that their WM doesn't do something sane by default.

**Comment by 10110111** [comment]
Yeah, it just seemed to me that `1.` can be thought of as a special case of `2.` when it's the user preference, since the user would move the window to the center anyway.

**Comment by zebus3d** [comment]
Yes, fully optional. But not all window managers like to recall the position, and as the implementation is relatively easy, so I proposed.

**Comment by eteran** [comment]
All done, sorry it took so long! needed a break from side projects for a bit :-)

**Comment by zebus3d** [comment]
Thanks!! :)
