### ISSUE TITLE
some newbie questions

### ISSUE THREAD

**Issue by zebus3d** [eteran/edb-debugger#438]
I have some questions.

1 A part of the wiki have thought about doing some tutorials?
2 Common buttons [ run, step into, step over, step out ] will be explained in the wiki?
3 types of analyzers will also be explained?
4 Is there any way to know the names of the functions (stripped or not)?
5 Is there any way to know where are using a string?
6 There is some forum where can do all these questions?
7 Can view the strings inside the nodes in the Graph window?.

Many thanks.

**Comment by eteran** [comment]
1, 2, 3. Yes, would love some more documentation and tutorials of **everything** in edb. It's really a matter of time and effort. If anyone in the community wants to contribute to the wiki for either documentation or tutorials. It is **very** welcome :-).
4. If the binary is stripped and there is no debug info file. Then there's not a whole lot we can do to resolve function names. If we have symbol information, we should be good to go. I suppose **hypothetically**, we could have a plugin which has a database of code patterns and associated names and tries to infer what a function should be called. But that's some pretty advanced stuff that would take a lot of time and effort to do effectively (and may end up not working very well for anything besides a toy test case).
5. See the References plugin. If you know the address of the start of the string, you can find code which has that address in use. It's not perfect, but it does a pretty good job. Also the Heap explorer plugin will show strings in heap blocks if it can.
6. No forum (yet), but I'd be open to one if the community wants it. For now, we do have a [gitter](https://gitter.im/eteran/edb-debugger) for a "live" chat. Though no one has chosen to use it yet. If I get a notification that a question was asked there though, I'll be sure to respond ASAP :-).
7. The graph view is new and still evolving. So I would say not yet but one day!

I hope that answers your questions.
