### ISSUE TITLE
Goto Address doesn't work in any pane

### ISSUE THREAD

**Issue by wdormann** [eteran/edb-debugger#441]
I'm running latest 0.9.21 master https://github.com/eteran/edb-debugger/commit/9a597e06d1152c4d00c78438dfd30890d9f90896

When I hit Ctrl-G for any of the panes, I'm prompted for an address.  When I type in e.g. a register or the hex value for the address I want to go do, nothing happens.  No errors seem to be present in the terminal from which I launched edb.  If I type in something invalid, I'll get the respective error like Unknown Variable or Invalid Numerical Constant.

**Comment by eteran** [comment]
Interesting, must be related to a recent change I made, I will look into it and put up a fix ASAP

**Comment by eteran** [comment]
Should be fixed as of 9a597e0, sorry about that!

**Comment by wdormann** [comment]
Looks good!   thanks.
