### ISSUE TITLE
"ACCESS DENIED:  open_wr: /proc/21190/mem" when compiling on Gentoo and portage.

### ISSUE THREAD

**Issue by Petross404** [eteran/edb-debugger#443]
Congratulations for the great tool you managed to create. I like edb so much, that I decided to make an ebuild (gentoo's "script" for portage to install software). When I use git clone in my home directory and try to compile it, everything goes just fine. It compiles and run like a charm.

But when portage try to do the same job in order to install it, this error arrise: 
`* ACCESS DENIED:  open_wr:      /proc/21190/mem
../../proc-pid-mem-write: failed to open memory file: Permission denied
Warning: failed to detect whether write to /proc/PID/mem is broken. Assuming it's not.`

Note that the error doesn't stop the compilation process and doesn't seem fatal at first. But after the compilation gets to 100%, this error comes up:
`>>> Source compiled.
 * --------------------------- ACCESS VIOLATION SUMMARY ---------------------------
 * LOG FILE: "/var/log/sandbox/sandbox-23377.log"
 * 
VERSION 1.0
FORMAT: F - Function called
FORMAT: S - Access Status
FORMAT: P - Path as passed to function
FORMAT: A - Absolute Path (not canonical)
FORMAT: R - Canonical Path
FORMAT: C - Command Line

F: open_wr
S: deny
P: /proc/24215/mem
A: /proc/24215/mem
R: /proc/24215/mem
C: ../../proc-pid-mem-write /tmp/portage/dev-util/edb-9999/work/edb-9999_build/plugins/DebuggerCore/procPidMemWrites.h 
 * --------------------------------------------------------------------------------`

I am not asking you to debug my ebuild or something. Just what is the issue with proc.

PS. I use this entry in fstab
`proc                    /proc           proc            defaults        0 0`
`shm                     /dev/shm        tmpfs           nodev,exec,nosuid  0 0`

The ebuild (if you happen to ever written one for Gentoo)
[https://raw.githubusercontent.com/Petross404/local/master/dev-util/edb/edb-9999.ebuild](url)

**Comment by 10110111** [comment]
Apparently portage is very strict regarding what the application's build system can probe. EDB build system probes whether writes to `/proc/<PID>/mem` are broken on current kernel (assuming that the current kernel will be the kernel to run the process built). For this it creates a child, does `PTRACE_TRACEME` from it, and the parent starts debugging it. The parent then opens child's `mem` file, and portage appears to disallow this.

**Comment by eteran** [comment]
Yea, we may need to offer an override flag during the build to allow the user to specify whether or not the feature being tested should just be assumed to succeed or fail.

**Comment by Petross404** [comment]
Thanks for the quick response. Whatever you decide to do with the configuration flags I am able to implement it in the ebuild with a simple cmake configuration option.

Have a nice day :)

**Comment by eteran** [comment]
@Petross404 OK, I've added a new cmake flag that you can leverage, it has 3 options:

    cmake -DASSUME_PROC_PID_MEM_WRITE_BROKEN=No ..
    cmake -DASSUME_PROC_PID_MEM_WRITE_BROKEN=Yes ..
    cmake -DASSUME_PROC_PID_MEM_WRITE_BROKEN=Detect ..

"Detect" is the default behavior of trying to test the system.
"Yes" means that the build should assume this feature is broken 
"No" means that the build should assume this feature works (works on *nearly* all supported kernels, just a few versions were broken for some distros, so this is probably what you want).

Thanks so much for making the ebuild!

**Comment by eteran** [comment]
Also, of course if you run into any issues, just let us know and we'll get right on it :-D

**Comment by Petross404** [comment]
Thank you very much! Although I didn't find an acceptable way to implement all the flags, I did implement just the "Detect" (which of course failes) and "No" flags - "No" compiles without problem. I did "fit" the "Yes" flag but the code got messy.

Once again thank you very much for your kind response and effort. Next step for me is to find a way to port this in a testing overlay for Gentoo, so that more users come to find and install edb. 

If anyone would like to take a look: [https://github.com/Petross404/local/tree/master/dev-util/edb](url)

**Comment by eteran** [comment]
So, for Gentoo's ebuild, I would ditch the auto-detect and would handle this with a USE flag, something like `legacy-memory-api` or similar. After all, Gentoo is all about user's being able to customize the builds of what gets installed (I'm a Gentoo user myself :-D)

If set, I would use `ASSUME_PROC_PID_MEM_WRITE_BROKEN=Yes`, otherwise, I would set `ASSUME_PROC_PID_MEM_WRITE_BROKEN=No`.

Also, as a side note; the graphivz dependency is entirely optional, so you can make that based on a `graph` USE flag or similar. Never hurts to give users more control.

**Comment by Petross404** [comment]
I followed your advices. I removed the "Detect" USE Flag and I put a warning which informs the users that if `ASSUME_PROC_PID_MEM_WRITE_BROKEN=No` is being used and edb doesn't work properly, they should enable the USE Flag and rebuild.

Also changed the description (and the name) of `legacy-mem-write` in metadata.xml and managed (?) to create a desktop entry. I am getting this warning, which is probably due to the fact that a .desktop file (not fully Gentoo-compliant) is provided.
`# * As described in the Icon Theme Specification, icon file extensions are not 
#* allowed in .desktop files if the value is not an absolute path.`

Either there is something that portage doesn't like about the icon refererence in the .desktop, either something else that I am missing out.

Anyway I don't know if this is the right place to talk about the ebuild anymore, but here there is a thread for other gentoo users to comment and critic it, before I try to report a bug for a new package and upload the ebuild. :)
[https://forums.gentoo.org/viewtopic-t-1052088.html](url)

**Comment by eteran** [comment]
Excellent work :-)

I had some other comments about your ebuild, please see them on your issue tracker: https://github.com/Petross404/local/issues/1
