### ISSUE TITLE
Could a tag/release for the latest commit be created?

### ISSUE THREAD

**Issue by Petross404** [eteran/edb-debugger#444]
Hello there! I managed to reach out some folks @#gentoo-sunrise about the ebuild and we were wondering, if you could provide a release so that we keyword it as ~[ARCH] and not as hard masked.

Thank you for your time and the help you provided!

**Comment by eteran** [comment]
Yea, I would like to do a formal release sometime soon, I'll close this bug when it is done :-)

**Comment by Petross404** [comment]
Great news :)

**Comment by eteran** [comment]
You've inspired me! Here's the **long overdue** release of 0.9.21. I recommend uses the tarball I've attached to the release as it includes the submodules already.

https://github.com/eteran/edb-debugger/releases/download/0.9.21/edb-debugger-0.9.21.tgz

Thanks to everyone who contributed to this, @10110111 has been especially helpful over the past year :-D.
