### ISSUE TITLE
edb48-logo.png is installed but desktop file expects edb.png

### ISSUE THREAD

**Issue by ZeroChaos-** [eteran/edb-debugger#446]
The desktop file seem to expect edb.png:

https://github.com/eteran/edb-debugger/blob/master/edb.desktop#L6

But edb48-logo.png is what actually gets installed:

https://github.com/eteran/edb-debugger/blob/master/CMakeLists.txt#L56

The preferred icon should likely be renamed to edb.png and CMakeLists.txt updated.  I tried to just rename it on the CMake line where it was being installed, but it ended up installing into /usr/share/pixmaps/edb.png/edb48-logo.png, so either Cmake can't do it, or I did it wrong.

**Comment by eteran** [comment]
OK, i'll make a copy of the logo file as edb.png and update the CMakeLists.txt appropriately
