### ISSUE TITLE
CMake fails at edb-debugger-0.9.21.tar.gz but not at edb-debugger-0.9.21.tgz

### ISSUE THREAD

**Issue by Petross404** [eteran/edb-debugger#449]
When I try to run `cmake .` at the the top directory of edb-debugger-0.9.21 (which was extracted from **.tar.gz** file), I continue to get :

`CMake Error at src/CMakeLists.txt:197 (add_executable):
  Cannot find source file:

    qjson4/QJsonArray.h

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx

CMake Error: CMake can not determine linker language for target: edb
CMake Error: Cannot determine link language for target "edb".`

CMake ran under edb-debugger-0.9.21 (which was extracted from **tgz** file) finishes without error. Do you think some submodules are missing from some archives? Strange though, because both are at the same version.

**Comment by eteran** [comment]
Right, so the auto-generated `.zip` and `.tar.gz` that github generates does not include sub-modules unfortunately, so they won't work :-(.

This is why I uploaded the .tgz file. I'll clarify on the releases page though.
