### ISSUE TITLE
On grsecurity hardened kernels /proc/<pid>/mem reads fail

### ISSUE THREAD

**Issue by eteran** [eteran/edb-debugger#451]
We have a tool detect if writes will fail, but have always assumed that reads will succeed. We should improve our tool to detect a an report a broken read and update PlatformProcess accordingly.

**Comment by 10110111** [comment]
BTW, I just thought: why not move the detection to runtime — initialization or whatever stage? This will allow avoid the need of manual setting for ebuilds etc. as well as allow for build kernel be different from actual run kernel.

**Comment by blshkv** [comment]
Runtime would make more sense. Keep in mind that we compile tools in sandbox so /proc is not accessible regardless hardened or not.

**Comment by eteran** [comment]
@10110111 you're probably right, we should hoist this into the DebuggerCore constructor or something similar amd ditch compile time detection of this feature.

**Comment by eteran** [comment]
@blshkv can you see if master works for you correct in the ebuild? and the see if the debugger loads properly?

I've made this feature detected at runtime instead of compile time, so I think we should be good to go. If so, i'll make a 0.9.22 release so we have something official for packages.

**Comment by eteran** [comment]
BTW, you will of course no longer need to use the `ASSUME_PROC_PID_MEM_WRITE_BROKEN` flag during cmake, as this feature is no longer tested at compile time.

**Comment by 10110111** [comment]
I get
```
Detect that read /proc/<pid>/mem works  =  false 
Detect that write /proc/<pid>/mem works =  false
```
on my linux 3.12.18-amd64, where it has always worked with compile-time detection.

**Comment by eteran** [comment]
hmm, can you trace through and see which code path is failing? it is essentially the same code and seems to work here. I wonder if ASLR is somehow getting in the way?

**Comment by 10110111** [comment]
Will try when I get back to that machine. BTW, your call to `feature::detect_proc_access` doesn't even check for the return value. It'll assume that nothing is broken if check fails before writing to the variables. This is no good for a runtime check.

**Comment by eteran** [comment]
Sure, but the behavior should be the same. The old code would assume "not broken" if the `detectAndWriteHeader` function returned `false`. This code initializes the variables to "not broken" and doesn't modify them if the function returns false. So in both cases, it assumed success if it could not test.

Unless I am missing something :-/

**Comment by 10110111** [comment]
Yes, I was not talking about the issue on 3.12.18, it's just what I noticed while looking into the code.

**Comment by 10110111** [comment]
OK, first I have to note that the problem is with 32-bit EDB.
Now, despite your new code doesn't call `exec` after `fork`, and instead calls `raise`, for some reason the libraries' memory space isn't accessible for reading. ASLR can't be a problem, since after `fork` the child has exactly duplicate memory space, up to stack and heap. I've had some success with using address of `edb::v1::version()` instead of `detect_proc_address`, but I'm not sure whether it'll always work, since I don't know the exact reason why library function's address doesn't.

I suggest you to actually do an `exec`, and then use a function in `edb` binary like `edb::v1::version` to thoroughly fix this.

**Comment by eteran** [comment]
By "some success", do you mean to say that it worked reliably? Or that it worked some of the time?

My main concerns are that exec'ing a whole other edb may be a bit on the expensive side, and I do hate it when programs are unnecessarily slow :-/

**Comment by eteran** [comment]
you know what, i bet it has to do with the fact that `detect_proc_address` is in a plugin! perhaps some configs handle memory of dynamically loaded plugins in unexpected ways?

**Comment by eteran** [comment]
so i just pushed a change where it uses `edb::version` since that's in the core executable. Can you let me know if that works well and/or isn't reliable?

**Comment by 10110111** [comment]
By some success I mean that it did work every time I tried, but I can't be sure that it's really well-defined to work reliably.

**Comment by 10110111** [comment]
Dunno what's different: here's the address map of the child:
```
08048000-082d4000 r-xp 00000000 08:23 402901165                          /usr/bin/edb
082d4000-082d6000 rw-p 0028c000 08:23 402901165                          /usr/bin/edb
082d6000-082d7000 rw-p 00000000 00:00 0 
08fdd000-090f1000 rw-p 00000000 00:00 0                                  [heap]
f2c63000-f2ce0000 r-xp 00000000 08:23 270212916                          /usr/lib/edb/libDebuggerCore.so
f2ce0000-f2ce3000 rw-p 0007d000 08:23 270212916                          /usr/lib/edb/libDebuggerCore.so
```
This is exactly the same as for parent. And the address of `detect_proc_address` page is 0xf2cc9000, which is in the first of the chunks for `libDebuggerCore.so`. Access rights for `libDebuggerCore.so` are exactly the same as for `edb`. So something is really strange. I'm not sure what EDB currently does is reliable, although now it does appear to work after your commit.

**Comment by eteran** [comment]
Hmm, OK. So it is odd.

Could actually be a kernel bug where reading and writing through ptrace fails to trigger CoW semantics under certain circumstances or something subtle like that? Dunno.

For now, I say, let's keep an eye on it and see if any users are negatively effected. So I'm gonna close this bug, but will keep this thread in mind going forward.

**Comment by 10110111** [comment]
I don't think the users will report even if they notice the slowness. This feature is mainly a performance feature.

Anyway, on another thing: I suggest to make EDB expect that the feature is broken by default, so that if the test fails at an early stage, EDB wouldn't blindly try to use the `/proc/PID/mem` API. When this test was in the build system, the opposite default made sense, since the build environment could (and did, it appears) intervene. In the runtime EDB should believe its failures.

**Comment by eteran** [comment]
live chat on gitter (or whatever) to avoid extended convo in bug report? You can just glick the gitter badge on the main page.

**Comment by eteran** [comment]
In latest master, user is prompted if they have a broken kernel now :-) @10110111 let me know if you run into any issues with it. The code is simple, so I expect it to be correct though.

**Comment by blshkv** [comment]
Ok, tested, I've got the qt warning message after the following:
```
EDB is in 64 bit segment
OS is 64 bit
Detect that read /proc/<pid>/mem works  =  true
Detect that write /proc/<pid>/mem works =  false
```

Not sure about the performance but it works. Thank you!

**Comment by eteran** [comment]
It seems that a grsecurity setup prevents writing through `/proc/<pid>/mem`, I will update the message to inform the users about this as a potential cause.

Thanks for testing :-)
