### ISSUE TITLE
/proc/pid/mem warning dialog looks suboptimal

### ISSUE THREAD

**Issue by 10110111** [eteran/edb-debugger#454]
See the screenshot:

![screenshot](https://cloud.githubusercontent.com/assets/6376882/19016296/6ca521ca-881e-11e6-94f6-e6c1ed58bf4b.png)

The dialog seems oversized vertically. This is with Qt4, if it matters, and on Kubuntu 12.04 (Precise), where the first problems with writing to `/proc/pid/mem` happened for EDB.

Why not just use stock Warning message box?

---

BTW, notice the "may bbe" typo in the message text.

Also, I'd suggest to list multiple possible reasons, like this:

> This may be due to some of the following:
> * the kernel is very old and restricts writing to /proc/<pid>/mem
> * the kernel has **grsecurity** enabled
> * EDB's feature detection has hit a bug

**Comment by eteran** [comment]
good call, i'll fix. Probably a result of my current screen having a newly HiDPI display and me sizing based on that.

**Comment by eteran** [comment]
give it a go now and see if it looks any better please :-)

**Comment by 10110111** [comment]
Still oversized:

![screenshot](https://cloud.githubusercontent.com/assets/6376882/19017064/59f84e86-8836-11e6-8417-a71add93bcf8.png)

Also, the bullets seem to have too much spacing between them.

**Comment by eteran** [comment]
trying one more thing, does it look a little better now?

**Comment by 10110111** [comment]
You seem to have not pushed anything.

**Comment by eteran** [comment]
you are corect, pushed

**Comment by 10110111** [comment]
Didn't change anything.

**Comment by eteran** [comment]
lame, OK, can you try resizing it in the qt-designer? The only caveat is that you need to manually add the "DebuggerCore::" prefix to the `<class>DebuggerCore::DialogMemoryAccess</class>` tag in the UI file after editing since the designer removes it.

**Comment by 10110111** [comment]
Will try ASAP, but have to go now. Are there any good reasons why you don't want to use `QMessageBox`?

**Comment by eteran** [comment]
I wanted the checkbox at the bottom, it's really the only reason.

**Comment by 10110111** [comment]
Here's what I get if I resize to 360x276 (see git diff output in the Konsole window in this screenshot):

![screenshot](https://cloud.githubusercontent.com/assets/6376882/19019087/e0ec937a-8881-11e6-9d98-803f27ed793d.png)

**Comment by eteran** [comment]
that looks good to me, i'll push something that uses that in just a bit. Seems that the HiDPI makes things roughly twice the size for you.

**Comment by eteran** [comment]
should be fixed now

**Comment by 10110111** [comment]
For the future, when EDB completely switches to Qt5, there's a way to have a checkbox in `QMessageBox` (since Qt 5.2).

**Comment by eteran** [comment]
Oh nice, good to know. I suppose it's worth trying to gauge what most users are using and see how worthy it is to try to stay compatible with Qt4.

**Comment by 10110111** [comment]
I guess Qt4 should remain until at least Kubuntu 14.04 support is dropped, since there KDE4 is the DE, and Qt5 isn't in default repos (AFAIR, or it is of very early version).
