### ISSUE TITLE
Problems to debug i386 files in amd64 system

### ISSUE THREAD

**Issue by AlmuHS** [eteran/edb-debugger#462]
Hello, I want to comment a problem what I have in my Debian system

I'm trying to debug 8086 assembly program in my Debian amd64 system
I got assemble and link it with that commands:

nasm -f elf32 file1.asm
ld -mi386 -s -o file1 file1.o

But, when I try to debug it with edb, it shows a error

"Failed to open and attach to process:
First event after waitpid() should be a STOP of type SIGTRAP, but wasn't, instead status=0xb7f."

How can I solve this?

**Comment by AlmuHS** [comment]
my code is this:

`section .text
	global _start
	cpu 8086
_start:
        ;Aqui va el codigo
	
	;como sólo hay un segmento de datos, y el de código no se puede modificar (por cuestiones de seguridad)
	;en general serán innecesarios los prefijos de segmento en los direccionamientos	
	SUB AX, B
	SUB AX, C
	
	;terminar la ejecución (AX=1)
	MOV AX,1
	INT 80h

section .data align=16
	;Aqui los datos inicializados
	A DW 500
	B DW 400
	C DW 100
`

**Comment by AlmuHS** [comment]
section .text
	global _start
	cpu 8086
_start:
        ;Aqui va el codigo
	
	;como sólo hay un segmento de datos, y el de código no se puede modificar (por cuestiones de seguridad)
	;en general serán innecesarios los prefijos de segmento en los direccionamientos	
	SUB AX, B
	SUB AX, C
	
	;terminar la ejecución (AX=1)
	MOV AX,1
	INT 80h

section .data align=16
	;Aqui los datos inicializados
	A DW 500
	B DW 400
	C DW 100

**Comment by 10110111** [comment]
Does it even run without a debugger? 8086 as ELF32 looks like a contradiction.

**Comment by AlmuHS** [comment]
I want to use 8086 assembly
In the examples I've read they use elf32, but I don't know if other format could be better than this

I tried to assemble with as86 format, but ld don't recognize this, and I don't know which I can use

**Comment by 10110111** [comment]
You can't directly run 16-bit code in 32/64-bit x86 Linux. You must either use a virtual machine, or set up a 16-bit code descriptor manually, as e.g. Wine does it.

**Comment by AlmuHS** [comment]
But I need to "compile" assembly code to a binary file for run it

How can I "compile" this in Linux?

**Comment by AlmuHS** [comment]
Ok, I understand it 
Do I need to use DOSBOX mandatorily to test my programs?
Don't exist any form to debug 8086 code from Linux?

**Comment by 10110111** [comment]
If you just want to run 16-bit code without needing to manually set up environment for it, use DOSBox or Bochs. The former is just a DOS emulator, from which you can run e.g. Turbo Debugger. The latter can allow you to also debug it from its integrated debugger.

**Comment by AlmuHS** [comment]
Ok
I'm trying to port TASM code to NASM, and I'm having problems like this
I go to try migrate code to 386 assembly, and if I continue having problems, then try your solution

Thanks for your help

**Comment by AlmuHS** [comment]
Finnaly, after change flag from cpu 8086 to cpu 386, the code assemble and debug without problems

nasm -f elf32 file.asm
ld -melf_i386 -o file file.o
