### ISSUE TITLE
Add jump destination line-drawing to disassembly view

### ISSUE THREAD

**Issue by AaronOpfer** [eteran/edb-debugger#464]
It's probably easiest to explain with this screenshot of ollydbg, my old time favorite.Notice the red line visible on this page:

http://www.ollydbg.de/Pics/OllyDbg2.gif

When the jump instruction is highlighted, the destination of the jump is drawn in the disassembly view with a connecting line. Without this feature, it is very difficult to find my way around a lot of conditional code in edb.

**Comment by 10110111** [comment]
This is a good point. But then, EDB should then integrate this with Analyzer which would highlight the arrow differently when the branch is taken vs when it isn't.

**Comment by eteran** [comment]
This has been implemented for a while now :-)
