### ISSUE TITLE
If debuggee is 32-bit, Stack window should automatically set word-width to 4 bytes

### ISSUE THREAD

**Issue by AaronOpfer** [eteran/edb-debugger#465]
I was confused why I didn't see return addresses in the stack window until I realized it was assuming an 8 byte stack. Once I told it to use 4 byte words, the stack window started to make sense.

The stack window should automatically change its word-size based on the debuggee's word-size (In fact, I would argue it probably should not be user-adjustable to prevent user confusion, that's what the memory dump window is for).

**Comment by eteran** [comment]
Hmm, it does try to do this (if the value is the default `-1` in the config file). But if you have manually set it before, it will remember that value. We should make some sort of UI feature to handle this in a more obvious fashion.

**Comment by eteran** [comment]
You may be right that perhaps the stack view should simply not have this feature. That's probably the simplest fix (and actually is a patch that mostly removes code).
