### ISSUE TITLE
UX improvements to Goto Dialog

### ISSUE THREAD

**Issue by AaronOpfer** [eteran/edb-debugger#466]
I'd like to propose some nice-to-have improvements to the "Goto Address" feature:

 * Instead of displaying a new pop-up box when an invalid address is entered and then forcing the user to click OK and press Ctrl+G again, disable the OK box and display some red error text explaining what is happening in the original window. This gives the user a chance to fix their mistake.
 * I frequently copy and paste addresses from a text editor when I navigate around edb. It would be nice if my clipboard text contents would automatically appear in edb's address box as *selected text*, so that if I wanted to paste the contents I only have to press enter, but if I didn't, I simply just start typing like I normally would before and the clipboard contents are replaced.
 * If an expression is decided to be invalid, check that it satisfies the regex expression ^[0-9a-fA-F]*$. If it does, then it is probably a hex address and we should not require the user to put 0x in front of it.

**Comment by 10110111** [comment]
+1 for first two. For example of behavior in bullet 1 one can look at OllyDbg, where it's done almost everywhere (the aim of OllyDbg was to remove distractions as much as possible). For bullet 2 the behavior can be seen in e.g. KTorrent's "Open URL" menu.

But for bullet 3, can't such a text conflict with anything? Maybe some symbol?..

**Comment by AaronOpfer** [comment]
It looks like the current Goto dialog is made out of a QInputDialog, and since we're replacing a lot of its behavior I think we need to make our own QDialog subclass. I hacked up source tree to make this mockup:

![image](https://cloud.githubusercontent.com/assets/1189089/20371348/b73de684-ac29-11e6-9952-99fc58a99dc3.png)

Assuming I can pass code review (my C++ is awful), is this something upstream development would want to see finished?

**Comment by eteran** [comment]
I can say that I don't really love the idea of acceping non 0x prefixed hex addresses. But generally agree with your other points. Because, if they enter "1234" is that decimal or hex? EDB currently allows decimal values.

**Comment by AaronOpfer** [comment]
Okay, I think I'm going to concede points 2 and 3. Although 3 (accept hex-ish addrs) is the way Ollydbg works, edb doesn't necessarily need to be a faithful reproduction of it, and it might be too late to switch to "hex everywhere by default" for the people used to edb today. And 2  (copy&paste) is not as good as a feature as keeping a log of the recent goto addresses and letting the user pick from those (another ollydbg feature) so I don't want to introduce a feature that we'd replace later as that would irritate people.

My current pull request takes that into account and so only addresses point 1.
