### ISSUE TITLE
main() heuristic seems incorrect/incomplete

### ISSUE THREAD

**Issue by AaronOpfer** [eteran/edb-debugger#473]
The ELF64 `main`-finding heuristic scans bytes past the entrypoint and looks for this signature:

```
// beginning of a call preceeded by a 64-bit mov and followed by a hlt
if(ba[0] == 0x48 && ba[1] == 0xc7 && ba[7] == 0xe8 && ba[12] == 0xf4)
```

However, I compiled this test program with `gcc test2.c -o test2`:
```C++
#include <stdio.h>

int main(int argc, char* argv[]) {
    printf("Hello, %s", "World");
}
```

and my entrypoint looks like this (main() is at 0x5555555546b0):

![image](https://cloud.githubusercontent.com/assets/1189089/20471065/ffbdfaa0-af73-11e6-96e0-55dea06b809f.png)

 * the `lea rdi, [rel 0x5555555546b0]` instruction before the call is `48 8d` but the heuristic is looking for `48 c7` (which doesn't even appear to be a valid opcode)
 * the `call qword [rel 0x555555754fd8]` is `ff 15` but the heuristic is looking for `e8` (which is "call <32bit immed>")

The heuristic like it may have worked at some point. Maybe this is a libc change?

GCC info
```
$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/6/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Debian 6.2.0-13' --with-bugurl=file:///usr/share/doc/gcc-6/README.Bugs --enable-languages=c,ada,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-6 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-6-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-6-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-6-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 6.2.0 20161109 (Debian 6.2.0-13)'
```

**Comment by 10110111** [comment]
`48 c7` is first two bytes of `48 c7 c7 imm32`, which is `mov rdi, imm32`. It works when `main` address fits in 32 bits. In your case the compiler uses `lea` to get absolute address from relative offset. Might be due to a change in GCC or special compilation options you used.

Here's what the heuristic is looking for:

![screenshot - 211116 - 09 15 58](https://cloud.githubusercontent.com/assets/6376882/20472498/448006fe-afcb-11e6-8f1c-a123a45f80bc.png)

**Comment by AaronOpfer** [comment]
I didn't force the address, it's just some ASLR I think. Above see that I am not using any special compiler flags `gcc test2.c -o test2`. (also see version: `gcc version 6.2.0 20161109 (Debian 6.2.0-13)`)

**Comment by 10110111** [comment]
Could you check with older gcc if possible? My screenshot results from GCC 5.3.0.

**Comment by AaronOpfer** [comment]
So I'm going to talk about my pull request #472 here because it's also relevant to this thread.

First of all, gcc6 compiles the program as a shared object instead of an executable:
```
$ file test2 # gcc6
test2: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.32, BuildID[sha1]=d3cbde1db6e9044e8b9892dca3723c7ea6f162ca, not stripped
$ file test2.5 # gcc5
test2.5: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.32, BuildID[sha1]=abe8d5ab020ec7c45fb1951e96e8452fe53a8777, not stripped
```
Secondly, it looks like gcc6 has chosen a base module address of 0 for my executable (forcing it to be relocated):

```
$ readelf -l test2

Elf file type is DYN (Shared object file)
Entry point 0x580
There are 9 program headers, starting at offset 64

Program Headers:
  Type           Offset             VirtAddr           PhysAddr
                 FileSiz            MemSiz              Flags  Align
  PHDR           0x0000000000000040 0x0000000000000040 0x0000000000000040
                 0x00000000000001f8 0x00000000000001f8  R E    8
  INTERP         0x0000000000000238 0x0000000000000238 0x0000000000000238
                 0x000000000000001c 0x000000000000001c  R      1
      [Requesting program interpreter: /lib64/ld-linux-x86-64.so.2]
  LOAD           0x0000000000000000 0x0000000000000000 0x0000000000000000
                 0x00000000000008e4 0x00000000000008e4  R E    200000
  LOAD           0x0000000000000dd8 0x0000000000200dd8 0x0000000000200dd8
                 0x0000000000000258 0x0000000000000260  RW     200000
  DYNAMIC        0x0000000000000df0 0x0000000000200df0 0x0000000000200df0
                 0x00000000000001e0 0x00000000000001e0  RW     8
  NOTE           0x0000000000000254 0x0000000000000254 0x0000000000000254
                 0x0000000000000044 0x0000000000000044  R      4
  GNU_EH_FRAME   0x00000000000007b4 0x00000000000007b4 0x00000000000007b4
                 0x0000000000000034 0x0000000000000034  R      4
  GNU_STACK      0x0000000000000000 0x0000000000000000 0x0000000000000000
                 0x0000000000000000 0x0000000000000000  RW     10
  GNU_RELRO      0x0000000000000dd8 0x0000000000200dd8 0x0000000000200dd8
                 0x0000000000000228 0x0000000000000228  R      1

 Section to Segment mapping:
  Segment Sections...
   00     
   01     .interp 
   02     .interp .note.ABI-tag .note.gnu.build-id .gnu.hash .dynsym .dynstr .gnu.version .gnu.version_r .rela.dyn .rela.plt .init .plt .plt.got .text .fini .rodata .eh_frame_hdr .eh_frame 
   03     .init_array .fini_array .jcr .dynamic .got .got.plt .data .bss 
   04     .dynamic 
   05     .note.ABI-tag .note.gnu.build-id 
   06     .eh_frame_hdr 
   07     
   08     .init_array .fini_array .jcr .dynamic .got 
```
I'm guessing gcc has a compiler flag of some kind that allows it to avoid creating a relocation table in the binary by using RIP-relative addresses, and gcc6 must have it on by default. So I think what we're seeing is a version of the entrypoint that is relative addressed instead of statically addressed (and fixed up by relocation table if necessary).

As an aside, this makes my pull request wrong: The bug isn't that we don't have the base address of the module added to the entrypoint, it's that we don't correctly handle when the binary we're debugging has been relocated and try to put the breakpoint on the executable's original address.

**Comment by 10110111** [comment]
[Here's](https://bugs.launchpad.net/ubuntu/+source/gcc-defaults/+bug/1635706) a related discussion on Launchpad. It appears that on Ubuntu 14.04 with gcc 6.2.0-3ubuntu11~14.04 I get normal executable, while in the above mentioned bug report against Ubuntu 16.10 with gcc 6.2.0-5ubuntu12 it seems to emit a shared object.

**Comment by 10110111** [comment]
So, I do reproduce this result when compiling with `gcc -pie` in both GCC versions 5 and 6.

**Comment by 10110111** [comment]
> I didn't force the address, it's just some ASLR I think.

OK, I reproduce these addresses when I disable ASLR. I had it enabled in EDB options.

**Comment by eteran** [comment]
Could this possibly be related to #59 in any way? I noticed that forever ago and just wrote it off as a prelink thing.

**Comment by AaronOpfer** [comment]
I think I've derailed our discussion away the original issue. I have another pull request about the ELF entrypoint/relocation issue coming and we can discuss it there.
