### ISSUE TITLE
Register "badges" in the disassembly view.

### ISSUE THREAD

**Issue by eteran** [eteran/edb-debugger#486]
If we look at x86dbg, it has a nice (and simple) feature that I think edb would benefit from having too in some form:

![x86dbg](http://x64dbg.com/img/slide3.png)

If we look at the left side of the interface here, there is a visual notation that `RDX` happens to point to that location.  I would like us to have something similar, but am imagining something slightly more compact. Something like this (rough mock up)

![register_tag](https://cloud.githubusercontent.com/assets/571477/20821205/afb350ca-b80e-11e6-81b0-b5e70095580f.png)

That would optionally go immediately to the left of where the addresses are displayed.

**Comment by AaronOpfer** [comment]
Where should we position them? We could render them overlaying the most significant digits of the address and not lose much visual information (since the significant digits are repeated above and below the address). Or we could add some blank space to the left of the address field for this purpose.

**Comment by eteran** [comment]
I am imagining thrm going in some extra space to the left of the breakpoints

**Comment by AaronOpfer** [comment]
I saw that there's a RegisterViewModelBase class but I'm not very familiar with Qt's modeling features. It looks very concerned about presentation layer which might make it inappropriate for directly interacting with it.

**Comment by eteran** [comment]
Actually, if you get an instance of an `IState` object, it has a `gp_register(size_t n)` method which should get a register by index.

**Comment by AaronOpfer** [comment]
Oh, I didn't see that `Register::name()` existed. Maybe this won't be so bad.
