### ISSUE TITLE
Analysis is very slow

### ISSUE THREAD

**Issue by AaronOpfer** [eteran/edb-debugger#488]
I ran `./edb --run edb` and then went to the address of `mprotect` in `libc-2.24.so`.

```
[Analyzer] complete
[Analyzer] elapsed: 170931 ms
```
2.5 minutes to analyze seems like a very long time to me. Also scrolling up and down in the disassembly view is noticeably slower after analysis is complete.

**Comment by eteran** [comment]
Sure, I'm always in favor of performance improvements :+1:
