### ISSUE TITLE
jump indicators and analysis brackets aren't clipped properly

### ISSUE THREAD

**Issue by eteran** [eteran/edb-debugger#494]
When `line2()` is right up against `line3()`, the text that goes between seems reasonably clipped. But the brackets of functions and jump direction indicators aren't clipped at all.

@AaronOpfer since you've been working on the display code quite a lot, care to take a look?

![screenshot_20161206_003036](https://cloud.githubusercontent.com/assets/571477/20914127/41c2fe5e-bb4b-11e6-826a-4d44ccb1bda2.png)

**Comment by AaronOpfer** [comment]
Sure, I can look at this.
