### ISSUE TITLE
Warning about 64-bit process on 32-bit EDB has vanished

### ISSUE THREAD

**Issue by 10110111** [eteran/edb-debugger#498]
After some recent changes the usual warning about running a 64-bit debuggee on a 32-bit EDB build has vanished. Is it by design? Currently EDB doesn't fully support such a configuration, so I think it's better to have this warning.

**Comment by eteran** [comment]
Agreed, it must have been lost during the recent PR that got merged. Since this is a configuration that I basically never use personally, it went unnoticed.

**Comment by eteran** [comment]
So, the code for this **looks** intact.

Debugger.cpp does this (as expected):

	void Debugger::test_native_binary() {
		if(EDB_IS_32_BIT && binary_info_ && !binary_info_->native()) {
			QMessageBox::warning(
				this,
				tr("Not A Native Binary"),
				tr("The program you just attached to was built for a different architecture than the one that edb was built for. "
				"For example a AMD64 binary on EDB built for IA32. "
				"This is not fully supported yet, so you may need to use a version of edb that was compiled for the same architecture as your target program")
				);
		}
	}

And BinaryInfo::ELF32/64.cpp does this:

	template<>
	bool ELF32::native() const {
		return edb::v1::debugger_core->cpu_type() == edb::string_hash("x86");
	}

	template<>
	bool ELF64::native() const {
		return edb::v1::debugger_core->cpu_type() == edb::string_hash("x86-64");
	}

Which all looks like it does the right thing:

Unfortunately, I don't exactly have things setup to try to replicate this issue. Are you on a 64-bit machine, and compiling a 32-bit edb? If so, what's the best way to coerce our cmake scripts to emit a 32-bit build? I can manually tweak the CXXFLAGS and such... but is there a better way that you are doing that?

**Comment by 10110111** [comment]
I'm on 32-bit userspace and 64-bit kernel. A bit unusual configuration, yes. You might succeed if you just set `CMAKE_CXX_FLAGS` and `CMAKE_*_LINKER_FLAGS` to `-m32`.

Looks like I'll have to debug this myself though...

**Comment by eteran** [comment]
@10110111  If you could that would be very helpful. I tried using `-m32` but immediately ran into issues where libraries like capstone would also need to be compiled for 32-bit and at that point it seemed easier to reach out to you :-).

**Comment by 10110111** [comment]
Hm, latest pull doesn't reproduce this problem. Seems fixed.

**Comment by eteran** [comment]
Great to hear, must have been a temporary breakage
