### ISSUE TITLE
Debian compile page doesn't mention libgraphviz-dev

### ISSUE THREAD

**Issue by AaronOpfer** [eteran/edb-debugger#506]
This wiki page doesn't mention libgraphviz-dev anywhere, which is required for compiling the optional graph features.

https://github.com/eteran/edb-debugger/wiki/Compiling-(Ubuntu-Debian)

It *does* mention libgvc6 but since this is a dependency of libgraphviz-dev it probably makes more sense to explicitly install the latter instead.

**Comment by eteran** [comment]
Updated. Thanks!
