### ISSUE TITLE
Make default build mode RelWithDebInfo ?

### ISSUE THREAD

**Issue by eteran** [eteran/edb-debugger#509]
By default, cmake will emit a Makefile that doesn't specify any particular optimization flags. While gcc does a decent job by default, C++ it notorious for having huge gains from enabling optimizations.

Since we want users to get the best possible build "out of the box", I propose making `RelWithDebInfo` the build type you get if you don't manually specify.

Anyone see any reason not to do this?

**Comment by 10110111** [comment]
Sounds good to me.
