### ISSUE TITLE
QDisassemblyView acts weird at region boundaries

### ISSUE THREAD

**Issue by eteran** [eteran/edb-debugger#520]
So it's a bit hard to describe. But basically if you scroll way to the end of a region. Eventually you get the point where the region ends. But the disassembly view still renders whatever bytes it can get beyond the region's end.

Basically it goes like this:

If you scroll to the max you can, you end up with the last valid address of the region as the top line. And some junk rendered for all subsequent lines. The junk addresses do not properly interact with mouse selection, and the data/disassembly doesn't quite update when you scroll around rapidly.

I see two potential solutions:

1. make the max scroll = region size - number of visible lines so the end of the region is always at the bottom of a max scroll. But this may act weird during resizes

2. Make it render nothing below the last address resulting in a mostly blank viewport when maximally scrolled.

@AaronOpfer can you please look into this. Let me know if you need any more information.

**Comment by AaronOpfer** [comment]
We actually try to render bytes past the end of the region and kind of "overflow" up to `instruction_bytes_.size()` (which is bigger than necessary), picking up leftover bytes from previous renders. Pretty easy to fix that. It's still possible to have a mostly empty viewport, though.
