### ISSUE TITLE
Data dump view should show address contents (like Stack view)

### ISSUE THREAD

**Issue by AaronOpfer** [eteran/edb-debugger#522]
SImilar to the stack view, when the data dump is 1-word wide and word size == pointer size (like how the stack is hardcoded right now), if a value in the dump points to readable memory that contains a ASCII/UTF16 string, that string should appear next to it in the dump.

This would be very useful for analyzing vtables and similar function pointer structures in the data dump screen.

**Comment by eteran** [comment]
It's a rare configuration, but sure it certainly can't hurt.
