### ISSUE TITLE
Implement internal breakpoint for capturing library load events

### ISSUE THREAD

**Issue by eteran** [eteran/edb-debugger#524]
The ld linker allows the capture of library load events by calling a do nothing function at library load time.  By placing an internal breakpoint on this address, we can "hook" this event.

Some of the work has already been done, but we should finish it up and take advantage of it to reload breakpoints and similar.

**Comment by eteran** [comment]
Implemented! (linux only for now)

`Debugger::next_debug_event()` now places an internal BP hook based on the debug information it can read from the ELF binary. Then
`Debugger::handle_trap()` tests if the BP it just hit was that internal BP.

For now, does some tests and then unconditionally tells the debugger to just continue. But in the future
we can allow the user to trap on load events, we can restore BPs in newly loaded libs, etc...

I do need to figure out if there is an efficient way to know WHICH library is being loaded.
We can scan the previous / current memory map and compare, but that seems inefficient.

**Comment by AaronOpfer** [comment]
That's pretty cool. Do we log anything when this happens about what library was loaded? Seems like it would be a good time to generate symbols as well.

**Comment by eteran** [comment]
We don't do anything in particular yet, just got the plumbing in there so that we can add a lot of  the cool features we've been wanting.
