### ISSUE TITLE
Debugger UI doesn't emit detachEvent if closed

### ISSUE THREAD

**Issue by AaronOpfer** [eteran/edb-debugger#528]
If the user closes the main GUI window either by using Alt+X or by clicking the close button (or however your DE does it), detachEvent does not fire.

I determined this while working on #478 ; I just added slots to Analyzer that are connected to the detachEvent signal. When using kill or restart from the "Debug" menu the event fires, but it does not fire when closing as described above. Not sure if the event never fires or if it has something to do with the plugin being unloaded before the event fires.

**Comment by eteran** [comment]
I think this should be an easy fix. We can just add something to explicitly deal with this during the `Debugger::closeEvent`

**Comment by eteran** [comment]
Hmm, it seems that somewhere along the lines the "CloseBehavior" code was a bit NERFed... I'll have to look into this.

**Comment by eteran** [comment]
Wait, I take it back, it's in there in the Debugger destructor... hrmm.

**Comment by eteran** [comment]
OK, did a push that I think will address this. But honestly, this may not be the best thing to hook as it is pretty late in the "shutdown" process. 

Looking at the code for for the detach event, it is used in one spot, and that's for clearing the UI in the thread view. So clearly this event was originally intended to mean "user clicked detach, but UI is still up" kinda thing when I first wrote it.

Might be better to hook the `MainWindow::CloseEvent`, but this may "just work" Let me know.

**Comment by AaronOpfer** [comment]
looks like that may have fixed it.
