### ISSUE TITLE
edb doesn't clean up from ptrace attach failure correctly

### ISSUE THREAD

**Issue by AaronOpfer** [eteran/edb-debugger#531]
Just observed this today on accident:

 * attempt to attach to a process that is already being debugged by another debugger process
 * observe that it fails (as expected)
 * Detach the other debugger and attempt to attach edb to the same process again

Instead of succesfully attaching, edb says "You are already debugging that process!"

**Comment by eteran** [comment]
I was able to reproduce the issue, looking into it.
