### ISSUE TITLE
Setting hardware breakpoints while process is running silently fails

### ISSUE THREAD

**Issue by AaronOpfer** [eteran/edb-debugger#532]
Attempting to set a hardware breakpoint (via the dump context menu or the hw bp manager plugin) while the process is running (i.e. not paused) fails silently and the breakpoint is not set.

Accessing the hardware breakpoint manager while the process is running will claim there are no hardware breakpoints set even if there are.

I believe this should be fixed by pausing the process, performing the operation and then immediately resuming the process for the user automatically.

**Comment by AaronOpfer** [comment]
As an aside, how does the hardware breakpoint system handle multiple threads in the child process and the fact that each thread can have its own set of HW BPs?

**Comment by eteran** [comment]
Yea, definitely should fix this. I suspect it won't be crazy hard to do correctly.

I think we loop through all threads and set the same ones for all of them. I don't recall if this is done to any new threads though.
