### ISSUE TITLE
Add feature to copy selected dump contents to clipboard

### ISSUE THREAD

**Issue by AaronOpfer** [eteran/edb-debugger#538]
It would be useful when analyzing data structures to be able to copy selected dump contents to the clipboard. This would make it easier to plug different dumps into diff tools, put data structures into documents, etc..

**Comment by eteran** [comment]
Are you looking for something different than the right click "Copy Selection To Clipboard"? WAY back when I was first making edb, it used to put the raw binary data itself in clipboard. But that seemed less useful for a C&P operation.

**Comment by AaronOpfer** [comment]
Uhh, it looks like I'm blind :-). That's exactly what I was looking for.
