### ISSUE TITLE
Error Compiling

### ISSUE THREAD

**Issue by peylight** [eteran/edb-debugger#539]
Hello
I have Debian 9.0 x64
I try to compile but i seen error.

`
[  1%] Built target edb_automoc
[  1%] Generating qrc_debugger.cpp
Scanning dependencies of target edb
[  1%] Building CXX object src/CMakeFiles/edb.dir/BasicBlock.cpp.o
[  1%] Building CXX object src/CMakeFiles/edb.dir/BinaryString.cpp.o
[  2%] Building CXX object src/CMakeFiles/edb.dir/ByteShiftArray.cpp.o
[  2%] Building CXX object src/CMakeFiles/edb.dir/capstone-edb/Instruction.cpp.o
[  3%] Building CXX object src/CMakeFiles/edb.dir/CommentServer.cpp.o
[  3%] Building CXX object src/CMakeFiles/edb.dir/Configuration.cpp.o
[  4%] Building CXX object src/CMakeFiles/edb.dir/DataViewInfo.cpp.o
[  4%] Building CXX object src/CMakeFiles/edb.dir/Debugger.cpp.o
/home/peylight/apps/edb-debugger/include/os/unix/linux/linker.h:24:11: error: expected identifier before numeric constant
 namespace linux {
           ^
/home/peylight/apps/edb-debugger/include/os/unix/linux/linker.h:24:11: error: expected unqualified-id before numeric constant
/home/peylight/apps/edb-debugger/src/Debugger.cpp:3535:1: error: expected ‘}’ at end of input
 }
 ^
src/CMakeFiles/edb.dir/build.make:308: recipe for target 'src/CMakeFiles/edb.dir/Debugger.cpp.o' failed
make[2]: *** [src/CMakeFiles/edb.dir/Debugger.cpp.o] Error 1
CMakeFiles/Makefile2:86: recipe for target 'src/CMakeFiles/edb.dir/all' failed
make[1]: *** [src/CMakeFiles/edb.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
`
complete error :  https://0bin.asis.io/paste/1NucDaHZ#ahPxLXxsxweQNFH+qKs6AJsrPmlamkHEZCnLNwk7ER4

**Comment by 10110111** [comment]
For some reason your compiler seems to be adding [the `linux` define](http://stackoverflow.com/q/19210935/673852). It seems it shouldn't, since EDB uses `-std=c++11` option.

**Comment by peylight** [comment]
@10110111 
$ g++ --version
g++ (Debian 6.3.0-6) 6.3.0 20170205                                                                                                                                                                  
Copyright (C) 2016 Free Software Foundation, Inc.                                                                                                                                                    
This is free software; see the source for copying conditions.  There is NO                                                                                                                           
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by 10110111** [comment]
That's strange. See [this test of `-std=c++11` with g++ 6.3](https://godbolt.org/g/JEYjWr). Could you post a full output of `make VERBOSE=1`?

**Comment by peylight** [comment]
@10110111 
Yes, its [HERE](https://0bin.asis.io/paste/z6TuPIBp#gFX8RUzpeiTFskYqO3CiZgsxVBlHMVLBbjK3plIdZl8)

**Comment by 10110111** [comment]
What do these commands say:
````
/usr/bin/c++ --version
/usr/bin/c++ -dM -E -x c++ - < /dev/null|grep '\<linux\>' || echo nothing
/usr/bin/c++ -dM -E -std=c++11 -x c++ - < /dev/null|grep '\<linux\>' || echo nothing
````
?

**Comment by peylight** [comment]
@10110111 
$ /usr/bin/c++ --version
```
c++ (Debian 6.3.0-6) 6.3.0 20170205
Copyright (C) 2016 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

```
$ /usr/bin/c++ -dM -E -x c++ - < /dev/null|grep '\<linux\>' || echo nothing
`#define linux 1`
$ /usr/bin/c++ -dM -E -std=c++11 -x c++ - < /dev/null|grep '\<linux\>' || echo nothing
`nothing`

**Comment by 10110111** [comment]
OK, I see what's wrong. You have `-std=gnu++11` after EDB's `-std=c++11`. Seems there's double configuration of C++11 in CMakeLists.txt, one of which is not pedantic standard mode...

**Comment by 10110111** [comment]
What if you add `-DCMAKE_CXX_FLAGS=-std=c++11` option to `cmake`? Does it make it work for you?

**Comment by 10110111** [comment]
@eteran
I think this is the culprit:

```
if( CMAKE_MAJOR_VERSION>3 OR ( CMAKE_MAJOR_VERSION==3 AND CMAKE_MINOR_VERSION>=1))
    set(CMAKE_CXX_STANDARD 11)
```

inside `cmake/EnableCXX11.cmake`.

@peylight Could you check that removing this branch from the script fixes the build for you? I.e. transforming `cmake/EnableCXX11.cmake` to this:
```
include(CheckCXXCompilerFlag)
check_cxx_compiler_flag("-std=c++11" COMPILER_SUPPORTS_CXX11)
if(COMPILER_SUPPORTS_CXX11)
    add_definitions("-std=c++11")
else()
    message( FATAL_ERROR "The compiler doesn't support -std=c++11 option. EDB requires a compiler which supports C++11. If you use gcc, please upgrade. For gcc-incompatible compiler please use cmake 3.1 or higher to get it to work." )
endif()
```

**Comment by peylight** [comment]
I add `-DCMAKE_CXX_FLAGS=-std=c++11` option to `cmake` by $ `cmake -DCMAKE_CXX_FLAGS=-std=c++11 ..` command, but it's have the same problem yet.
Also changing `cmake/EnableCXX11.cmake` to that, have no any change to make error or anything.

**Comment by 10110111** [comment]
Hmm, might be that Qt5 dependencies add this. Well, anyway, I think this should work around the problem for you: use `-DCMAKE_CXX_FLAGS=-Ulinux`.

**Comment by peylight** [comment]
It's work!
Thanks

**Comment by antekone** [comment]
Had the same issue, the `-Ulinux` workaround worked for me, thanks.

**Comment by eteran** [comment]
Hmm, I'm glad we have a workaround, but would obviously like to find a more fundamental solution. Leaving this open for the time being.

**Comment by Reuben-Thorpe** [comment]
Another confirmation, `-Ulinux` worked for me too, thanks guys.

**Comment by eteran** [comment]
Decided to just not use a namespace named `linux`, changing it to `linux_struct` avoids collision with this macro.
