### ISSUE TITLE
a bug of improt breakpoints

### ISSUE THREAD

**Issue by Chhui** [eteran/edb-debugger#540]
When open the plugins menu plugins->BreakpointManager->Breakpoints, after click Import Breakpoints button, the program will crash and haven't any response. I studied the source code of BreakpointManager and try to fix this bug. I find the problem maybe in DialogBreakpoints.cpp file. The bug is in line 252 of DialogBreakpoints.cpp file as follow:
	int count = 0;
	Q_FOREVER {

		//Get the address
		QString line = file.readLine();

		if(line.isNull()) {
			break;
		}
  I change the code "if(line.isNull())" as " if(line.isEmpty())", then it can be compiled successfully and the executable program EDB can work normally.  My Environments for EDB is: 
  OS: RHEL linux 7.3
  QT: QT-opensource-5.4.1
  Boost: v1.5.3 
  capstone: 3.0.4

**Comment by eteran** [comment]
Fixed! Thanks for finding this :-)
