### ISSUE TITLE
Any plans on a new release?

### ISSUE THREAD

**Issue by Petross404** [eteran/edb-debugger#542]
Hi guys, it's been a while since we last made the gentoo ebuild. Well I was curious are there any plans for some new release in the near future?

**Comment by AaronOpfer** [comment]
It would also be nice to have a release cut for debian systems as well.

**Comment by Petross404** [comment]
Like distibuting a .deb file from here?

**Comment by eteran** [comment]
Yes, dev has slowed recently, but not halted. A lot of work has been done since the last release so it is probably a good time for another.

**Comment by eteran** [comment]
@Petross404 I just wanted to give an update. It's been a bit since, but I think that it will likely be time for a new release sometime soon. A lot of good work has been done since the last one, and I've been able to cross off several issues in the past few days (and would like to keep the momentum going).

So I will definitely keep you posted about when the next release is coming.

**Comment by Petross404** [comment]
The thing is that after 17 - 5 I won't be able to update it as I will join the army for a few months. Maybe in the middle of June, I will be able to come back, see my emails and generally do stuff for the community and then again after a few more months.

Of course I am just informing you - not putting pressure on you to rush something. Maybe someone else will update the ebuild in the portage for me.

**Comment by Petross404** [comment]
Any news on this? :)

**Comment by eteran** [comment]
Ha, it has been a while since this was last discussed. I'd like to do a release soon. I think that we'll call it 1.0.0, not because we've reached a milestone, but because edb is in a fairly stable state and this point. And I'd like to move forward with #565 (dropping Qt4 support).

**Comment by Petross404** [comment]
Great news :+1:

**Comment by eteran** [comment]
I have some travel coming up soon. My plan is to tag for 1.0.0 around May 2nd or 3rd which is shortly after I'll be getting back.

**Comment by Petross404** [comment]
We will be in touch, thank you. ☺

**Comment by eteran** [comment]
1.0.0 has been released! Moving forward I plan to cut Qt4 support and switch C++14 as the base standard we target :-).

**Comment by 10110111** [comment]
C++14 is great news :)

**Comment by Petross404** [comment]
Great, I am looking forward to bump the ebuild. Is anything in the build system or something different since the last version? Anyway I will test it, thanks for all the work!
