### ISSUE TITLE
edb kali can't find starting point (function main from file)

### ISSUE THREAD

**Issue by Fare9** [eteran/edb-debugger#548]
Hi, 

I'm using the edb-debugger that comes with Kali, and I updated to Kali v2. After compile a file with GCC version 6.3.0-12, I can see that main function start at address 0x0000... (in 32 bits), but some months ago with GCC version 4.9.2-10 main function started at address 0x8040... (same 32 bits). When I use edb-debugger with new executables (GCC 6.3.0-12) heuristic can't find starting point main function.
Do you know if new edb fix this problem? of didn't you know about this problem?

Thanks for the attention, I hope to fix this problem.

**Comment by eteran** [comment]
@AaronOpfer did some work to improve the heuristic a while back. Please try the latest from git and see if it is solved and let me know if it needs more work or not.

**Comment by Fare9** [comment]
I've tried the last edb debugger in the last Ubuntu edition (17.04), no problems to find the entry point, even I've seen that you have improved the way to show functions names from kali linux's edb version. Congratulations I close this issue, thanks for everyting
