### ISSUE TITLE
Is there A precompiled version of this program?

### ISSUE THREAD

**Issue by ApertureSecurity** [eteran/edb-debugger#562]
Firstly, Thank you for supporting the best Linux compatible debugger!

Secondly, I am looking for a binary version of this package that I can distribute without having to have other users compile this from scratch. Usually this is something I can google and I can download. However, I cannot find anything other than what appears to be your old site for hosting this.

Let me know please if you can help. 

Thank you!

**Comment by arakan94** [comment]
There are deb packages available in Kali: http://http.kali.org/kali/pool/main/e/edb-debugger/ and probably in other distros as well.. But they won't be the latest builds.

**Comment by ApertureSecurity** [comment]
Good day , sorry for getting back to you so late. I usually reply much quicker.  The Deb is nice, but I was hoping for a Zip that I could just have users that use Linux  X64 . I would like to popularize this Debugger in my community. 

If this isn't possible , then  I suppose it will suffice.

**Comment by eteran** [comment]
There isn't a "standalone" binary package that is pre-compiled. I think that this would be interesting to have eventually. So I am going to close this issue as it is a question and not a bug. However, I think that having a  prebuilt binary is something to aim for in future releases.

Thanks.

**Comment by ApertureSecurity** [comment]
I compiled this and put it up. 

http://rootkitdev.com/extras/edb.zip
