### ISSUE TITLE
why depends so libs not load when debug the so with edb-debugger

### ISSUE THREAD

**Issue by unpackerbai** [eteran/edb-debugger#566]

**Comment by eteran** [comment]
@unpackerbai I assume English is not your primary language, I am having a hard time understanding your question :-/

I **think** you are asking why shared libraries (.so files) of a program being debugged by edb aren't loaded? Is that your question?

The answer is that they **ARE** loaded. However, they aren't loaded right away. When you first launch a program, essentially only a version of `ld` (the library) and your program are loaded. And the code starts inside `ld` itself. `ld` then loads the dependent libraries and eventually gives control to the `main` of your program.

It is possible that some libraries are lazy loaded, or loaded at run-time. But for the most common scenarios, dependent libraries should be loaded by the time you reach `main`.

Does this answer your question?

**Comment by unpackerbai** [comment]
yes,i am chinese.
i means that,  a shared library(let's call it A), needed other .so files.  when debugging A, needed .so files not loaded in edb.But I write a .o file, code : dlopen("./A", RTLD_NOW), the needed .so files which A need can be loaded in edb..

**Comment by eteran** [comment]
If your program uses `dlopen`, then the system should load any dependant libraries.

Can you provide a simple example of it not working.

**Comment by unpackerbai** [comment]
ok, how to contact with you?

**Comment by eteran** [comment]
Closing since there hasn't been any follow up for nearly 2 years :-(.
