### ISSUE TITLE
EDB can't find name of __libc_start_main in statically-linked binaries

### ISSUE THREAD

**Issue by 10110111** [eteran/edb-debugger#571]
Here's how to reproduce:
```
gcc -x c -static-libgcc -Wl,-Bstatic -static -o test - <<< $'#include <stdio.h>\nint main(){ printf("Hello!\\n"); return 0; }'
gdb ./test -ex 'b *0' -ex r -ex 'd 1' -ex disas -ex 'set confirm off' -ex q
```
If you look at the disassembly, you'll see the line like
```
   0x080481bc <+28>:    call   0x80482c0 <__libc_start_main>
```
But if you run `edb --run ./test`, you'll see that EDB just says `call 0x80482c0`, and stepping into this function leaves `EIP` comment without function name — only file name.

**Comment by eteran** [comment]
Interesting, not sure why the symbol wouldn't resolve, but I'll look into it. In fact, this example binary segfaults edb for me!

**Comment by 10110111** [comment]
Yeah, I also get segfaults, although not 100% of time.

**Comment by eteran** [comment]
I have a theory... one moment while i test

**Comment by eteran** [comment]
OK, it crashes during symbol creation, resulting in a 0 length cache file (in $HOME/.cache/codef00.com/edb/symbols/...).

If the file exists, even when empty, you probably won't get a crash, but it won't have any symbols either. So the problem is a crash during symbol creation, I'll look into it tonight.

**Comment by eteran** [comment]
using `readelf` on the binaries produced yeilds the following warning:

    readelf: Warning: [ 2]: Link field (0) should index a symtab section.

Based on that, I am assuming that if the link field is `0`, then we should skip that section, and have produced a patch.

**Comment by 10110111** [comment]
This may have fixed the crash, but EDB still doesn't find the function names — neither of `_start` nor of `__libc_start_main` — while GDB finds them without problems.

**Comment by eteran** [comment]
did you try deleting the cached symbol file? If not, it will prevent symbol generation.

**Comment by 10110111** [comment]
Ah, right. That was it. Now `__libc_start_main` does get appear int the view.

But shouldn't `_start`, which is the entry point (and is visible in the address column), appear next to `EIP` in the register view? For me it doesn't. This may be a matter for another issue though.

**Comment by eteran** [comment]
For me, I get: `<test!_start+0>` next to the RIP in the register view.

I have almost made it so 0 length symbol files get auto replaced during symbol file generation.

**Comment by 10110111** [comment]
Do you also get this on a 32-bit system?

**Comment by eteran** [comment]
I haven't tried on a 32-bit system. I'll have to set up a VM to something to check that out.
