### ISSUE TITLE
Disassembly View selection isn't visible on undefined instructions

### ISSUE THREAD

**Issue by 10110111** [eteran/edb-debugger#572]
E.g. if you have bytes like `FF FF` in disassembly view, then trying to click the `db 0xff` lines results in vanishing selection. Same as Ctrl+G → go to the address of these bytes. Moving the selection to valid instructions by the arrow keys does make the selection band appear.

**Comment by eteran** [comment]
Confirmed. Surprised that no one seems to have noticed this before!
