### ISSUE TITLE
Format invalid instructions in a single place

### ISSUE THREAD

**Issue by 10110111** [eteran/edb-debugger#573]
Currently we have `Formatter::to_string()`, return `(bad)` for an invalid instruction, while Disassembly View formats it in its own way, via `QDisassemblyView::format_invalid_instruction_bytes()`. This in particular results in bad look of disassembly when _Tab between mnemonic and operands_ option is checked.

Isn't it better to handle this formatting inside `Formatter::to_string`, letting it take care of the tabs etc.?

**Comment by eteran** [comment]
I see where you're coming from on this, but I can see it two ways.

The other end of the argument is that `Formatter::to_string()` is for formatting instructions, but arguably, an invalid instruction isn't an instruction at all; it's just a set of random bytes.

Either way, we can make the display put a tab there, and we can decide the best "home" for that code at some point.

**Comment by 10110111** [comment]
> but arguably, an invalid instruction isn't an instruction at all; it's just a set of random bytes
And then there are "official invalid instructions" like `ud0`, `ud1`, `ud2`... They are similarly invalid as is `FF FF`, but we do treat them as valid.

**Comment by eteran** [comment]
That's a fair point. But I would say that those actually have proper mnemonics and such... I'm not saying "no", just that there is more than one perspective here :-)

**Comment by eteran** [comment]
Fixed, and the formatting is done by `Formatter::to_string`
