### ISSUE TITLE
Symbolic offset is hexadecimal, but looks like decimal

### ISSUE THREAD

**Issue by 10110111** [eteran/edb-debugger#575]
Currently I see the following next to EIP: `<ld-2.14.1.so!_dl_start+15>`, where the offset is actually 0x15. Similar thing in GDB looks like `<_dl_start+21>`.

Although the register view shows all registers as hex without prefixes, it seems somewhat misleading that offsets are formatted in simple `%x` format (c.f. registers, which have `%08x` or similar formats). This is especially senseless in the analysis view where we have something like
```0xf7fe2175 = 0xf7fe2175 <ld-2.14.1.so!_dl_start+15>```

I think the better options are:

* offsets in decimal
* offsets with `0x` prefixes
* offsets in the format of `%08x`/`%016x`

**Comment by eteran** [comment]
You are right, edb has gotten much better at being consistent with how we display values, but we should cleanup these loose ends.

I think the way I'd like to handle it is:

1. make a preference for "display address offsets in hexdecimal" so the user can select which they prefer.
2. when displaying in hex, there will be a "0x" prefix on it
