### ISSUE TITLE
edb sometimes produces symbols relative to the wrong lib base

### ISSUE THREAD

**Issue by GoogleCodeExporter** [eteran/edb-debugger#59]
sometimes, edb will generate symbol values which don't appear to be relative, yet are for libraries which are loaded with ASLR. Fortunately nothing breaks _terribly_ but some things aren't quite right.

I believe that this is related to prelinking and can reproduce on recent versions of Fedora.

**Comment by eteran** [comment]
I'm closing this. It was opened a LONG time ago, and the symbol management has been reworked significantly. So we'll consider it resolved for now, and if any users report an issue, we can address it.
