### ISSUE TITLE
Assembler-Plugin: "New instruction is too big to fit."

### ISSUE THREAD

**Issue by cmkarner** [eteran/edb-debugger#597]
There's an Error when trying to assemble a instruction using the Assembler-Plugin with "Keep size" enabled:

> "Error in Code: New instruction is too big to fit."

This occurs nearly every time, even if the new instruction should be shorter than the previous one.

**Comment by 10110111** [comment]
Please give an example of code you're trying to modify and the instruction you're trying to assemble, as well as what assembler you're using (this is configurable in Plugin Options→Assembler).

**Comment by cmkarner** [comment]
My bad, of course it's quite obvious that this kind of information is also needed. I used both yasm and nasm, but the result was the same in both cases.

The error occurs, for example, when trying to modify
> jne 0x4009ed
to
> jne 0x4009e1
or
> je 0x4009ed

But it is possible to change the current instruction to NOP.

(Thanks for your quick response!)

**Comment by 10110111** [comment]
Can't seem to reproduce, some more info is needed:
* Current address of the original instruction
* Exact bytes of the instruction (to distinguish encodings like `74 00` vs `0f 84 00 00 00 00`)
* Whether the code is 32-bit or 64-bit (or 16-bit?)
* Whether the OS (and EDB binary) is 32- or 64-bit
* YASM version
Also, what happens if you uncheck "_Keep size_" option? What (and how many) bytes are written in place of the original instruction?

**Comment by cmkarner** [comment]
* Current address of original instruction: 0x00000000004009df
* Bytes: `75 0c`
* Analyzed executable: 64-bit (ELF 64-bit LSB executable, x86-64, version 1 (SYSV))
* EDB executable: 64-bit (ELF 64-bit LSB executable, x86-64, version 1 (GNU/Linux))
* OS: 64-bit Linux
* YASM version: 1.3.0

When replacing `jne 0x4009ed` with `je 0x4009ed` using _Keep size_ unchecked and _Fill rest with NOPs_ checked, the next two instructions (which consist of 10 bytes; 5 each) are changed to:
`00 e8`
`1b ff`

Which is then followed by two more instructions:
`ff`
`ff`

**Comment by eteran** [comment]
This is strange, I don't think that there are any non relative JXX instructions, so I would expect them to he the same size.

Seems we should add more information to the message box to include the set of bytes that it encoded the new instruction to. That would make diagnosis of this simpler

**Comment by 10110111** [comment]
Actually it's not EDB Assembly plugin's bug. It's just that the disassembly doesn't match what YASM would assemble back to the original bytes. In your case, if you need `74 0c` as the resulting instruction, you need to change the disassembled instruction to `je short 0x4009ed`.

**Comment by 10110111** [comment]
Another option is to use FASM instead of YASM: FASM optimizes for size by default, unlike NASM and YASM.

**Comment by cmkarner** [comment]
Thanks for your support and your detailed remarks. Seems as if the issue isn't an issue and can be closed.
