### ISSUE TITLE
Return key doesn't open Register Editor

### ISSUE THREAD

**Issue by 10110111** [eteran/edb-debugger#600]
Due to _Follow_ menu item's shortcut (Return key) in CPU view, Register view doesn't receive Return key press events. The shortcut for the _Follow_ menu item is set via `QAction::setShortcut`. Looks like the `QAction`'s shortcuts are global for all the main window, not only for the focused widget, so I'm not sure how this should be fixed.

**Comment by eteran** [comment]
So, we had a similar "issue" with the "Goto" shortcut if I recall correctly. The solution was relatively simple.

We simply made the global handler test which widget had focus, and would delegate to the appropriate one as needed.

see: `Debugger::goto_triggered()` for relevant code.

**Comment by 10110111** [comment]
Doesn't seem too easy. I've tried this approach, but it results in ugly coupling between handlers of `Key_Return` in main window and register view. Another option I tried, `QAction::setShortcutContext`, appears to require moving logic of _Follow_ item from `Debugger` to `QDisassemblyView`, otherwise it doesn't have any effect (the associated widget is still the main window). Yet another option, simulation of `QKeyEvent` via `QCoreApplication::postEvent`, appears to lead to infinite loop for some reason.

**Comment by eteran** [comment]
So, here's how I think I would handle it (untested)

I would have a global handler like we do, then I would use `qobject_cast` to get which specific widget has the focus, so we know which widget we want to get the event.

If it is one of the primary UI widgets, like the disassembler, data, or stack panes. then we know what to do and perform the action.

For the "unknown" case. We simulate a `keyPressEvent(QKeyEvent *event)` directly for the target widget there is likely a way to avoid infinite loops when doing this. My gut would have been `postEvent`, but I believe that there are other options as well, I will explore a little bit.

**Comment by eteran** [comment]
Should be fixed! Dunno why I didn't do this sooner, I had the right idea :-)
