### ISSUE TITLE
Packages in Linux Distribution repositories

### ISSUE THREAD

**Issue by dkazantzas** [eteran/edb-debugger#602]
Hi all, 
Is there a reason that there aren't any packages of edb-debugger in linux distribution repositories, or is it that none has taken this task?

**Comment by Petross404** [comment]
Well, there is a package for gentoo https://packages.gentoo.org/packages/dev-util/edb-debugger

**Comment by eteran** [comment]
@dkazantzas It really boils down to someone taking the initiative and helping. I would love to create a PPA for edb ( see issue #356 ), but my knowledge in Ubuntu packaging is very limited (I'm a Gentoo guy personally).

We have some scripts which seem to reliably create a working .deb file, but like I said, I'm missing some small bits of info on how PPAs work.

Likewise, it would be great to have a custom fedora repo as well that people could use, but it really is a matter of manpower and insider knowledge on how the different package systems work.

**Comment by mich181189** [comment]
Just to note there is a fedora package - though it's ridiculously out of date - it's called edb

I'm working on seeing if I can update it now
