### ISSUE TITLE
Saving breakpoints and comments as a session?

### ISSUE THREAD

**Issue by helvete003** [eteran/edb-debugger#609]
I use edb for CTF challanges and i remember, back when i was using OllyDbg for PE-files, that it saved my breakpoints and comments. When the application stopped, i could just run it again and didn't had to set the breakpoints again. Would this be usefull in edb? The bp and comments could be stored in the same way as the bookmarks (in a json). I would like to implement this feature but I'm not sure if this feature is really needed or wanted.

**Comment by eteran** [comment]
It is needed **and** wanted. These features have been discussed in issues #527 and #358.

Definitely, please feel free to take a crack at it if you have the interest to do so. The only real complexities that come to mind are:

* ASLR
* Dynamically loaded libraries
* making sure to store addresses as strings and not numbers as JSON numbers are often considered doubles and may be rounded to the nearest representable value in the round trip.

All 3 of these are "doable", and frankly, something would be better than nothing.

I am going to close this bug as a duplicate, but that doesn't mean that we have no interest! Like I said, feel free to jump up these if you have the interest :-)
