### ISSUE TITLE
"You may not debug EDB parent" isn't always true

### ISSUE THREAD

**Issue by 10110111** [eteran/edb-debugger#610]
This message is misleading and sometimes wrong. It sounds as if EDB forbids the user to debug parent process, and indeed, the attach may succeed. I can e.g. debug `bash` from which EDB is started if I comment out that `if` clause (Kubuntu 14.04 64-bit, kernel 3.16.0-73-generic). I'd suggest EDB to simply try what the user requested, and if that fails, then report what failed and with what `strerror(errno)`.

**Comment by eteran** [comment]
Hmm, in the past I ran into deadlock issues. I'll have to revisit this and see if it actually causes a problem.
