### ISSUE TITLE
Issue with cmake and capstone

### ISSUE THREAD

**Issue by smholsen** [eteran/edb-debugger#622]
Hello,
I am trying to install edb on Ubuntu, but when I am trying to run the cmake command, it complains about not finding the capstone package. I have tried installed it using sudo apt-get install libcapstone3, but it still does not seem to find it.
I have attached the error message below.  How can I resolve this issue?

 `
$ cmake -DCMAKE_INSTALL_PREFIX=/usr/local/ ..

Boost version: 1.58.0

Checking for module 'capstone>=3.0.4'

CMake Error at /usr/share/cmake-3.5/Modules/FindPkgConfig.cmake:367 (message):
  A required package was not found

Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/FindPkgConfig.cmake:532 (_pkg_check_modules_internal)
  cmake/Modules/FindCapstone.cmake:4 (pkg_check_modules)
  CMakeLists.txt:28 (find_package)
`

-- Configuring incomplete, errors occurred!`

**Comment by 10110111** [comment]
Is there any package like `libcapstone3-dev`?

**Comment by 10110111** [comment]
I think you want [libcapstone-dev](https://packages.ubuntu.com/xenial/libcapstone-dev).

**Comment by smholsen** [comment]
Thank you!
