### ISSUE TITLE
plugins not found

### ISSUE THREAD

**Issue by deepgray** [eteran/edb-debugger#623]
after performing the install, the executable startups up but can't find the plugins.

a dialog pops up after starting saying:

edb Failed To Load A Necessary Plugin

Failed to successfully load the debugger core plugin.

work fine from the build directory.

**Comment by 10110111** [comment]
Try removing the line containing `directory.plugin.path` from `~/.config/codef00.com/edb.conf`.

**Comment by eteran** [comment]
Did this resolve your issue?

**Comment by deepgray** [comment]
built via the Ubuntu or debian specific instructions and it works find...
