### ISSUE TITLE
no menu bar under ubuntu

### ISSUE THREAD

**Issue by deepgray** [eteran/edb-debugger#624]
EDB doesn't provide a menubar under ubuntu-gnome-desktop, ode-plasma-desktop, or lxde..

i realize this is a window manager issue but under debian with gnome-desktop has it but ubuntu related variants don't.

**Comment by eteran** [comment]
The menu bar isn't at the top of the screen unified with the system menu (similar to how macOS does it)? I thought that's what Ubuntu does by default. Screeshots?

**Comment by 10110111** [comment]
It's not a window manager issue, window manager only provides window decorations and manages window placement. I suppose you have this issue with all the Qt apps. If it's true, it's better to ask at askubuntu.com for assistance.

**Comment by deepgray** [comment]
![edb-screenshot](https://user-images.githubusercontent.com/14880472/33000433-0d31c70e-cd76-11e7-9703-ea9b2669f46d.png)

appears this is only on Ubuntu14 ...16  looks fine.

**Comment by eteran** [comment]
Can you show the whole desktop? On Ubuntu, normally emerges at menus with the global system menu at the very top of the screen.

**Comment by deepgray** [comment]
![ubuntu14-i386](https://user-images.githubusercontent.com/14880472/33081148-8e31919a-cea7-11e7-8e3c-1e45a6d19d11.png)

**Comment by 10110111** [comment]
That's [Ubuntu bug 1307619](https://bugs.launchpad.net/ubuntu/+source/appmenu-qt5/+bug/1307619), I'd guess.

**Comment by deepgray** [comment]
that fixed it...something to note on the Ubuntu notes...
