### ISSUE TITLE
capstone in the wrong location

### ISSUE THREAD

**Issue by deepgray** [eteran/edb-debugger#626]
when building capstone on i386 (kali), the make.sh file creates a directory, /usr/lib64, and installs the files there. when cmake .. on edb is performed, pkg_check fails because the files are in the wrong location.

I've put a ticket in about this on capstone, but not sure if it's a capstone error or a edb error.

**Comment by 10110111** [comment]
(ref: https://github.com/aquynh/capstone/issues/1050)

**Comment by eteran** [comment]
So, this is a real issue. But I don't think it's something edb can do anything about unless we decide to bundle capstone with edb as one thing. So I'm going to close the bug, but we'll keep an eye on the capstone issue created for it.

BTW, does this issue occur if you use capstone's cmake build process?

**Comment by deepgray** [comment]
i used the procedure you stated for the capstone build and install.

the work around was to copy the files in /usr/lib64 into the /usr/lib directory and works fine.

i'll have to look into capstone to see if there is a cmake process.
