### ISSUE TITLE
stream based input

### ISSUE THREAD

**Issue by deepgray** [eteran/edb-debugger#627]
i have not been able to read from stdin or another other stream based input.

the normal operations would be:

program-1 | program-2

program-2 is the target i am trying to debug.

**Comment by eteran** [comment]
Fair enough, given the current UI / command line options; what do you think would be a user-friendly way to specify the source of input for the debugged program?

**Comment by deepgray** [comment]
maybe in the options where there are arguments, have a stream option? maybe a cli field where the instruction is for stdin via a pipe?

i'm not sure of how you would implement that...

the other aspect is if i am debugging a app that reads a file...don't know if the debugger would handle that in the same fashion since files and pipes are all streams.

in gdb, you would:

run < file.txt but run < $(python -c '"A"*1024') doesn't work...most likely issues with command substation and streams.

**Comment by 10110111** [comment]
Well command substitution doesn't work in GDB because GDB isn't Bash. The `<` syntax is explicitly supported for files (and, I'd guess, some resources as named pipes).
I think it's a good idea for EDB to get an option like `--stdin filename` and `--stdout[-append] filename`.

**Comment by deepgray** [comment]
that would work...

with regard to bash, i found that:

command1 | command2

works the same as

command2 < <(command1)

but

command 2 <(command1)

doesn't...

**Comment by deepgray** [comment]
and command2 < $(command1) doesn't work either

**Comment by deepgray** [comment]
as a side note i tried this...

ladmin@ubuntu14-i386:~/Desktop$ python -c 'print "A"*64 + "\x24\x84\x04\x08"' | ./stack3
calling function pointer, jumping to 0x08048424
code flow successfully changed
ladmin@ubuntu14-i386:~/Desktop$ ./stack3 < <(python -c 'print "A"*64 + "\x24\x84\x04\x08"')
calling function pointer, jumping to 0x08048424
code flow successfully changed
ladmin@ubuntu14-i386:~/Desktop$ edb --run ./stack3 < <(python -c 'print "A"*64 + "\x24\x84\x04\x08"')
Starting edb version: 0.9.22 
Please Report Bugs & Requests At: https://github.com/eteran/edb-debugger/issues
Running Terminal:  "/usr/bin/xterm" 
Terminal Args:  ("-title", "edb output", "-hold", "-e", "sh", "-c", "tty > /tmp/edb_temp_file_1232312080_30242;trap "" INT QUIT TSTP;exec<&-; exec>&-;while :; do sleep 3600; done") 
Terminal process has TTY:  "/dev/pts/6" 
Loading session file
Loading plugin-data
restoreComments
comparing versions: [2325] [2326]
Saving session file
ladmin@ubuntu14-i386:~/Desktop$ 

edb didn't process it correctly...so not sure if there is a way ahead...

**Comment by deepgray** [comment]
don't know why gtihub put the strike through lines...

**Comment by 10110111** [comment]
Because you failed to use triple backticks to make the text pre-formatted. And in Markdown, double tildes mean strike through. See [the reference](https://guides.github.com/features/mastering-markdown/).

**Comment by deepgray** [comment]
ok...

back on the stream input, what would happen if i executed this:

command1 | edb --run command2

could the fileIO from command1 bepassed in to the command2 being executed?

**Comment by 10110111** [comment]
I don't think so. And implementing it in this way would be no good if EDB ever decides to get a command-line interface.

**Comment by eteran** [comment]
Implemented! Essentially did what was suggested in this comment:

https://github.com/eteran/edb-debugger/issues/627#issuecomment-346068444

**Comment by 10110111** [comment]
OK, so I've tried it with a simple command:
```
edb --stdin <(printf "Hello, world!\nWait a bit\nAnd hello again ;)\n") \
    --stdout >(grep again > /tmp/out.txt) \
    --run /bin/cat
```
Pressed <kbd>F9</kbd> twice and... `cat` hangs in `read()`. At the same time, of course, this works as expected:
```
cp <(printf "Hello, world!\nWait a bit\nAnd hello again ;)\n") \
   >(grep again > /tmp/out.txt)
```
as does this
```
printf "Hello, world!\nWait a bit\nAnd hello again ;)\n" | /bin/cat | 
       grep again > /tmp/out.txt
```
where output of both is the same in `/tmp/out.txt`.

**Comment by eteran** [comment]
@10110111 

The things passes to `--stdin` and `--stdout` are files, most usefully, named pipes.

So you'd have to do something like:

```
mkfifo my_fifo
edb --stdin my_fifo --run /bin/cat
```

and then separately, likely in a different terminal something like this:

```
printf "hello world\n" > my_fifo
```

**Comment by eteran** [comment]
This lays the groundwork, but we can eventually add more bash like syntax support.

**Comment by 10110111** [comment]
> The things passed to --stdin and --stdout are files, most usefully, named pipes.

If you look closely, my examples also pass files, namely, `/dev/fd/a_number`. That's what this `>(command)` and `<(command)` syntax expands to from the application POV.

**Comment by eteran** [comment]
oh really? OK, interesting, I didn't know about that syntax!

OK, I'll have to play around with it and see if there's a reason why some things don't work as expected.

The code is pretty simple though, it's just setting stdin/out/err to the given pipes, so hard to see where it would go wrong :-/

**Comment by eteran** [comment]
@10110111 

So I did some testing:

```
./edb --stdin <(printf "Hello, world\!\n") --run /bin/cat
```

Does, in fact, properly pull its stdin from the `printf`, and prints the "Hello, World!\n" in the output terminal.

But ... It doesn't terminate, so it doesn't think that the stream is ever hits `EOF`. Could that be what you're running into?

**Comment by eteran** [comment]
I've been able to reproduce the problem with this minimalistic test program. I'm not sure what I'm doing wrong here, but I'm going to investigate.

```
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/types.h>
#include <sys/wait.h>
#include <unistd.h>

int main(int argc, char *argv[]) {

	switch (pid_t pid = fork()) {
	case 0: {
		// in child
		freopen(argv[1], "r+b", stdin);

		char path[]  = "/bin/cat";
		char *args[] = {path, NULL};

		execv(args[0], args);
		abort(); // we should never get here!
	}
	case -1:
		// error
		return -1;
	default: {
		// in parent
		int status;
		const auto r = waitpid(pid, &status, __WALL);

		if (r == -1) {
			perror("waitpid");
			return -1;
		}
		break;
	}
	}
}
```

```
g++ test.cpp -o test
./test >(printf "Hello\n")
```

**Comment by 10110111** [comment]
OK, I don't get the hang now, but the output in the output file doesn't appear unless I close EDB after the debuggee terminates. Tested with my test case from https://github.com/eteran/edb-debugger/issues/627#issuecomment-595983860.

Another issue: starting a new debuggee appears to try to reuse the same stdin and stdout, which may not be what the user wants (the processes that generated or consumed the data may have exited by now). I think it'd be best to give the user some control over this in the _Open_ dialog (we've already done this for command line arguments, might add two more line edits).

**Comment by eteran** [comment]
Yea, output may be tricky to get right since we are at the whim of when The debugee decides to flush/close the file.

You are right about running another process. If the source was a pipe, It almost certainly does not make sense to have future runs trying to consume it again.

Restart also has a similar problem I think

**Comment by 10110111** [comment]
> since we are at the whim of when The debugee decides to flush/close the file.

Well, that must happen by the time it exits. But it doesn't happen even after I click OK on the "Terminated with exit code 0" message box. Only EDB shutdown gives me the output. So I suppose it's something related to the way EDB starts the debuggee.

**Comment by eteran** [comment]
Hmm, interesting.
