### ISSUE TITLE
stack addressing differs from i386 to amd64 for the same i386 ELF

### ISSUE THREAD

**Issue by deepgray** [eteran/edb-debugger#630]
the target app is a i386 32 bit ELF.

when debugging on amd64 with gcc-multilibs installed, the address in the stack view is different on amd64 than it is on i386.

code addresses are the same. why isn't the stack emulated in teh same addressing?

is this a capstone issue?

**Comment by 10110111** [comment]
EDB is not an emulator, it's a debugger. It shows whatever the application on your kernel actually gets. And why do you think the addresses should be the same? At the very least, addresses can't have nonzero bits 47:32 in 32-bit mode, while they commonly do in 64-bit mode.

**Comment by eteran** [comment]
@deepgray I think you are misunderstanding something. As @10110111 said, edb is not an emulator, so the stack is wherever the OS (and libc I suppose) decides to place it.

Even if edb were an emulator, I don't think this could be considered a bug. Please feel free to reopen this issue if we are misunderstanding you.

**Comment by deepgray** [comment]
I thought to worked with capstone for cross architecture debugging...

**Comment by 10110111** [comment]
Capstone is not an emulator, it's just a disassembler, nothing more.

**Comment by eteran** [comment]
I think that unicorn engine (built by the capstone guys) is a machine simulation. But capstone itself is just a disassembler.
