### ISSUE TITLE
Make error (X32 support)

### ISSUE THREAD

**Issue by Devdexterity** [eteran/edb-debugger#633]
there is an make error [error: ‘__X32_SYSCALL_BIT’ was not declared in this scope]
on [src/CMakeFiles/edb.dir/arch/x86-generic/ArchProcessor.cpp.o] .

and my enviroment is on centos 6.4
-- The CXX compiler identification is GNU 4.8.2
-- Check for working CXX compiler: /opt/rh/devtoolset-2/root/usr/bin/c++
-- Check for working CXX compiler: /opt/rh/devtoolset-2/root/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Boost version: 1.65.1
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.23") 
-- checking for module 'capstone>=3.0.4'
--   found capstone, version 3.0.5
-- checking for module 'libgvc>=2.38.0'
--   package 'libgvc>=2.38.0' not found
-- Performing Test COMPILER_SUPPORTS_CXX11
-- Performing Test COMPILER_SUPPORTS_CXX11 - Success
-- Configuring done
-- Generating done
-- Build files have been written to: /home/dbg/edb-debugger/build

**Comment by 10110111** [comment]
Does this command give you anything:
```
grep '\<__X32_SYSCALL_BIT\>' /usr/include/ -rIl
```

**Comment by Devdexterity** [comment]
thanks a lot! 
I've got the released version 0.9.21 and it works fine now.
but i will rollback my VM to confirm if your command could fix that error later, and reply it here then.

**Comment by lynxlynx** [comment]
Same thing,
`grep '\<__X32_SYSCALL_BIT\>' /usr/include/ -rIl`
does not reveal anything (my headers are a bit old anyway). I did put
`
#ifndef __X32_SYSCALL_BIT
#define __X32_SYSCALL_BIT 0x40000000
#endif
`
temporarily into `src/arch/x86-generic/ArchProcessor.cpp`
to continue.

**Comment by 10110111** [comment]
You can install Qt 5.10.1 using [this repo](https://launchpad.net/~beineri/+archive/ubuntu/opt-qt-5.10.1-xenial) on Ubuntu Xenial. But frankly, these errors have nothing to do with this issue, which is about x32.

**Comment by Qing-zhan** [comment]
@10110111 Thanks for the repo. Another question, is it possible to modify this HardwareBreakpoints.cpp source file to adjust to Qt versions 5.x which are less than 5.5 ?

**Comment by eteran** [comment]
@Qing-zhan  Please checkout the latest version from master. When I added the lambdas to that file, I didn't realize that support for them in `addAction` was added in 5.5, so I rolled it back 3 days ago and it should build again with Qt >= 5.0

**Comment by Qing-zhan** [comment]
@eteran yay, it works!!! thanks
