### ISSUE TITLE
Build compatibility with non-glibc systems

### ISSUE THREAD

**Issue by lynxlynx** [eteran/edb-debugger#635]
I am using a system with musl libc as the only libc available. It provides different standard headers as well as different dynamic linking interface.
edb builds and runs just fine, but for better portability you may need to make these adjustments:
1. `plugins/DebuggerCore/unix/linux/DebuggerCore.cpp` misses `#include <sys/wait.h>`. Without it, `__WALL` macro for `waitpid()` is missing and compile errors pop out.
2. `plugins/DebuggerCore/unix/linux/arch/x86-generic/PlatformThread.cpp` relies on `enum __ptrace_request` as first `ptrace()` argument. This is fine and conforming probably, but musl uses `int` instead. I had to add `#define __ptrace_request int` just after all includes but before `// doesn't always seem to be defined in the headers` defines.

While 1 definitely wants to be fixed, 2 is questionable.

**Comment by 10110111** [comment]
I suppose `typedef` would be better than `#define`, but in any case this one will need some CMake checks to be really viable (like "if `__ptrace_request` doesn't compile in a test, then declare a `typedef` for it in some config header").

**Comment by eteran** [comment]
@lynxlynx is this issue resolved? Or do you feel that it just hasn't gotten attention?
