### ISSUE TITLE
Debug

### ISSUE THREAD

**Issue by AngeloNero01** [eteran/edb-debugger#638]
DEBUG  comparing versions: [2325] [2326]
WARN   QXcbWindow: Unhandled client message: "_GTK_LOAD_ICONTHEMES"

**Comment by eteran** [comment]
Are these messages causing an indicator of something not functioning correctly? I can say that the first one is completely normal and is just saying that the version you have is newer than the lastest "official release"

**Comment by AngeloNero01** [comment]
Thanks Evan .....Happy New Year ;)




________________________________
Da: Evan Teran <notifications@github.com>
Inviato: venerdì 29 dicembre 2017 23:54
A: eteran/edb-debugger
Cc: AngeloNero01; Author
Oggetto: Re: [eteran/edb-debugger] Debug (#638)


Are these messages causing an indicator of something not functioning correctly? I can say that the first one is completely normal and is just saying that the version you have is newer than the lastest "official release"
