### ISSUE TITLE
Edm-debugger 

### ISSUE THREAD

**Issue by mikeofthenight2003** [eteran/edb-debugger#642]
Hello,
    I wish to report the following error after sucsessfully building and installing
    edm-debugger-0.9.21
This is the actual message from the debugger.

"Failed to setup program arguments and working directory entries for file open dialog,
please report and be sure to tell your Qt version"
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.

I am using qt5 version 5.9.5 on Linux grumpy 4.14.16-300.fc27.x86_64
#1 SMP Wed Jan 31 19:24:27 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
The following dependancies are installed:
    qt5-devel gcc gcc-c++ boost-devel cmake capstone-devel
    NASM version 2.13.02 compiled on Jan  2 2018

I have tried re-building twice everything in edm-debugger-0.9.21 appears to be
working apart from the inabliity to enter command line argumemts.

Mike Lear.

**Comment by 10110111** [comment]
Possibly the same problem as #637.

**Comment by eteran** [comment]
Yea, this doesn't seem to be a "hard error, just undesirable behavior that is outside of the control of edb. Closing; please re-open if this is not redundant to the issue mentioned by @10110111

**Comment by mikeofthenight2003** [comment]
Thank you for updating me in this matter.  I shall continue to supplycommand line args to my programs by starting edb from the commandline with the --run option.
Mike Lear

    On Tuesday, 13 February 2018, 04:13:52 GMT, Evan Teran <notifications@github.com> wrote:  
 
 
Yea, this doesn't seem to be a "hard error, just undesirable behavior that is outside of the control of edb. Closing; please re-open if this is not redundant to the issue mentioned by @10110111

**Comment by 10110111** [comment]
Please note that #637 has a better workaround (unless you absolutely want Qt5's GTK integration).
