### ISSUE TITLE
Whatever the file I open, edb cannot open it

### ISSUE THREAD

**Issue by toderesa97** [eteran/edb-debugger#643]
Hi,
 I am getting this error whatever the opened file is:

![capture](https://user-images.githubusercontent.com/19231158/36352790-87fd9924-14be-11e8-8672-1c009d5b9e07.PNG)

I am logged in as root, so I do not know what might be causing that error.
Thank you,
TDRS

**Comment by 10110111** [comment]
Apparently, the files don't have `x` permission...

**Comment by toderesa97** [comment]
Thank you, It works.
