### ISSUE TITLE
"Error Loading Session" dialog has no text

### ISSUE THREAD

**Issue by sorokin** [eteran/edb-debugger#647]
When I tried attaching to an existing process, I see the following dialog:

![error-loading-session](https://user-images.githubusercontent.com/286877/37244776-d1cd002c-249e-11e8-9109-6a3d39ee59b6.png)

This dialog is not resizable, so I can not resize it to see full text. This dialog is shown in function: Debugger::set_initial_debugger_state():
```
QMessageBox::warning(
				this,
				tr("Error Loading Session"),
				QT_TR_NOOP(session_error.getErrorMessage())
			);
```

I see 2 problems with this dialog:
1. It is not properly sized and it is not resizable.
2. It doesn't provide any meaningful information on how to troubleshoot the problem.

**Comment by 10110111** [comment]
Duplicate of #628.

**Comment by sorokin** [comment]
I didn't see that. Closing. Thank you.
