### ISSUE TITLE
Erasing an element of std::deque while iterating over it

### ISSUE THREAD

**Issue by sorokin** [eteran/edb-debugger#650]
I have found an error in the logic of step out, but before developing a fix I would like to discuss the problem.

First let me explain what I'm trying to do. Recently I have learned that there is a debugger like ollydbg, but for Linux. And I was really excited about all this. On the other hand the person who told me about edb warned me that he had found the debugger very unstable.

As I liked the idea of having olly-like debugger for Linux. I decided to take a look at it.

I shoved "-fsanitize=address,undefined -D_GLIBCXX_DEBUG" into CXXFLAGS. These options are to enable debug checks inserted by compiler and standard library. After this I got a program that can not even start without printing some errors. This is the way I found #645 and #646.

Another problem I found was an unconditional crash on step out. The problem is the following:

1. execute_debug_event_handlers() is run.
2. execute_debug_event_handlers() is iterating over handlers and now stays on element corresponding RunUntilRet.
3. RunUntilRet::handle_event() is run, prints "Found ret; passing back to debugger" and calls "delete this".
4. RunUntilRet::~RunUntilRet() is called doing remove_debug_event_handler(this).
5. remove_debug_event_handler() erases the element corresponding to RunUntilRet. Erasing the element invalidates the iterator that is hold by execute_debug_event_handlers (!!!!!)
6. remove_debug_event_handler() is quit, RunUntilRet::~RunUntilRet() is quit, RunUntilRet::handle_event() is quit.
7. The execution is back to execute_debug_event_handlers(). The next operation it does is ++it incrementing invalid iterator.

The console log I see is the following:
```
"Scanning for terminator at 0x4001c7: found pop"
"Scanning for terminator at 0x4001c8: found pop"
"Scanning for terminator at 0x4001c9: found ret"
"Found terminator ret at 0x4001c9"
"Setting breakpoint at terminator 0x4001c9"
"Event at address 0x4001ca"
Trap breakpoint
Previous was an internal breakpoint.
"On our terminator at 0x4001c9"
Found ret; passing back to debugger
safe_iterator.h:298:
Error: attempt to increment a singular iterator.

Objects involved in the operation:
    iterator "this" @ 0x0x7ffc15c979e0 {
      type = __gnu_debug::_Safe_iterator<std::__cxx1998::_Deque_iterator<IDebugEventHandler*, IDebugEventHandler*&, IDebugEventHandler**>, std::__debug::deque<IDebugEventHandler*, std::allocator<IDebugEventHandler*> > > (mutable iterator);
      state = singular;
      references sequence with type 'std::__debug::deque<IDebugEventHandler*, std::allocator<IDebugEventHandler*> >' @ 0x0x1993a00
    }
```

The problem is that the current implementation doesn't support unsubscribing from the debug events from the inside of debug event handler.

I see 3 ways of fixing this problem.
1. Using Qt signals. They support unsubscribing a slot from the inside. This solution involves making IDebugEventHandler QObject which I don't really like.
2. Using Boost.Signals2. They support unsubscribing a slot from the inside too. The problem is that Boost.Signals2 doesn't support unsubscribing by a pointer to the original object. Instead subscribing returns a special object (called connection) that is then used to unsubscribing. So this involves changing interface of add_debug_event_handler to return boost::signals2::connection.
3. Roll out home-grown mini-signal like class. This will help preserving the current interface. I expect the class to be 200-300 lines long.

I would like to use the solution 3.  What do you think?

P. S. As there must be more bugs lurking around can I suggest adding something like
```
set(CMAKE_CXX_FLAGS_DEBUG "-fsanitize=address,undefined -D_GLIBCXX_DEBUG ${CMAKE_CXX_FLAGS_DEBUG}")
```
to the CMakeLists.txt and asking all developers to test the program in this configuration?

**Comment by eteran** [comment]
Excellent find! I'll take a look at the code more carefully and we can see what the best solution is.

Thanks for reporting.

**Comment by sorokin** [comment]
Thank you. I'm looking forward to what you think should be done.

Also I have prepared a fix (using the solution 3) as described above: #651.

**Comment by eteran** [comment]
Just as a note, I've added a whole slew of configuration options to cmake to easily enable different types of sanitizers, which should hopefully make it much simpler to catch these types of issues going forward :-)

**Comment by sorokin** [comment]
Great, thank you!
