### ISSUE TITLE
Any instructions how to download the .exe?

### ISSUE THREAD

**Issue by tazotodua** [eteran/edb-debugger#655]
For newbies like me, how can I get .exe file of edb-debugger? I am not familiar how to make program from this github source code. Just need the production(compiled) file like x64dbg is available for download.

any help?

**Comment by eteran** [comment]
I assume since you're asking for a .exe that you are looking for a windows build. Linux is the only supported platform at the moment (The only platform that both builds and works).

**Comment by tazotodua** [comment]
thanks, sorry.

**Comment by eteran** [comment]
No worries! Windows support will come one day!

**Comment by tazotodua** [comment]
well, it may be also good if you develop as a plugin for x64dbg, because its superior at this moment and I doubt starting from ground, could become a strong competitor of it, but plugin (it supports) could be used by existing users too. however, as you wish. thanks. (btw, dont count me in Windows users, as I had only one-time project and just asked if it was available for windows).
thanks!

**Comment by eteran** [comment]
I'm not sure what it would mean for edb to be a "plugin" to x64dbg...
