### ISSUE TITLE
make install does not install correctly

### ISSUE THREAD

**Issue by Smilex** [eteran/edb-debugger#656]
I've downloaded the 1.0.0 tarball, and I created a build directory, where I ran cmake, then make, then sudo make install, and I get the following error,

> $ edb
> This application failed to start because it could not find or load the Qt platform plugin "xcb"
> in "".
> Available platform plugins are: linuxfb, minimal, offscreen, xcb.
> Reinstalling the application may fix this problem.
> Aborted (core dumped)

This is on Arch Linux. Running edb from the build directory does work.

**Comment by eteran** [comment]
Hmm, I'm not sure what would cause that...

I'll have to try to set up an arch VM or docker, and see if I can replicate this. That error seems to be coming from QT or X11, so I wonder why launch path makes a difference at all.

**Comment by Petross404** [comment]
@Smilex Is there a tool in Arch, that can output the files that a package owns? Like : 

```
/usr/bin/foo
/usr/lib/qt5/bar.so
/usr/share/...
```

This way it will be much easier to figure out which file went in the wrong place.

**Comment by Smilex** [comment]
@Petross404 I did not install a package, so my package manager does not know about this software. I just ran `sudo make install`, after compiling the project.

**Comment by Smilex** [comment]
It is linked against Qt5

**Comment by Petross404** [comment]
Better check with `lddtree`. Also these libraries are supposed to exist inside `/usr/lib64/qt5/plugins/platforms/`.

```
ls /usr/lib64/qt5/plugins/platforms/
KWinQpaPlugin.so  libqminimal.so  libqoffscreen.so  libqwayland-egl.so  libqwayland-generic.so  libqwayland-xcomposite-egl.so  libqwayland-xcomposite-glx.so  libqxcb.so
```

Does your directory miss anything xcb-related?

**Comment by Smilex** [comment]
Yes I have these files, but they are under /usr/lib64/qt/.

**Comment by Petross404** [comment]
I don't think that it's a problem. Can you please paste the output of `lddtree /path/to/edb`? Also, can you please shows us the output of `make install`?

**Comment by eteran** [comment]
No follow up and haven't seen it happen locally. Closing for now, but please re-open if the problem persists.
