### ISSUE TITLE
PTRACE_GETSIGINFO failed

### ISSUE THREAD

**Issue by certxbmc** [eteran/edb-debugger#660]
I updated from 0.9.xxx to 1.0.0

open file, running application -> edb error "unable to get signal info for thread xxx : PTRACE_GETSIGINFO failed"

i tried to set "kernel.yama.ptrace_scope = 0" /etc/sysctl.d/10-ptrace.conf but it doesn't help.

**Comment by eteran** [comment]
Can you please provide information about your distribution? Also, I assume 0.9.xx worked? Which is a bit odd since 1.0.0 didn't make any large changes since the last 0.9.x release to the debugging core code.

**Comment by certxbmc** [comment]
Ubuntu 18.04 LTS, edb 0.9.21-3 is in this distibution, i deleted the edb config file after updating because plugins didn't load, edb 0.9.21-3 sometimes stopped working when i used the "step over" function.

**Comment by 10110111** [comment]
Latest git works for me on Ubuntu 18.04 x86_64.

**Comment by certxbmc** [comment]
I compiled edb yesterday from git. Fresh Ubuntu 18.04 LTS installation with updates. When i use the "attach" function edb 1.0.0 works fine but i want to pause at application start.

**Comment by 10110111** [comment]
Please provide detailed step-by-step instructions on how to reproduce your exact problem, including how you built EDB, which application you launch/attach to, what errors/misbehavior you get as a result. Otherwise we'll be unable to help you.

**Comment by certxbmc** [comment]
I tried Ubuntu 16.04 and there's the same problem. Fresh install and compiling 1.0.0. I have to correct me and the problem is in 0.9.21 too. I think the application i 'm trying to debug is starting a thread and gdb can't follow.

**Comment by certxbmc** [comment]
EDB stops debugging at this location "call qword [rel 0x6xxxxx]" and it points to __libc_start_main.

**Comment by eteran** [comment]
@certxbmc is the issue debugging a specific binary, or do you encounter this with any other binaries?

If we are to work on this, we'll need to reproduce it locally, so as much information (the program, steps to reproduce, etc...) would be very helpful.

Thanks

**Comment by certxbmc** [comment]
Maybe the problem is similar to this issue:

https://github.com/eteran/edb-debugger/issues/571

I will check other binaries.

**Comment by eteran** [comment]
Closing dude to lack of activity.
