### ISSUE TITLE
how can

### ISSUE THREAD

**Issue by yangshaojie0123** [eteran/edb-debugger#666]
CMake Error at /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE)
Call Stack (most recent call first):
  /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.10/Modules/FindPkgConfig.cmake:36 (find_package_handle_standard_args)
  cmake/Modules/FindCapstone.cmake:2 (find_package)
  CMakeLists.txt:26 (find_package)

**Comment by yangshaojie0123** [comment]
when i mkdir build file and cd into this file . i want to "cmake .." but something wrong

**Comment by eteran** [comment]
OK, you are missing pkg-config, seems that it is not included in build-essentials.
