### ISSUE TITLE
Feature: Go To Address in Data Dump

### ISSUE THREAD

**Issue by ttufts** [eteran/edb-debugger#682]
Currently if a memory region is executable it automatically loads in the CPU pane. On the CTF binary I'm looking at, the Heap is executable... so I can't view the heap in the Data Dump unless I wait for the address to be in a register or on the stack, then right click on it and choose Follow in Data Dump. It would be nice to be able to jump to any address in Data Dump from an input window.

**Comment by eteran** [comment]
Click on the data dump, press "Ctrl+G", or right click and select "Goto Address" :-P
