### ISSUE TITLE
Feature: Searchable ROPs in ROPTool

### ISSUE THREAD

**Issue by ttufts** [eteran/edb-debugger#685]
Give a search/filter box for searching ROPs by text. When searching for a ROP through libc... there are a lot... I just want pop eax damnit!

**Comment by ttufts** [comment]
Addendum: 

Allow copy/pasta for the ROP list. Editor of choice might be a nice shortcut for this, and awesome editors like Atom allow regex search.

**Comment by eteran** [comment]
The ROPTool has been searchable for a while now. Now that 1.1.0 is released, safe to close this bug :-)

No Regex support yet though, that would require at the very least a checkbox to enable since it would be confusing by default.
