### ISSUE TITLE
Question about Capstone 4 and edb

### ISSUE THREAD

**Issue by Petross404** [eteran/edb-debugger#689]
[Here](https://github.com/eteran/edb-debugger/wiki/Compiling) it is mentioned that edb needs `capstone >=3`, but at bug [673466](https://bugs.gentoo.org/673466) one can see that `dev-libs/capstone-4.0` (i.e >=3) creates a problem.

```
>>> package: dev-libs/capstone-4.0
 *  - /usr/lib64/libcapstone.so.3
 *      used by /usr/bin/edb (dev-util/edb-debugger-1.0.0-r1)
```

Is capstone-4 incompatible with edb? 

Thanks.

**Comment by 10110111** [comment]
What is the problem you actually have with capstone 4? From the links I couldn't understand what it is.

**Comment by Petross404** [comment]
My bad. There is [something](https://wiki.gentoo.org/wiki/Sub-slots_and_Slot-Operators) missing from my ebuild so when capstone installed a different soname, edb preserved the old `capstone.so.3` instead of getting rebuilt with `capstone.so.4` and portage deleting the old one.

> The FEATURES=preserve-libs setting will cause Portage to preserve libraries when sonames change during upgrade or downgrade, only as necessary to satisfy shared library dependencies of installed consumers. Preserved libraries are automatically removed when there are no remaining consumers, which occurs when consumer packages are rebuilt or uninstalled. Ideally, rebuilds are triggered automatically during updates, in order to satisfy slot-operator dependencies. Before emerge exits after installing updates, if there are remaining preserved libraries because slot-operator dependencies have not been used to trigger automatic rebuilds, then emerge will display a message like the following:

More details [here](https://wiki.gentoo.org/wiki/Preserve-libs). 

Thanks.
