### ISSUE TITLE
Upgrade edb in Kali Linux results undefined symbol error

### ISSUE THREAD

**Issue by ZozoZoeLi** [eteran/edb-debugger#690]
System Info: Linux kali 4.17.0-kali1-686 #1 SMP Debian 4.17.8-1kali1 (2018-07-24) i686 GNU/Linux

I got the notification while using EDB that 1.0.0 upgrade is available. Therefore I did:
1. sudo apt-get remove --purge edb-debugger
2. sudo apt autoremove
3. sudo apt-get install edb-debugger

The error comes up:
#edb --version
[load_plugins] Cannot load library /usr/lib/i386-linux-gnu/edb/libDebuggerErrorConsole.so: (/usr/lib/i386-linux-gnu/edb/libDebuggerErrorConsole.so: undefined symbol: _ZN26DebuggerErrorConsolePlugin20DebuggerErrorConsole20compareDisassemblersEv)
edb version: 1.0.0

**Comment by 10110111** [comment]
Looks like your `edb-debugger-plugins` package is out of date. Not sure how that could happen with proper package management, this is just my guess.

**Comment by cristimiha** [comment]
I had the same problem, and the above response seems like a solution... Upgrading the package > `edb-debugger-plugins` does the trick

**Comment by eteran** [comment]
Seems that solution is diagnosed.

**Comment by megastruktur** [comment]
Hey,
I have the same issue. Can you please help?  :)
Purged remove both edb and plugins, reinstalled them back, nothing helps...

`Linux kali 4.19.0-kali4-686 #1 SMP Debian 4.19.28-2kali1 (2019-03-18) i686 GNU/Linux`

```
# apt-get install edb-debugger-plugins
Reading package lists... Done
Building dependency tree       
Reading state information... Done
edb-debugger-plugins is already the newest version (1.0.0-1).
```

```
# edb --version
[load_plugins] Cannot load library /usr/lib/i386-linux-gnu/edb/libDebuggerErrorConsole.so: (/usr/lib/i386-linux-gnu/edb/libDebuggerErrorConsole.so: undefined symbol: _ZN26DebuggerErrorConsolePlugin20DebuggerErrorConsole20compareDisassemblersEv)
edb version: 1.0.0
```

**Comment by eteran** [comment]
Unfortunately, I don't have much control of the kali packages. When it doubt I would try the following:

1. uninstall edb and plugins
2. remove $HOME/.config/codef00.com/edb.conf
3. clone the repo (recursively) and build from master
4. just run it from the build directory

I can't imagine how that could fail to work...

**Comment by megastruktur** [comment]
@eteran It's magic, but it worked. Sorry for wasting yr time.

**Comment by eteran** [comment]
Not a waste of time at all. Now we know that works and anyone with the same problem will find this too 👍

**Comment by joshuaspy** [comment]
> Unfortunately, I don't have much control of the kali packages. When it doubt I would try the following:
> 
> 1. uninstall edb and plugins
> 2. remove $HOME/.config/codef00.com/edb.conf
> 3. clone the repo (recursively) and build from master
> 4. just run it from the build directory
> 
> I can't imagine how that could fail to work...

This solved issue for me. thank you.

**Comment by aliefar** [comment]
> Unfortunately, I don't have much control of the kali packages. When it doubt I would try the following:
> 
>     1. uninstall edb and plugins
> 
>     2. remove $HOME/.config/codef00.com/edb.conf
> 
>     3. clone the repo (recursively) and build from master
> 
>     4. just run it from the build directory
> 
> 
> I can't imagine how that could fail to work...



> Unfortunately, I don't have much control of the kali packages. When it doubt I would try the following:
> 
>     1. uninstall edb and plugins
> 
>     2. remove $HOME/.config/codef00.com/edb.conf
> 
>     3. clone the repo (recursively) and build from master
> 
>     4. just run it from the build directory
> 
> 
> I can't imagine how that could fail to work...

i edit $HOME/.config/codef00.com/edb.conf with true plugin directory and its work.thanks
