### ISSUE TITLE
accesss

### ISSUE THREAD

**Issue by BeneficialCode** [eteran/edb-debugger#700]
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-kernel'
failed to open memory file: No such file or directory
Detect that read /proc/<pid>/mem works  =  false
Detect that write /proc/<pid>/mem works =  false
Starting edb version: 1.0.0

**Comment by eteran** [comment]
Can you provide a few more details?

Does this occur when debugging all files or just some? Which distribution? Are there any security features enabled that I should be aware of like SELinux?

It looks like it failed to even identify its own pid as those tests should read something like:

    Detect that read /proc/1234/mem works = true

where 1234 is the pid of a subprocess of edb used to test the feature.

**Comment by eteran** [comment]
Closing due to lack of followup. Please reopen if the problem persists.
