### ISSUE TITLE
Command line parameters

### ISSUE THREAD

**Issue by SummerLife** [eteran/edb-debugger#703]
Could you please tell me that how can i add the command line parameters when i debug? Thank you very much.

**Comment by eteran** [comment]
There are essentially 2 methods to do this:

* You can run edb from the command line and use `--run` for example:

    ./edb --run /bin/ls /etc/*

* You can use the UI to set application arguments for the **next** opened program. You can do this with the "Options -> Application Arguments" menu item. In there, you can add/remove/reorder arguments as you see fit.

**Comment by SummerLife** [comment]
I tried to add arguments in the "Options -> Application Arguments" menu item, but it did not work

**Comment by SummerLife** [comment]
And the first method works well. I really appreciate your help!

**Comment by eteran** [comment]
The menu option should work, if it isn't working, can you describe exactly what you did step by step so I can try to reproduce?

**Comment by 10110111** [comment]
I can confirm that it's broken (or too unintuitive to use it correctly). I do as follows:

1. Run EDB
1. Options → Application Arguments
1. `+` button
1. Replace the text with `5454`
1. Close
1. File→Open
1. `/bin/sleep`
1. `F9`, `F9` → get exit with code 1, with `/bin/sleep: missing operand` in the console.

**Comment by 10110111** [comment]
BTW, third option (which does work) is to specify the arguments in the _Run_ dialog.

**Comment by SummerLife** [comment]
Thanks very much for your help.

**Comment by eteran** [comment]
@10110111 Hmm, we'll have to look into that then. It's not a feature I use often, but it used to work!

**Comment by itsallmathematics** [comment]
@eteran I cannot use the GUI to add args.. See screenshot. The box won't let me type anything in and it has no "+" button or any way to add args... Am I missing something?
![edb_args](https://user-images.githubusercontent.com/57550024/68732305-d033c900-0587-11ea-88a6-2c82281001ce.png)

**Comment by eteran** [comment]
@itsallmathematics Sorry, that method of using the feature has actually be removed because it was surprisingly difficult to implement in a user-friendly way (It would contradict the other more direct methods of setting the arguments creating confusion).

The current correct way is either through the command line parameters, or the file open-dialog.
