### ISSUE TITLE
edb crashes when adding a hardware breakpoint if a hardware breakpoint was attempted previously unsuccessfully

### ISSUE THREAD

**Issue by AaronOpfer** [eteran/edb-debugger#704]
Steps to repro:

  * attach edb to a process
 * resume so that the process is running
 * attempt to set a hardware read/write breakpoint in the memory dump view
 * see that it fails with an error suggesting you pause the process
 * pause the process
 * reattempt to set the hardware read/write breakpoint in the memory dump view
 
Expected: breakpoint is set successfully

Actual: edb crashes with the following in the terminal

```
/home/aopfer/gits/edb-debugger/src/DebugEventHandlers.cpp:40: void DebugEventHandlers::add(IDebugEventHandler*): Fatal error: the same event handler is added twice
```

**Comment by eteran** [comment]
Ok, should be an easy fix. Thanks!
