### ISSUE TITLE
Symbol Viewer shows empty list for elf_i386 linked with ld-2.31

### ISSUE THREAD

**Issue by BwanaTheBig** [eteran/edb-debugger#705]
When using linker ld-2.30+ to build executable Symbol Viewer cannot load symbols and does not produce symbol map-file in ~/cache/codef00.com/edb/symbols/.....

**Comment by eteran** [comment]
Interesting, can you attach an example executable for me to test with?

**Comment by eteran** [comment]
Possibly related to #707 ?
