### ISSUE TITLE
No way to show CPU registers after hiding them

### ISSUE THREAD

**Issue by jfariasf** [eteran/edb-debugger#708]
If you hide Registers there's no way to get them back. I even tried to hide them all to see what happened and now I'm with a blank window where the registers should be.

**Comment by 10110111** [comment]
Actually there is a way, although admittedly not too user-friendly: add new Register View via _Plugins_→_OllyDbg-like Register View_→_New Register View_, and removing your old one. You can even add multiple views and have different sets of registers in each.

But yes, it'd still be better to have a way to re-add hidden register groups.

**Comment by derco0n** [comment]
Hi, i just ran into the same issue.
accidentally hided CPU-registers and now have no way to re-enable them.

Any progress on this?

**Comment by eteran** [comment]
No progress yet, but I'll do my best to make it a priority.
