### ISSUE TITLE
double-conversion.h not found

### ISSUE THREAD

**Issue by jpaiotti** [eteran/edb-debugger#710]
I'm trying to upgrade edb to 1.0, but the build accuses "double-conversion not found"
I installed the double-conversion package by github, but the error continues.
Ubuntu 18.04 gcc 7.4 clang 6.0 cmake 3.0
Thank you.

**Comment by 10110111** [comment]
Please post the exact output of the build process. Normally, lack of this package is not an error: the package is optional.

**Comment by jpaiotti** [comment]
jairo@jairo-VS-MCP61M:~/aDownloads/edb-debugger-master$ mkdir build
jairo@jairo-VS-MCP61M:~/aDownloads/edb-debugger-master$ cd build
jairo@jairo-VS-MCP61M:~/aDownloads/edb-debugger-master/build$ cmake ..
-- The CXX compiler identification is GNU 7.4.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:7 (message):
  The git submodules are not available.  Please run:

  git submodule update --init --recursive


-- Boost version: 1.65.1
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- Checking for module 'capstone>=3.0.4'
--   Found capstone, version 3.0.4
-- Checking for module 'libgvc>=2.38.0'
--   Found libgvc, version 2.40.1
-- Checking for module 'double-conversion'
-- Looking for C++ include double-conversion/double-conversion.h
-- Looking for C++ include double-conversion/double-conversion.h - not found
CMake Warning at CMakeLists.txt:66 (message):
  libdouble-conversion header wasn't found.  32- and 64-bit floating-point
  values will be shown with max_digits10 digits of precision instead of
  shortest representation.


-- Checking for module 'gdtoa-desktop'
--   Found gdtoa-desktop, version 0.1.20180730
-- Configuring incomplete, errors occurred!
See also "/home/jairo/aDownloads/edb-debugger-master/build/CMakeFiles/CMakeOutput.log".
See also "/home/jairo/aDownloads/edb-debugger-master/build/CMakeFiles/CMakeError.log".
jairo@jairo-VS-MCP61M:~/aDownloads/edb-debugger-master/build$

**Comment by 10110111** [comment]
The proble is here:

> The git submodules are not available. Please run:
> 
> git submodule update --init --recursive

Not in the double-conversion. But yes, the latter hasn't been found and won't be used.

**Comment by jpaiotti** [comment]
It worked
Thank you for your attention.
