### ISSUE TITLE
Maybe update the screenshot at README

### ISSUE THREAD

**Issue by Petross404** [eteran/edb-debugger#716]
It's been quite some time now that edb is Qt5 software. Maybe a new screenshot with Qt5 will suit better :)

**Comment by 10110111** [comment]
Nothing changed GUI-wise. The look is still the same if using the same style.

**Comment by Petross404** [comment]
Sure, but the oxygen widget style reminds of the old qt4, while qt5 usually uses breeze style. I guess it's a minor (?) detail, but I thought I should share this nonetheless.

Anyway, no harm done after all, edb is very competitive and a precious alternative.

**Comment by 10110111** [comment]
[Current README image](https://raw.githubusercontent.com/eteran/edb-debugger/master/doc/img/edb_interface-2016.png) has non-Oxygen style for the GUI (not sure what it is — seems to be Breeze; I'm using k4oxygen with Qt5 on my machines). It's only KWin that has Oxygen in the screenshot, and this decoration style hasn't even been removed from KF5 (only made fatter).

But your notice may indeed apply to the Wiki, where some of the screenshots are with Breeze, and some are the old Oxygen-styled ones.

**Comment by Petross404** [comment]
Hmm yeah, toolbars seems to be breeze styled. I guess my error originates from the oldish color scheme but anyway. An image speaks a thousand words so screenshots should advertize both edb's functionality and portability by multiple screenshots from multiple platforms. 

I guess this issue is no longer about breeze vs oxygen style, so feel free to close this ;)

**Comment by eteran** [comment]
Some minor changes have occurred recently, so we get a new pic for README!

**Comment by 10110111** [comment]
Given that (according to [this chart](https://gs.statcounter.com/screen-resolution-stats/desktop/worldwide#monthly-201809-201909-bar)) the most common monitor resolutions still are quasi-HD and FullHD (the latter has even smaller share than the former!), are you really sure that such a high-resolution screenshot with size 2600×2109 is a good idea for README? It looks blurry when downsampled (I'm looking from an SXGA monitor), which is not appealing to potential users ;)

**Comment by eteran** [comment]
Ha! I didn't even consider that I was taking the screenshot on a 4K monitor :-).

I'll probably redo it on a standard resolution screen.

**Comment by eteran** [comment]
@10110111 hopefully the new one looks better to more people :-)
