### ISSUE TITLE
Error after launching the tool for Linux packages.

### ISSUE THREAD

**Issue by AnmolMaurya** [eteran/edb-debugger#717]
When the tool is launched , there is an error pops up which shows there is wrong path selection.

I have tried several paths, but it didn't worked and there is no specific instructions as well

**Comment by eteran** [comment]
Can you please say what the exact error is? Is it referring to plugin paths? Are you running it from the build directory, did you "make install", or are you running it from an installation via .deb or .rpm?

**Comment by AnmolMaurya** [comment]
yes, the error is referring to plugin paths.
I have tried make install via .deb

**Comment by eteran** [comment]
OK, can you try removing the .deb files (since I don't know what their origin is), removing `~/.config/codef00.com/edb.conf` and then building and running from the master branch?

**Comment by eteran** [comment]
Closing due to no follow up. Please re-open if the problem persists.
