### ISSUE TITLE
kali linux error

### ISSUE THREAD

**Issue by davidfsnyder** [eteran/edb-debugger#718]
[load_plugins] Cannot load library /usr/lib/x86_64-linux-gnu/edb/libDebuggerErrorConsole.so: (/usr/lib/x86_64-linux-gnu/edb/libDebuggerErrorConsole.so: undefined symbol: _ZN26DebuggerErrorConsolePlugin20DebuggerErrorConsole20compareDisassemblersEv)
Starting edb version: 1.0.0
Please Report Bugs & Requests At: https://github.com/eteran/edb-debugger/issues
comparing versions: [4096] [4096]

I tried issue #690, it didn't help. Thanks for any help.

**Comment by eteran** [comment]
Yea, the Kali version installs a broken debug console plugin. Not much I can do about it since it's long been fixed in master.

But fortunately, it isn't fatal and doesn't prevent any functionality since it is just that one plugin which has a problem.
