### ISSUE TITLE
How to watch the program output?

### ISSUE THREAD

**Issue by ssdemajia** [eteran/edb-debugger#720]
I have a program print some information to console, but I can't find the window to see this information? Where should I open the option?

**Comment by ssdemajia** [comment]
I found that is printed in console I open the edb....

**Comment by eteran** [comment]
If you set the terminal in the settings, edb will indeed open a new window for it.

**Comment by ssdemajia** [comment]
Thank you very much, I found this setting.😊

**Comment by shan8112** [comment]
Can i know how does the terminal can be opened? Where can we find the path?
