### ISSUE TITLE
Improve ability to theme

### ISSUE THREAD

**Issue by eteran** [eteran/edb-debugger#732]
We have **basic** theming capabilities, but plenty of colors are hardcoded. They should all be addressed.

We should also offer the ability to override the system window background colors (like the background of the hex/register/disassembly views) with colors the user can specify.

"dark mode" themes are increasingly popular, and honestly, feel better on the eyes, so we should support this as best we can.

Once complete, will address issue #178

**Comment by eteran** [comment]
Themeing is much better, but not quite there yet.

Still outstanding is:

[] dividing lines in hex and stack views
[] toolbar/menu icons. They are monochromatic black, and need to be white for dark theme
[] breakpoint/IP indicator icons

**Comment by 10110111** [comment]
Will there be (or is there) a GUI for this? It would be good not only for ease of use, but also for discoverability of the feature.

**Comment by eteran** [comment]
Initially no, but once we do a release, probably one of the next major features will be a GUI for the feature.

There's a LOT of knobs that can be adjusted for theming, making a nice GUI for it will likely be complicated.

**Comment by eteran** [comment]
OK, I think basic themeing is **done**. Now we detect the relative brightness of the window background and use either white or black icons depending on which we see.
