### ISSUE TITLE
Release Version 1.1.0

### ISSUE THREAD

**Issue by eteran** [eteran/edb-debugger#734]
It's been a long time since the 1.0 release, and there have been a **ton** of improvements. We should do a 1.1.0 release once I have the icon part of dark themeing sorted out (issue #732).

I have some successful experiments already, I just need to implement them in edb.

After that, I think it's about time.

**Comment by 10110111** [comment]
I think a release should also have the docs updated. Namely the screenshots in the Wiki, which currently
* don't reflect the latest UI changes,
* use different widget styles.

Also some of the screenshots are blurred due to be larger than GitHub column width and thus downsampled. Yes, one can "Open image in new tab" to see it in native size, but it'd be better to make a small version (widgets shrunk to fit), and, if necessary (like for the screenshot of the whole EDB window), be explicitly clickable for a larger version.

**Comment by eteran** [comment]
We can definitely update the UI screenshots 👍

**Comment by 10110111** [comment]
BTW, we should make sure that it at least builds without errors on ARM before release. Currently it fails for me with the following error (apparently, introduced by the refactoring):
```
/home/pi/src/edb-debugger/src/arch/arm-generic/ArchProcessor.cpp: In member function ‘bool ArchProcessor::isExecuted(const Instruction&, const State&) const’:
/home/pi/src/edb-debugger/src/arch/arm-generic/ArchProcessor.cpp:427:42: error: ‘const Instruction {aka const class CapstoneEDB::Instruction}’ has no member named ‘condition_code’; did you mean ‘conditionCode’?
  return is_jcc_taken(state.flags(), inst.condition_code());
                                          ^~~~~~~~~~~~~~
``
So, please either do a build yourself (if you have a Pi or a suitable cross-compiler toolchain), or ping me before you decide to make a release, so that I could test.

**Comment by eteran** [comment]
Of course. I have a pi3 that I had been using during my refactoring. That one was I believe a small change introduced just after it.

I'll make sure it builds! (I wish we had a CI that could do ARM!)

**Comment by eteran** [comment]
@10110111 

So I've fixed the ARM build compilation, but have noticed that I can't get it to load icons on my raspberry pi box. If you have access to one, can you check to see if it's actually a problem or if I've just got my pi machine slightly misconfigured?

As for the 1.1.0 checklist I have as follows:

- [x] Fix ARM builds 
- [x] Complete theme-ability and support for dark themes
- [] Update Screenshots


Assuming the icons is just a machine local config problem, that just leaves screenshots. Unless there is something I'm forgetting.

Let me know!

**Comment by eteran** [comment]
As a follow-up, I'm pretty confident that it's a system config issue and not an edb issue. I just did a windows build and it loads the icons just fine and **certainly** isn't getting them from any system themes.

**Comment by 10110111** [comment]
Icons are loaded fine for me (when I run EDB in a remote X11 session, not sure if it makes a difference).

**Comment by eteran** [comment]
Great, that's 3 data points that say it's fine. I think the 1 is just that config being weird (it's a "pi-top" OS where I just installed Qt, I probably missed a dep or something).

I'm gonna try to update all the screenshots tonight on my 1080p display, and then I think it'll be ready for a 1.1.0 release!

**Comment by eteran** [comment]
@10110111 Screenshots have been updated. Ironically, they look slightly blurry on my 4K screen because they are being scaled up. But I hope they look good for most users. Let me know what you think before I pull the trigger on the release!

**Comment by 10110111** [comment]
That's better, but I think Disassembly View screenshot should definitely be shrunk to 700px width (there's plenty of space on its RHS). Also, Interface screenshot could be shrunk a bit too (there's still some empty space to sacrifice).

Dunno why so many sites insist on such narrow columns, but to look nice our screenshots have to be shrunk to fit.

**Comment by eteran** [comment]
@10110111 OK, Disassembly view is updated to be smaller. I'll see what I can do about the interface one, it looks pretty tight to me, but I'll give it a try. In the meantime. I think we're at a state where a release would be good to go, since it represent well what edb looks like now. We can pixel hunt on the wiki more as we continue to develop.

I've also discovered that the wiki is "just another repo", so I'll probably (post 1.1.0 release) move the images to the edb.wiki repo since they don't need to be the source tree itself.

My plan is to grab some dinner, do one more push to update the version number, and then call it a release!
