### ISSUE TITLE
Can't patch the program (by using assembler)

### ISSUE THREAD

**Issue by orenbenya1** [eteran/edb-debugger#739]
Hey, I try to do the pwnable.kr collision challenge [col.zip](https://github.com/eteran/edb-debugger/files/4075412/col.zip) but the problem is that when I try to debug the program using edb, I want to patch some areas of the code and it says that "Assembler cant be started"...

for example:

When I want to replace this instruction:
![Screenshot (28)](https://user-images.githubusercontent.com/59980489/72590907-907eba00-3907-11ea-9dd3-ebd0828b2492.png)

with this:
![Screenshot (31)](https://user-images.githubusercontent.com/59980489/72590915-95dc0480-3907-11ea-8d50-8d6f2685ee20.png)

I get this result:
![Screenshot (32)](https://user-images.githubusercontent.com/59980489/72590950-abe9c500-3907-11ea-93e3-bbdf768599fb.png)

also when I try to replace this code with simple NOP

**Comment by 10110111** [comment]
The dialog in the first screenshot says that your currently chosen assembler is YASM. Do you have it installed?

**Comment by orenbenya1** [comment]
> The dialog in the first screenshot says that your currently chosen assembler is YASM. Do you have it installed?

thank you ^^ didnt notice that I dont have yasm installed, ^^ (apt-get install yasm worked enough for me)
