### ISSUE TITLE
theme and addresses changed after upgrade kali

### ISSUE THREAD

**Issue by AngelSkull** [eteran/edb-debugger#759]
all addresses in edb starting with 0x00000000address
also menu changed: Run instead of the play button

![image](https://user-images.githubusercontent.com/64097334/79897587-f2076680-83d7-11ea-9ba3-989cacbbd1ba.png)

**Comment by 10110111** [comment]
Is it a 32-bit process that you're debugging?

**Comment by AngelSkull** [comment]
yes, crossfire
it was normal when I started after that I used opcode searcher when the result was blank I thought that it may need update. so updated and upgraded and everything changed after that

**Comment by eteran** [comment]
I'll take a look and see what's going on, it, of course, should not be padding with zeros for 32-bit processes.

**Comment by eteran** [comment]
Sorry for the **long** delay, but I've replicated this issue and am looking into it today.

What do you mean about the "run/play" button though?

**Comment by eteran** [comment]
Should be fixed in the latest master branch. Please reopen if you have any further issues.
