### ISSUE TITLE
Register View

### ISSUE THREAD

**Issue by hxhBrofessor** [eteran/edb-debugger#764]
I'm having trouble finding the appropriate view setting for the "Register" to have it display normal EAX, ECX, EIP, etc...  what mine currently shows is rax, rcx, rbx, and rip, for example. 

This may be simple fix, not sure. Thank you in advance. 

![image](https://user-images.githubusercontent.com/66050673/83097987-a430ee80-a066-11ea-95e4-0a611c65a740.png)

**Comment by 10110111** [comment]
There is no such setting, and it doesn't make much sense generally. When it does make sense, i.e. when you debug a 32-bit process, Register View will automatically show 32-bit registers.

**Comment by eteran** [comment]
@hxhBrofessor it will show 64-bit registers when debugging a 64-bit process, and 32-bit registers when debugging a 32-bit process.

Closing, but please re-open if there is something we are overlooking here.
