### ISSUE TITLE
X server does not support XInput 2

### ISSUE THREAD

**Issue by zhaoxhcqupt** [eteran/edb-debugger#767]
qt.qpa.xcb: failed to initialize XRandr
qt.qpa.xcb: X server does not support XInput 2
Starting edb version: 1.2.0
Please Report Bugs & Requests At: https://github.com/eteran/edb-debugger/issues
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
QXcbConnection: XCB error: 1 (BadRequest), sequence: 164, resource id: 88, major code: 130 (Unknown), minor code: 47
comparing versions: [4608] [4608]

**Comment by eteran** [comment]
Does this affect the functionality of edb? This strikes me as likely an issue with your Qt setup, not edb.

**Comment by eteran** [comment]
Closing since I think this is a Qt issue, and not an edb issue. Additionally, there has been no follow up from the reporter.

Please feel free to reopen if this is not correct.
