### ISSUE TITLE
How can I set the theme to white on a dark-themed system (Support custom color for QDisassemblyView background)

### ISSUE THREAD

**Issue by alloygoh** [eteran/edb-debugger#769]
I would like to set the theme of edb to white as the disassembly is very unreadable on the default dark theme.

**Comment by eteran** [comment]
The theming isn't quite perfect, but it can get you pretty close to looking great on a dark setup. Read here for details on the theming, though< i do fear it may be a little out of date:

https://github.com/eteran/edb-debugger/wiki/Theming

**Comment by alloygoh** [comment]
Is there a specific option to set the disassembly background to white? I can't seem to find it in the wiki.

**Comment by eteran** [comment]
Ah, the background for all windows is set from the system window theme. There isn't an option (yet) to override that with a custom color.

**Comment by alloygoh** [comment]
So the only way to get it to display as white is to change my system theme?

**Comment by eteran** [comment]
Currently, yes.

The mentality is that we want to the disassembly to mimick the look of all the other windows in the app.

However, being able to override the BG color is not unreasonable, I think we can work on adding support for that

**Comment by alloygoh** [comment]
That would be great. Should I open a separate issue for that or would this suffice?

**Comment by eteran** [comment]
This is good enough :+1:

**Comment by junknet** [comment]
I tried to modify the source code through [qt wiki](https://wiki.qt.io/How_to_Change_the_Background_Color_of_QWidget) many times，but but failed..... I'm already dizzy. I think you must have defined the color of the widget's base class before. may be like:
system_color=palette.windows.color() 
But I can't find where it is ！Please help me quickly...

**Comment by eteran** [comment]
Ah, sorry, I got a bit distracted :-P. I'll see what I can do relatively soon :-).

**Comment by eteran** [comment]
There is now a new theme entry: `theme.disassembly.background` which you can use to set the disassembly widget background color.
