### ISSUE TITLE
how to chnage command line IO

### ISSUE THREAD

**Issue by PrithviGudodagi** [eteran/edb-debugger#772]
i tried terminator like terminals to replace xterm as i am not able to paste anything in that but nothing worked an help?

**Comment by eteran** [comment]
Can you show me the settings you used to set the terminal in edb? Do you know if it supports command line flags similar to xterm?

**Comment by PrithviGudodagi** [comment]
Its fine i figured  it out thankyou i rechecked the xterm docs and got a
way to copy
Regards
Prithvi
