### ISSUE TITLE
can't use gnome-terminal as output terminal 

### ISSUE THREAD

**Issue by junknet** [eteran/edb-debugger#774]
DEBUG A Timeout occured while attempting to get the TTY of the terminal sub-process

I don't know why.
OS:archlinux 64

**Comment by eteran** [comment]
Can you share your terminal relevant settings in edb, please? Perhaps a screenshot of the options page?

**Comment by junknet** [comment]
![2020-09-01_21-35](https://user-images.githubusercontent.com/55597646/91857998-3c102b00-ec9b-11ea-9871-886cab01e10a.png)
![2020-09-01_21-36](https://user-images.githubusercontent.com/55597646/91858008-3dd9ee80-ec9b-11ea-96f9-d14b0ef5fb5b.png)

**Comment by eteran** [comment]
Thanks, that should be enough to look into it.

**Comment by eteran** [comment]
Should be fixed in master now (Sorry it took so long for such a simple fix!)

**Comment by junknet** [comment]
Thank you for all your work
