### ISSUE TITLE
UI under newest version of Kali; Can't see text

### ISSUE THREAD

**Issue by roydavisonline** [eteran/edb-debugger#775]
Not sure what the issue is. I am running kali 2020.3. I just installed edb with sudo apt-get install edb-debugger and ran it. I can't see any text in the UI. See screenshot for example.

![Screen Shot 2020-09-03 at 1 16 42 PM](https://user-images.githubusercontent.com/19733012/92163010-e09f8380-ede7-11ea-93d7-e5c7b57c73dd.png)

**Comment by 10110111** [comment]
Is the theme configured somehow, or does this happen with the default system install?

**Comment by roydavisonline** [comment]
This is a default install of kali. I also tried fiddling with the "appearance" theme settings in kali be it didn't seem to make a diff.
![Screen Shot 2020-09-03 at 1 25 56 PM](https://user-images.githubusercontent.com/19733012/92163711-feb9b380-ede8-11ea-8254-8d54c247e68a.png)

**Comment by roydavisonline** [comment]
here you can barely see that the text is white. You can only see it on the slightly grey lines...
![Screen Shot 2020-09-03 at 1 36 55 PM](https://user-images.githubusercontent.com/19733012/92164646-85bb5b80-edea-11ea-8c4e-372ba703a251.png)

**Comment by eteran** [comment]
Well, that's weird...

**Comment by eteran** [comment]
So, this honestly looks like a kali Qt configuration issue.

edb doesn't explicitly set the foreground text color or windows background color in the windows you are showing. It seems that for some reason, list and text box backgrounds are being given a "light" theme, while the text itself is being given a "dark" theme.

I have been considering ways to improve edb's general theming to cover things more completely... but for this specific case, it looks like kali is doing something wrong here.

**Comment by eteran** [comment]
If I implement my plan for #779 then this probably should (hopefully) go away. But it may take a bit to get there...

**Comment by eteran** [comment]
In the latest master, (and soon latest release), you should be able to explicitly choose a dark/light theme which should resolve this issue entirely :-).

Please re-open if this is not the case.

**Comment by roydavisonline** [comment]
awesome. thanks. I'll try it and let you know.

- ROy
