### ISSUE TITLE
Typo in the UI - v.1.2.0

### ISSUE THREAD

**Issue by NotepadExpert** [eteran/edb-debugger#777]
Hello, As seen bellow. There is a typo on the UI in Data Dump section. 

![image](https://user-images.githubusercontent.com/63058148/96459681-4a4de280-121a-11eb-8375-a36496203dfc.png)

The code located at:
./build/src/edb_autogen/include/ui_Debugger.h:437:        dataDock->setWindowTitle(QCoreApplication::translate("Debugger", "Data D&ump", nullptr));

And another one on Stack view. 
![image](https://user-images.githubusercontent.com/63058148/96460089-c1837680-121a-11eb-82be-2766584ab2e2.png)

The code at:
./build/src/edb_autogen/include/ui_Debugger.h:439:        stackDock->setWindowTitle(QCoreApplication::translate("Debugger", "Stac&k", nullptr));

**Comment by 10110111** [comment]
It seems label buddies are broken. An older version, 6764e031c6fe406dd95cc3bf19c9494fc07a3659, running with Qt 5.13, shows underlined letters correctly, although the shortcuts <kbd>Alt</kbd>+<kbd>u</kbd> and <kbd>Alt</kbd>+<kbd>k</kbd> don't change focus.

**Comment by NotepadExpert** [comment]
> It seems label buddies are broken. An older version, [6764e03](https://github.com/eteran/edb-debugger/commit/6764e031c6fe406dd95cc3bf19c9494fc07a3659), running with Qt 5.13, shows underlined letters correctly, although the shortcuts Alt+u and Alt+k don't change focus.

Ahh so that's what it is. Thanks for clarifying.

**Comment by eteran** [comment]
Did we conclude that this isn't a problem with edb itself? Or that it's a Qt configuration or version issue?

**Comment by 10110111** [comment]
I definitely didn't. As you can see in my previous comment, this is a regression in EDB.

**Comment by eteran** [comment]
Interesting. The ampersand conversation to underscores is kinda a built in Qt thing. So not sure where we are going wrong.

**Comment by 10110111** [comment]
The ampersand in a label only appears if the label has a buddy. Also, since it's a regression, `git bisect` is your friend ;)

**Comment by 10110111** [comment]
In fact, I've just checked, and neither with 1.2.0, nor with current master can I reproduce this issue. I'm using Qt 5.13, and accelerators are always underlined for me (don't remember where I configured this option). And I don't get any ampersands in the GUI.

@eteran do you reproduce this problem?

@NotepadExpert what's your Qt version?

**Comment by eteran** [comment]
I've actually NEVER experienced this issue locally that I can recall.

I'm running Qt 5.15 (I tend to upgrade pretty aggressively)

**Comment by eteran** [comment]
Indo suppose that there's no real harm in removing the ampersands from the .ui files for things which have no meaningful focus to switch to 🤷‍♂️

**Comment by 10110111** [comment]
> Indo suppose that there's no real harm in removing the ampersands from the .ui files for things which have no meaningful focus to switch to

Well, I'd expect the focus to switch to the memory views of the _Stack_ and _Dump_ windows. But yeah, if it doesn't work, then may be worth simply removing the fake accelerator.

**Comment by eteran** [comment]
Yes th accelerators don't even do anything, I'll just chop em for those two .

**Comment by eteran** [comment]
Done!

@NotepadExpert please re-open if this problem persists in either master or a release > 1.2.0
