### ISSUE TITLE
Consider updating the C++ and Qt versions we use

### ISSUE THREAD

**Issue by eteran** [eteran/edb-debugger#778]
C++-20 is official standardized and Qt has LONG since moved past version 5.2 we support and has started to release betas of 6.0!

We should consider when to move to C++17 as the standard we work with, and we should also likely pick a newer Qt LTS to require as a new baseline.

@10110111 thoughts?

**Comment by 10110111** [comment]
I'm definitely for it. Some time later we'll be able to also drop `libdouble-conversion` and `libgdtoa-desktop` in favor of `std::to_chars`, which seems to be going to become available for floating-point types in `libstdc++` (and thus GCC) soon: see [mailing list entry](https://gcc.gnu.org/pipermail/gcc-patches/2020-July/550331.html).

**Comment by eteran** [comment]
OK, I think we'll do one more release with C++14 as the baseline (hopefully soon, maybe after I bang out this theme stuff), and then officially switch to using C++17! From a quick look around, we might be able to ditch the boost dependency with this!

The question remains of which version of Qt to "officially" support. Right now I am considering either 5.12  or 5.9.

5.9 is a candidate just because it's about as old as C++17 (give or take) and 5.12 is the current oldest LTS that is still in a support phase. Frankly, even 5.9 would be a pretty big jump

**Comment by eteran** [comment]
Done! master branch now uses C++17 and has a minimum requirement of Qt-5.9.

So, @10110111 if there are any parts of the codebase you've been itching to modernize with new C++17 goodies, have at it!
