### ISSUE TITLE
Could you help me with this error please

### ISSUE THREAD

**Issue by sasky621** [eteran/edb-debugger#780]
DEBUG Running Terminal:  "/usr/bin/xterm"
DEBUG Terminal Args:  ("-title", "edb output", "-hold", "-e", "sh", "-c", "tty > /tmp/edb_temp_file_1319970107_11615;trap \"\" INT QUIT TSTP;exec<&-; exec>&-;while :; do sleep 3600; done")
DEBUG Could not launch the desired terminal ["/usr/bin/xterm"], please check that it exists and you have proper permissions.
DEBUG Terminal process has TTY:  ""
DEBUG comparing versions: [4608] [4608]
WARN  QXcbConnection: XCB error: 3 (BadWindow), sequence: 629, resource id: 11947434, major code: 40 (TranslateCoords), minor code: 0

**Comment by eteran** [comment]
You need to install `xterm`

**Comment by eteran** [comment]
Or set the terminal a different one of your choosing, `konsole` and `gnome-terminal` are both reasonably well suported
