### ISSUE TITLE
[Suggestion] AppImage releases

### ISSUE THREAD

**Issue by Ristovski** [eteran/edb-debugger#781]
Having AppImages of `edb` would be a nice and portable way of having binary releases that work everywhere. 
Has this been considered? 

It could even be automated by setting up Github Actions to build/package an AppImage release automatically.

Just a suggestion that would be very welcome.

**Comment by eteran** [comment]
LOL, We actually **used** to have an AppImage. But during an update to upstream AppImage, it was broken. I wasn't sure if anyone used it, so I just chopped it from the `.travis.yml` file. Perhaps we should re-add it and fix it :-).
