### ISSUE TITLE
Arch Linux Failed to successfully load debugger core plugin

### ISSUE THREAD

**Issue by qumusabel** [eteran/edb-debugger#782]
Hello,

I've been trying to build edb on arch linux for a while now. At first there were issues with cmake not finding boost. In the end I was able to build it, but when I run it this message pops up:
```
Failed to successfully load the debugger core plugin. Please make sure it exists and that the plugin path is correctly configured.
This is normal if edb has not been previously run or the configuration file has been removed.
```

What I've tried:
- specifying `edb-debugger/build/plugins` in the settings
- removing `directory.plugin.path` from `~/.config/codef00.com/edb.conf`, as suggested in #623

**Comment by eteran** [comment]
OK, a few thoughts:

1. have you by any chance installed edb in some other way? If so, it is recommended to still to one way
2. If not... can you look in the `edb-debugger/build/plugins` and do an `ls *.so` to see if the plugins are found in there?

**Comment by qumusabel** [comment]
1. I've tried multiple methods to install edb, first from AUR, then converting .deb to Arch package (almost worked, it was missing `libcapstone`). Finally I've tried building from the sources, and it worked besides the plugins issue. First time I did `make && make install`, this time I've built it to `build/` and wiped all the files from previous `make install` attempt. 
2. This is what's in `build/plugins` https://pastebin.com/ZmnM633Z. No `.so` files

**Comment by qumusabel** [comment]
I ran `make` in `build/plugins`, and turns out they haven't been built yet, which is really strange. I expected them to be built with everything else...

**Comment by eteran** [comment]
They certainly should have been built with everything else. By default, then end up in the same directory as edb itself, which is `build/`

**Comment by IdanBanani** [comment]
Ubuntu, no .so files in plugins directory for me. 
![image](https://user-images.githubusercontent.com/26879273/102069350-50b99e80-3e06-11eb-81c8-2dad3464b19d.png)

I tried to follow exactly the install instructions.

maybe it's because edb was installed previously? (came built in) and needs to be removed first?

**Comment by qumusabel** [comment]
@IdanBanani try `make` in `build/` or `build/plugins`

**Comment by IdanBanani** [comment]
> @IdanBanani try `make` in `build/` or `build/plugins`

Didn't work.

**Comment by IdanBanani** [comment]
![image](https://user-images.githubusercontent.com/26879273/102074161-02f46480-3e0d-11eb-9df5-9cf330fae54a.png)

**Comment by eteran** [comment]
@IdanBanani do you have `.so` files in the **build** directory? That's where the plugins should end up.

**Comment by eteran** [comment]
@qumusabel did you resolve the issue by pointing the settings at `build/` since that's where the plugin `.so` files should be?

**Comment by qumusabel** [comment]
> @qumusabel did you resolve the issue by pointing the settings at `build/` since that's where the plugin `.so` files should be?

Yes, that's what I did after build.

**Comment by eteran** [comment]
Also, @IdanBanani ,

If there is a copy of edb install system wide, it is recommended to uninstall it to avoid any conflicts.

**Comment by IdanBanani** [comment]
> Also, @IdanBanani ,
> 
> If there is a copy of edb install system wide, it is recommended to uninstall it to avoid any conflicts.

As suggested in the top of the page: 
This one solved it!
"removing directory.plugin.path from ~/.config/codef00.com/edb.conf, as suggested in #623"

+No idea how I could uninstall (through sudo apt-get remove edb/edb-debugger) ? 
or something like "make clean" command?

**Comment by eteran** [comment]
@IdanBanani you will need to remove it through the package manager.

**Comment by eteran** [comment]
@IdanBanani I am assuming based on "This one solved it!", that this is no longer an issue, so I'm closing this issue. Please re-open if  this issue is not resolved.
