### ISSUE TITLE
Breakpoint manager does not import/export breakpoints

### ISSUE THREAD

**Issue by sayboltm** [eteran/edb-debugger#801]
Using EDB v1.3.0, commit 39925b68375be2bb70a9df539d897c944a3c4d1b

I feel right at home in EDB, or at least as home as it seems I can be, jumping back into this hobby/work after totally removing Windows and its familiar but dated PE32s from my life. Thanks for making something that looks and sort of feels like Olly DBG!

When in breakpoint manager (Ctrl+B), 
![image](https://user-images.githubusercontent.com/25088020/108095897-5cb41d80-704e-11eb-96bc-3d7b1a494a16.png)

clicking "Import Breakpoints" results in the dialogue going dark,
![image](https://user-images.githubusercontent.com/25088020/108095946-69387600-704e-11eb-8c18-6aed60dd50f7.png)

and the console in the background shows:
`Gtk-Message: 11:45:17.481: GtkDialog mapped without a transient parent. This is discouraged.
`

I can provide additional details if needed. I installed using the very nice and simple standard build in the readme. Any help or ideas appreciated!

**Comment by 10110111** [comment]
What value does `QT_QPA_PLATFORMTHEME` environment variable have?

**Comment by sayboltm** [comment]
$QT_QPA_PLATFORMTHEME
appears to be unset, and/or doesn't appear in env

desktop is `GNOME`

`env | grep QT` returns only `QT_IM_MODULE=ibus`

running centOS 8 if that helps

**Comment by 10110111** [comment]
Does it work if you unset `XDG_CURRENT_DESKTOP` or set it to e.g. `kde`?

**Comment by eteran** [comment]
Well that's certainly a weird one! Any luck with @10110111's suggestions?

**Comment by sayboltm** [comment]
I ran into some difficulty installing kde on my last known good kernel (working on display issues with latest one), but in the process I tried simply using other desktops.

Classic (X11 display server)
      
which results in: 

`XDG_CURRENT_DESKTOP=GNOME-Classic:GNOME`

or 

Standard (X11 display server) on Xorg

which results in 

`XDG_CURRENT_DESKTOP=GNOME`

and

`XDG_SESSION_dESKTOP=gnome-xorg` (vs just `gnome`)
and I have all 3 monitors working, without this issue showing up. It appears it does not like Wayland, though it was also working there.

To reproduce this darkened screen and no dialogue, I login with `Standard` (Wayland)`, this only runs 2/3 monitors, so I drop a runlevel with `systemctl isolate multi-user.target`, then startx manually, to get the 3rd monitor on. Janky procedure, I know, but I was just happy to get it to go so I could keep working. Now I see Wayland must be causing some kind of problem with my gpu conf etc.

It is following this process the above issue occurs. I am not sure what would be different starting X that way, vs logging in using `Classic (X11 display server)` or what appears to be identical but must not be, logging in using `Standard (X11 display server) on Xorg`. I am new to centOS and aware that it is maybe not the best desktop candidate, but I wanted to try out RHEL and GPU passthrough and figured what's the worst that can happen using as a desktop for a bit.

I'll close it, but happy to hear any other suggestions. Thanks for the help!

**Comment by 10110111** [comment]
In fact, I wasn't suggesting to switch DE or windowing system, just to alter the environment variable for EDB — so that Qt didn't try to use its GTK plugin.

**Comment by sayboltm** [comment]
So, ignore what I said, during my tests, I did not load the executable I was working on <facepalm>. This occurs once the binary is loaded, and you click import.

However, @10110111 is right, and that unsetting the environment variable EDB sees does change its behavior! I do not see the GTK message, and the window does not go dark and not work. It looks older, but works!

**Comment by 10110111** [comment]
> It looks older, but works!

Could you show a screenshot? Qt doesn't seem to have an "old" style by default...

**Comment by sayboltm** [comment]
Sure! .. Looks 'old' but I like its behavior more

![image](https://user-images.githubusercontent.com/25088020/108610257-5b625800-73a2-11eb-993e-258dc49a1976.png)

I have seen it a few times in different programs, and prefer its "windows-like" behavior of being able to press the first letter of a folder instead of search, and had not yet had the time to get to 'nice to have' customization like that.

**Comment by sayboltm** [comment]
I don't recall the state of this, I think changing the `XDG_CURRENT_DESKTOP` helped, though I did that through changing my desktop at the login screen of CentOS. My system became unstable after a kernel update, losing my monitors and delaying my progress posting back here. sorry about that. I will close! (and post back if have more details)
