### ISSUE TITLE
Failed to open and attach to process: execv() failed: Exec format error.

### ISSUE THREAD

**Issue by MikeTheScriptKid** [eteran/edb-debugger#804]
I'm getting this error when trying to open my .exe file and I can't find any solution for it.
Does anybody know how to fix this?

![Screenshot 2021-05-08 04:42:56](https://user-images.githubusercontent.com/79508710/117533258-cf7fc580-afb9-11eb-85b1-780574f1dec4.png)

**Comment by 10110111** [comment]
Looks like [this FAQ entry](https://github.com/eteran/edb-debugger/wiki/FAQ#can-use-edb-on-linux-to-debug-or-analyze-windows-executables).

**Comment by lotation** [comment]
I have the same isse and I've just compiled it with gcc on Arch Linux

**Comment by eteran** [comment]
@lotation Are you trying to open a Windows executable? As answered above, this is not supported.
