### ISSUE TITLE
Edb - Debugger could not restore edi register display

### ISSUE THREAD

**Issue by IGTHESHY2018** [eteran/edb-debugger#818]
<img width="356" alt="image" src="https://user-images.githubusercontent.com/55623291/173659352-b7cc453c-75ed-4721-a3a5-70e48ec61a41.png">
I accidentally hid several registers such as edi and eax,ebx when I used deb-debugger. Then the bad thing came, they became unrecoverable - none of the operations could make them show up again

**Comment by 10110111** [comment]
If you right-click in the _Registers_ window, there'll be a "*Show hidden group >*" item, where you can restore the group you hid.

**Comment by eteran** [comment]
@IGTHESHY2018 Going to close since I believe that @10110111's suggestion will work for you. Please re-open the issue if it does not.
