### ISSUE TITLE
Debugger doesn't respect Signal Ignore Preferences

### ISSUE THREAD

**Issue by AaronOpfer** [eteran/edb-debugger#819]
Despite configuring preferences like so:

![image](https://user-images.githubusercontent.com/1189089/174524287-12107d92-8e00-4860-94c1-4a5460676095.png)

edb does not pass through signals to the debuggee, and instead pauses the program.

![image](https://user-images.githubusercontent.com/1189089/174524234-0172b242-89aa-480d-b78c-7528e4dd8698.png)

Reproduction steps:
 * Attach edb to a process
 * Configure edb to pass through the signal
 * Send a signal that should be ignored to that process `kill -s SIGUSR1 <pid>`
 * Observe that edb does not ignore the signal but instead pauses the application

**Comment by AaronOpfer** [comment]
Fixing this may be as simple as adding `return null_ptr` here:
https://github.com/eteran/edb-debugger/blob/master/plugins/DebuggerCore/unix/linux/DebuggerCore.cpp#L535

**Comment by eteran** [comment]
@AaronOpfer Hmm, interesting. So it seems like we are continuing the process with the appropriate signal code, but are still delivering the event to the other layers.

We'll have to make sure that the calling code is appropriately tolerant of nullptr's, but the solution may be that simple. Have you tried it at all with success?

**Comment by AaronOpfer** [comment]
Yes, it seems like adding that return statement fixes the problem.

**Comment by eteran** [comment]
Fixed pushed. I confirmed that we actually safely return `nullptr` elsewhere from this function, so we can assume it is safe to do so where you recommended.
