### ISSUE TITLE
edb debugger giving normal application exit message when the application has crashed

### ISSUE THREAD

**Issue by OldSchoolHackerGit** [eteran/edb-debugger#835]
Hi, 

I am working on a program for pentesting prepration and knows the value at which it should crash. I am seeing edb debugger is not giving segmentation fault rather exiting normally. Need to check the issue. Thanks in advance.

![image](https://user-images.githubusercontent.com/124121101/223722677-1232de30-fb23-4d0e-82f1-20a13c8712ad.png)

Also it was not finding the JMP ESP instruction as in this issue --> https://github.com/eteran/edb-debugger/issues/723

I tried re-installing using the steps give here and found an error relating to qt5-default.
![image](https://user-images.githubusercontent.com/124121101/223723834-32be4f1a-4f33-45b4-8de8-fd8055195d18.png)

https://github.com/eteran/edb-debugger/wiki/Installing.

Need some assistance in resolving the error or removing edb completely & re-installing from scratch

**Comment by 10110111** [comment]
How do you know the app really crashes?

**Comment by OldSchoolHackerGit** [comment]
> How do you know the app really crashes?
Thanks for responding.

Because added a segmentation fault in it by overwriting the EIP. At some point in time edb was reporting it correctly then stopped working.

**Comment by OldSchoolHackerGit** [comment]
> apt show qt5-default qtbase5-dev
> cat /etc/lsb-release
> cat /etc/issue

[File1.txt](https://github.com/eteran/edb-debugger/files/10921917/File1.txt)
![image](https://user-images.githubusercontent.com/124121101/223750596-6ef8a642-220b-4b5b-ac74-4d062dc1b66c.png)
![image](https://user-images.githubusercontent.com/124121101/223750785-2c1a0cd3-793f-4c0a-a694-5f1747ca095c.png)

Attaching requested files, I'm not very familiar with Linux so please don't hesitate to let me know in case osme of the commands are to be run differently. Also I am able to identify the reason for the app not crashing , so edb was correctly identify a good exit and your comment let me think over it. Thanks for that. 
The problem was that it was looking for a particular file and that edb has to be run from the directory where the app is placed, referencing does not work which is weird. I've reported it to the developers. 

Now moving on, I am trying to understand why opscode searcher is not picking jmp esp instruction, which is similar to the other issue I"ve marked initially. I also installed via apt, is there still aproblem that installation needs to be carried out via GIT path. Much appreciate your time into it.

**Comment by 10110111** [comment]
Text should never be posted as images, at least if the goal is not to show how it's rendered: it's not possible to copy and paste it easily.

> Package: qt5-default
> Version: 5.7.1+dfsg-3+deb9u3
> ...
> APT-Sources: /var/lib/dpkg/status

This seems to imply that you have somehow installed a very old version of `qt5-default` (maybe years ago), and the current version from the repository is incompatible with it. Try removing this package, and see if it drags something else with it (`apt` will ask you whether you want to continue if you don't force "yes" answers, so you can check before removing too much).

> Now moving on, I am trying to understand why opscode searcher is not picking jmp esp instruction, which is similar to the other issue I"ve marked initially. I also installed via apt, is there still aproblem that installation needs to be carried out via GIT path.

There might be a problem if the version of EDB that you have installed is older than the commit that fixed issue #723 that you linked to. You can check EDB version either by `edb --version`, or by `apt show edb` (substitute `edb` with the actual name of the package here).

**Comment by OldSchoolHackerGit** [comment]
Thanks for your time into this. After long hours of troubleshooting, I identified the problem to be with the program I was attaching the debugger to and reported accordingly. This is resolved for me now
