### ISSUE TITLE
New Release ?

### ISSUE THREAD

**Issue by motorto** [eteran/edb-debugger#838]
Would it be possible to create a new release ? The current one is almost 3 years old...

Would it make it easier for package maintainers to package it to their distro. (I am one, and we don't accept git master tarballs, only stable releases).

**Comment by eteran** [comment]
Absolutely, there is actually been a lot of work over the last 3 years. It's probably about time to tag it as a release 🙂

**Comment by eteran** [comment]
1.4.0 Released!
