### ISSUE TITLE
Chinese localization

### ISSUE THREAD

**Issue by xfan-hack** [eteran/edb-debugger#841]
The interface of edb tool is developed based on QT? I would like to do a Chinese language operation of the interface, where is the corresponding ts file? Thanks for your help!

**Comment by eteran** [comment]
Thank you for your interest and for reminding me of this task. Yes it is Qt based and can be translated. I will first need to edit the code to make it load translation files.

Things have been very busy lately, but I will try to make the necessary changes and get you the needed information as soon as possible!

**Comment by pt-hack** [comment]
Thanks, I'm patiently waiting for your results, do programmers in your country have more energy to work on open source code?

**Comment by pt-hack** [comment]
> Thank you for your interest and for reminding me of this task. Yes it is Qt based and can be translated. I will first need to edit the code to make it load translation files.
> 
> Things have been very busy lately, but I will try to make the necessary changes and get you the needed information as soon as possible!

Things have been very busy lately, but I will try to make the necessary changes and get you the needed information as soon as possible!

**Comment by xfan-hack** [comment]
thank you

**Comment by xfan-hack** [comment]
Is there any development plan for the Chinese localization?

**Comment by eteran** [comment]
Thanks for the follow up! I'll try to make some progress on this soon 🙂

**Comment by eteran** [comment]
@xfan-hack 

OK, so sorry for the delay on this, but I have progress for you !

I just merged in a few small changes that add the foundation for translation support. All that is left is for contributors to make PRs adding translation files. I'll make up some instructions and hopefully people can help going forward.

**Comment by eteran** [comment]
@xfan-hack Here's some instructions on how to do it.

https://github.com/eteran/edb-debugger/wiki/Translating

Let me know if you have any questions or issues

**Comment by eteran** [comment]
@xfan-hack another user had contributed a translation and it's testable with `LANG=zh_CN ./edb` in master now!

That being said, I'm sure that the translation could use some more work, so please, if you are still interested in doing so, feel free to improve it.

Also, @10110111 , any interest in a translation to your native language? If so, let me know and I can help with any technical issues you run into
