### ISSUE TITLE
Failed to start assembler (Couldn't Launch Assembler) - version 1.2.0 & 1.3.0

### ISSUE THREAD

**Issue by Jay1508** [eteran/edb-debugger#845]
Hi,
I a new user of edb debugger, I loaded an ELF 64-bit file in it and wanted to modify a CPU instruction (from a je to jmp). So I went onto the instruction, press bar and changed it from je to jmp. However I keep getting this error message. I tried on version 1.2.0 and 1.3.0. Can anyone help me with fixing this issue? thank you
![1](https://github.com/eteran/edb-debugger/assets/36248389/1148de4b-e625-4396-9d72-cfdb89748ac2)

**Comment by Jay1508** [comment]
I can see those error messages. 
RUNNING ASM TOOL:  "/usr/bin/yasm" ("-f", "bin", "/tmp/edb_asm_temp_721281_LwhHBn.asm", "-o", "/tmp/edb_asm_temp_721281_REfeSe.bin")
Warning: terminator_CreateInstance: Failed to CreateInstance in ICD 3.  Skipping ICD.
error: XDG_RUNTIME_DIR is invalid or not set in the environment.
error: XDG_RUNTIME_DIR is invalid or not set in the environment.

**Comment by eteran** [comment]
Do you have yasm installed?

**Comment by Jay1508** [comment]
yes sorry it wasn't installed. I thought it would be initially installed on REMnux

**Comment by Jay1508** [comment]
fixed, yasm wasn't installed
