### ISSUE TITLE
Wiki: Compiling (Ubuntu) needs dependencies updated

### ISSUE THREAD

**Issue by colematt** [eteran/edb-debugger#846]
**For Ubuntu >= 15.10**

```
# install dependencies
sudo apt-get install       \
    cmake                  \
    build-essential        \
    libboost-dev           \
    libqt5xmlpatterns5-dev \
    qtbase5-dev            \
    qt5-default            \
    libqt5svg5-dev         \
    libgraphviz-dev        \
    libcapstone-dev        \
    pkg-config
```

Should now be **For Ubuntu >= 22.04 LTS** 

- `qt5-default` no longer exists and has been replaced by `qtbase5-dev qt5-qmake`
- `libdouble-conversion-dev` avoids "CMake Warning at CMakeLists.txt:49 (message): libdouble-conversion header wasn't found.  32- and 64-bit floating-point values will be shown with max_digits10 digits of precision instead of shortest representation."

```
# install dependencies
sudo apt-get install         \
    cmake                    \
    build-essential          \
    libdouble-conversion-dev \
    libboost-dev             \
    libqt5xmlpatterns5-dev   \
    qtbase5-dev              \
    qt5-qmake                \
    libqt5svg5-dev           \
    libgraphviz-dev          \
    libcapstone-dev          \
    pkg-config
```

**Comment by 10110111** [comment]
> Should now be For Ubuntu >= 22.04 LTS

20.04 has still not reached EOL. The fixes seem to be compatible with it though.

**Comment by eteran** [comment]
Done!
