### ISSUE TITLE
Qt5LinguistToolsConfig Error - qttools5-dev is a prerequisite

### ISSUE THREAD

**Issue by waterwin** [eteran/edb-debugger#849]
looks as if missing some dependencies :

```
-- gdtoa-desktop package wasn't found. Using built in version.

But more importantly :
CMake Error at /usr/lib/x86_64-linux-gnu/cmake/Qt5/Qt5Config.cmake:28 (find_package):
  Could not find a package configuration file provided by "Qt5LinguistTools"
  with any of the following names:

    Qt5LinguistToolsConfig.cmake
    qt5linguisttools-config.cmake
```

After some googling :
in Ubuntu 18.04+ you need to install also qttools5-dev in order to get `/usr/lib/x86_64-linux-gnu/cmake/Qt5LinguistTools/Qt5LinguistToolsConfig.cmake`

Installing these solves that issue.

**Comment by waterwin** [comment]
When starting : it also needs xterm !

**Comment by waterwin** [comment]
After installing still stuck when trying to open a .sh file

Failed to open and attach to process:
execv() failed: Permission denied.

**Comment by eteran** [comment]
Did you try following the wiki?

https://github.com/eteran/edb-debugger/wiki/Compiling-(Ubuntu)

As for running a .sh file, keep in mind that the target needs to be executable by the OS. So make sure the permissions are correct.

Also, do keep in mind that if you try to debug a .sh file, you'll be debugging the shell that is running the script. Which may or may not be what you actually want.

**Comment by eteran** [comment]
Also, xterm is technically optional, it's just warning you that it wanted to run it to show the application output, but it's ok if it can't, it'll just output to the term that owns edb

**Comment by waterwin** [comment]
Thank you for your reaction. Yes I followed the Wiki to the letter. And had to install the prereq qttools5-dev which is not in your list I think.
After googling the issue :
As mentioned here : The problem was that in Ubuntu 18.04+ you need to install also qttools5-dev in order to get /usr/lib/x86_64-linux-gnu/cmake/Qt5LinguistTools/Qt5LinguistToolsConfig.cmake.

xterm is indeed just a warning.

I can start the program, see the windows and try to Open a file, then it all stops.

**Comment by eteran** [comment]
OK, I'll take a look and ensure the requirements are correct for 18.04+.

I suspect that you have a permissions issue. When you ask edb to open a `.sh` file (for example `script.sh`), this is comparable to running `./script.sh` on the command line. So please ensure that doing that works. But to reiterate, just to be clear, when you debug a script, you are really debugging the **interpreter** not the script itself.

That may be your intention, but if you are hoping to be able to debug the state of the script itself, while that is **possible** it is a very challenging task.

**Comment by eteran** [comment]
I think this had to do with the new internationalization stuff I added to support other languages. Added it as a depenency to the wiki!
