### ISSUE TITLE
aarch64 Support

### ISSUE THREAD

**Issue by fairycn** [eteran/edb-debugger#855]
The current build on an Arm 64 ubuntu system gives the following error
![image](https://github.com/eteran/edb-debugger/assets/74580422/e2bfc47b-f711-4d20-9835-9988fed2cf57)
Ask how to solve or support arm 64 version OS

**Comment by eteran** [comment]
Well, @10110111 does most of the ARM stuff, so with anything deeper than this, he'd be best to respond... but I can help with that specific error by modifying the cmake script to support "aarch64" as an acceptable name for arm64. I can push a tweak in just a little bit.

**Comment by eteran** [comment]
merged! should get you passed that particular error

**Comment by 10110111** [comment]
I no longer have access to any hardware suitable for development on/for ARM. But I should tell, AArch64 is very different from 32-bit ARM, so such a simple fix might yield little.

**Comment by eteran** [comment]
@10110111 good to know, it should get detected as arm64 though, so at least it'll TRY to use the right architecture 🤷🏻
