### ISSUE TITLE
Symbol addresses off by constant offset

### ISSUE THREAD

**Issue by Talndir** [eteran/edb-debugger#857]
Using Ubuntu 22.04 on WSL2 (Windows 11).

Every symbol from the PLT is off by exactly 0x1e0. For example, in the symbol table it shows that `puts@plt` is at 0x.....3070, but the code actually calls 0x......3250. Because of this, library functions are shown as an address rather than as a name, making it difficult to see what is going on. Local jumps are still correct and show the correct name, but library symbols are off, and all addresses seem to be off by the same amount.

I know the addresses are incorrect because GDB shows the correct function names. See screenshots below:

![image](https://github.com/eteran/edb-debugger/assets/24933589/600b9533-2650-4df0-8662-8da06084f010)

![image](https://github.com/eteran/edb-debugger/assets/24933589/a947e5dc-4c87-4c9d-9ce8-2a7011d43f58)

(I apologise for the terrible colour scheme.)

**Comment by eteran** [comment]
Interesting, we'll have to look into it. Is it with every program, or just this one? Is there an ideal way to reproduce the issue (I often use WSL2 so I can look into it using that)

**Comment by Talndir** [comment]
It's happening with everything. Here's one I just coded up, this time the offset is 0x20:

`#include <stdio.h>

int main()
{
    puts("Hello, world!");
    return 0;
}`

![image](https://github.com/eteran/edb-debugger/assets/24933589/ef56fc9a-8387-4197-a911-70d45862bed3)
![image](https://github.com/eteran/edb-debugger/assets/24933589/109af67f-4b65-41b4-9018-ad9918ecb021)

**Comment by eteran** [comment]
Great, I'll take a look in the next couple of days (I'm not at my usual work laptop until like Tuesday)

**Comment by eteran** [comment]
OK, I have reproduced the issue locally and am looking into it!

**Comment by eteran** [comment]
Interesting, I have boiled it down to the PLT having a slightly different layout when the application is built `-fcf-protection` enabled.

Setting `-fcf-protection=none` when building the app "fixes" the issue. But... obviously we'd like to have edb support both cases.

**Comment by eteran** [comment]
@Talndir I possibly have a fix commited.

**Important note**: edb caches the symbols it generates and only recalculates them if the binary looks different. Since we've only changed how symbols are computed, and not the binaries themselves... we'll need to invalidate the cache. So you will need to run:

```
rm -rf ~/.cache/codef00.com/edb/symbols/
```

to delete existing cache entries for the new code to take effect. Please let me know if this solves the problem for you.

**Comment by Talndir** [comment]
I can confirm the fix worked! I had indeed observed that the PLT looked weird, almost duplicated, and had these `endbr` instructions everywhere, but hadn't realised it was specifically because of the branch protection!
