### ISSUE TITLE
Compilation error 

### ISSUE THREAD

**Issue by rach1tarora** [eteran/edb-debugger#865]
home/user/edb-debugger/src/ByteShiftArray.cpp: In member function ‘ByteShiftArray& ByteShiftArray::shr()’:
/home/user/edb-debugger/src/ByteShiftArray.cpp:61:21: error: ‘class QVector<unsigned char>’ has no member named ‘rbegin’; did you mean ‘begin’?
   std::rotate(data_.rbegin(), data_.rbegin() + 1, data_.rend());
                     ^~~~~~
                     begin
/home/user/edb-debugger/src/ByteShiftArray.cpp:61:37: error: ‘class QVector<unsigned char>’ has no member named ‘rbegin’; did you mean ‘begin’?
   std::rotate(data_.rbegin(), data_.rbegin() + 1, data_.rend());
                                     ^~~~~~
                                     begin
/home/user/edb-debugger/src/ByteShiftArray.cpp:61:57: error: ‘class QVector<unsigned char>’ has no member named ‘rend’; did you mean ‘end’?
   std::rotate(data_.rbegin(), data_.rbegin() + 1, data_.rend());
                                                         ^~~~
                                                         end
src/CMakeFiles/edb.dir/build.make:286: recipe for target 'src/CMakeFiles/edb.dir/ByteShiftArray.cpp.o' failed
make[2]: *** [src/CMakeFiles/edb.dir/ByteShiftArray.cpp.o] Error 1
CMakeFiles/Makefile2:646: recipe for target 'src/CMakeFiles/edb.dir/all' failed
make[1]: *** [src/CMakeFiles/edb.dir/all] Error 2
Makefile:145: recipe for target 'all' failed
make: *** [all] Error 2

Ive tried almost every workaround, unable to do so

```
Ubuntu 16.04.7 LTS \n \l\

g++ (Ubuntu 7.5.0-3ubuntu1~16.04) 7.5.0


gcc (Ubuntu 7.5.0-3ubuntu1~16.04) 7.5.0
```

**Comment by 10110111** [comment]
The missing function was introduced in Qt 5.6. Your distribution has reached its EOL almost 3 years ago, so you need to upgrade something. Your whole Ubuntu, or Qt from Qt's official installer, or build Qt from sources.

**Comment by eteran** [comment]
Yeah, as a baseline, we are currently targeting Qt 5.15 LTS as that is the current supported LTS version of Qt

**Comment by rach1tarora** [comment]
thank you, yeah i was dumb enough to not realize that.
