### ISSUE TITLE
Unable to display the value of registers such as rax

### ISSUE THREAD

**Issue by fengtao918** [eteran/edb-debugger#868]
When debugging a program on Ubuntu on x86-64, the values ​​of registers such as rax and rbx cannot be displayed. Is there any way to display them? Thanks!
![image](https://github.com/user-attachments/assets/35d3f5ea-d375-4f54-96a3-821581de70c6)
I can't right-click to display registers such as rax.
![image](https://github.com/user-attachments/assets/0ee1989c-79b8-4efe-9a29-6ff14706e629)

**Comment by 10110111** [comment]
How did you hide them? If everything works right, the menu should also have an entry "GPRs". What is the contents of `[ODbgRegisterView]` section in `~/.config/codef00.com/edb.conf`?

**Comment by fengtao918** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by fengtao918** [comment]
[ODbgRegisterView]


views\1\visibleGroups=GPR, rIP, ExpandedEFL, Segment, EFL, FPUData, FPUWords, FPULastOp, Debug, MMX, SSEData, AVXData, MXCSR
views\2\visibleGroups=GPR, rIP, ExpandedEFL, Segment, EFL, FPUData, FPUWords, FPULastOp, Debug, MMX
views\size=2
![image](https://github.com/user-attachments/assets/ea8d256c-c614-46d0-a66e-2b9c1e506300)
I compiled the code and ran it and found that it was like this, and I didn't actively hide it。
No GPRs on the menu either
![image](https://github.com/user-attachments/assets/81967647-6ee6-466f-9c3e-a9d8b0014b05)

**Comment by fengtao918** [comment]
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.3 LTS
Release:	22.04
Codename:	jammy

This computer is running edb for the first time, compiled from the latest code downloaded from git

**Comment by fengtao918** [comment]
My virtual machine has multiple snapshots. I rolled back to the previous location and installed edb with the following command
The rax register appeared successfully.
![image](https://github.com/user-attachments/assets/83e3c48c-aee6-493f-a4da-a07a9d20180b)

[ODbgRegisterView]
views\1\visibleGroups=GPR, rIP, ExpandedEFL, Segment, EFL, FPUData, FPUWords, FPULastOp, Debug, MMX, SSEData, AVXData, MXCSR
views\size=1

**Comment by fengtao918** [comment]
I restored the virtual machine snapshot and started from scratch. After downloading the code and compiling it, I opened the software and did not configure it. There was still no rax register. This may be a bug in the latest version.
![image](https://github.com/user-attachments/assets/0044f877-fd75-4f44-a505-9807b4f809fc)

**Comment by 10110111** [comment]
Could you try using git-bisect to find the commit that broke this?

**Comment by fengtao918** [comment]
ok ！I'll try it tomorrow

**Comment by epasveer** [comment]
> Could you try using git-bisect to find the commit that broke this?

Learned a new git command today... :^)

**Comment by eteran** [comment]
This is very strange. Please do see if you can find the commit that caused the issue. I don't even recall the last time the code for the register display was touched in a meaningful way.

**Comment by fengtao918** [comment]
![image](https://github.com/user-attachments/assets/f41f6bd0-29d1-4e64-b1bb-53a95e3a7928)
I found the commit where the problem first occurred. 
9ed4c86
It seems that the problem is caused by the change of Chinese translation.
I found out where the bug is triggered!

The following two places will not trigger the bug if they are not translated
General Purpose
General Status
![image](https://github.com/user-attachments/assets/c1c40750-335b-49e8-9cc9-8f342610b09a)
I canceled the translation of the above two places, and the rax and other registers are displayed.

**Comment by fengtao918** [comment]
Now I am using the latest version of the software, which also cancels the above two translations, and the rax, rip and other registers show success
![image](https://github.com/user-attachments/assets/04e7c484-32fe-4ea1-9124-10ba7495ed1c)

**Comment by 10110111** [comment]
Apparently, this is related to the fact that `GprCategoryName` is used without being passed to `QObject::tr()`. Similarly to `"General Status"` passed into `find_model_category`, which is also suspicious.
Generally, now that we have a translation, the whole principle of using the name as the internal id looks ugly.

**Comment by fengtao918** [comment]
Yes!
edb-debugger-master\plugins\ODbgRegisterView\ODbgRV_Common.h
static constexpr const char *GprCategoryName = "General Purpose";
The above GprCategoryName is not included by tr

When I try to use the translated text directly, rax is displayed.
![image](https://github.com/user-attachments/assets/edfd64cf-494a-4999-b163-5e718325d3d0)

**Comment by eteran** [comment]
Awesome work guys! 

@10110111 since you've narrowed it down a bit, any chance you've got time to make a quick PR for this? I'm a bit busy today and am just starting the work day.

**Comment by 10110111** [comment]
I don't think a *quick* fix is the way to go. The whole structure of the code looks quite strange to me now, particularly the sole named string out of all the register categories. I'd need to study the code properly to make a sensible fix that would not be just a workaround.

**Comment by eteran** [comment]
If you think that's best, I trust your judgement 🙂.

**Comment by 10110111** [comment]
So, it seems that
1. To make things work with the translations, we need plugins to be translatable, while currently they aren't (right?). Particularly, my attempts at calling `tr("General Purpose")` from `ODbgRegisterView` returned the original string.
2. The translations of the register categories aren't user-visible since the time the legacy register view was removed (was it?). It may make sense to actually remove all the `tr()` calls for categories and simply use the English strings as ids.

**Comment by 10110111** [comment]
Actually, if we run `lupdate` not only on `src` directory but also on `plugins`, then things (after my local changes) start working, and a myriad of untranslated strings from the plugins appears. This should be done anyways, in a separate change.

The point 2 above is still valid though.

**Comment by eteran** [comment]
@10110111 yea, the legacy register view is long gone. In fact, I'd support a separate effort to "de-plugin" this feature to be honest since it's so fundamental.

Anyway, let me know if/when your PR is ready and i'll merge it.
